### ISSUE TITLE
PropertiesAutowired() malfunction

### ISSUE THREAD

**Issue by chrisxvin** [autofac/Autofac#732] opened 2016-04-01 08:54 UTC
This is my code:
`var reg = m_builder.RegisterType<TService>()
    .Named<TService>(name)
    .AsSelf()
    .AsImplementedInterfaces()
    .PropertiesAutowired()
    .OnActivated(a => a.Instance.Initialize());
`
And when I acquire a service, its properties are null.
This happens on Autofac 4.0.0-rc1 with .Net 4.6.1. Same code under Autofac 3.5.2 with .Net 4.0 is correct. All properties can be autowired.

**Comment by tillig** [comment] 2016-04-01 14:10
Are the properties coming from a base class? We had a similar sounding issue that was resolved for an early RC2 build: https://github.com/autofac/Autofac.Configuration/issues/2

That one hasn't released on NuGet but is on our MyGet feed.

**Comment by tillig** [comment] 2016-04-29 19:44
Given the derived-class-properties thing was fixed and we don't have a repro for any additional issues related to property autowiring failing, I'm going to close this. If it turns out the issue isn't fixed and we can get a repro, we can re-open it and solve the issue at that time.

**Closed by tillig** 2016-04-29 19:44 UTC
