### ISSUE TITLE
ReflectionActivator / DefaultValueParameter do not throw DependencyResolutionException when using EnableClassInterceptors()

### ISSUE THREAD

**Issue by danneberg** [autofac/Autofac#759] opened 2016-06-14 11:59 UTC
When registering a class with dependencies there is no exception raised when dependency is not registered in case of using EnableClassInterceptors(). 

```
using System;
using Autofac;
using Autofac.Core;
using Autofac.Extras.DynamicProxy2;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace AutoFact
{
    public class Part
    {
    }

    public class Aggregate
    {
        public Aggregate(Part part)
        {
            Console.WriteLine("\n\nConstructor called with following parameters:");
            Console.WriteLine("Part is [{0}]", part == null ? "null" : part.ToString());
        }
    }

    [TestClass]
    public class UnitTest5
    {
        [TestMethod]
        [ExpectedException(typeof(DependencyResolutionException))]
        public void ExceptionThrownWhenDependencyNotRegistered()
        {
            var builder = new ContainerBuilder();

            builder
                .RegisterType<Aggregate>();

            var container = builder.Build();

            container.Resolve<Aggregate>();
            /*
                Test method AutoFact.UnitTest5.TestMethod1 threw exception: 
                Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'AutoFact.Aggregate' can be invoked with the available services and parameters:
                Cannot resolve parameter 'AutoFact.Part part' of constructor 'Void .ctor(AutoFact.Part)'.
             */
        }

        [TestMethod]
        [ExpectedException(typeof(DependencyResolutionException))]
        public void ExceptionThrownWhenDependencyNotRegisteredAndClassInterceptors()
        {
            var builder = new ContainerBuilder();

            builder
                .RegisterType<Aggregate>()
                .EnableClassInterceptors();

            var container = builder.Build();

            container.Resolve<Aggregate>();
            /*
                Test method AutoFact.UnitTest5.ExceptionThrownWhenDependencyNotRegisteredAndClassInterceptors did not throw an exception. An exception was expected by attribute Microsoft.VisualStudio.TestTools.UnitTesting.ExpectedExceptionAttribute defined on the test method.

                Constructor called with following parameters:
                Part is [null]
             */
        }
    }
}
```

Using the following Versions:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Autofac" version="3.5.2" targetFramework="net451" />
  <package id="Autofac.Extras.Attributed" version="3.3.0" targetFramework="net451" />
  <package id="Autofac.Extras.DynamicProxy2" version="3.0.7" targetFramework="net451" />
  <package id="Autofac.Mef" version="3.0.3" targetFramework="net451" />
  <package id="Castle.Core" version="3.3.3" targetFramework="net451" />
</packages>
```

The problem is that the Registration Extension creates an implementation type with Castle.DynamicProxy.DefaultProxyBuilder 
(registration.ActivatorData.ImplementationType = (Type) RegistrationExtensions.ProxyGenerator.ProxyBuilder.CreateClassProxyType((Type) registration.ActivatorData.ImplementationType, additionalInterfaces ?? new Type[0], options);
).
The constructor of this type has all parameters ar marked with "HasDefaultValue" and a Default value of DBNull even when the supporting base class does not have any default values defined.
As a result DefaultValueParameter returns true in method CanSupplyValue.

**Comment by tillig** [comment] 2016-06-14 14:37
Nice catch, and thanks for helping track down what's up. We're a little backed up with .NET Core right now, but will do our best to see if we can remedy the issue as soon as that lets up a bit.

**Comment by brunojcm** [comment] 2017-07-17 09:03
Same as https://github.com/autofac/Autofac.Extras.DynamicProxy/issues/14 ?

**Comment by tillig** [comment] 2017-07-17 12:18
Duplicate of autofac/Autofac.Extras.DynamicProxy#14

**Closed by tillig** 2017-07-17 12:18 UTC
Labels: bug
