### ISSUE TITLE
Add generic counterparts for TryResolveNamed, TryResolveKeyed and TryResolveService

### ISSUE THREAD

**Issue by lukoerfer** [autofac/Autofac#1263] opened 2021-03-24 11:21 UTC
## Problem Statement
The static class `ResolutionExtensions` provides a set of extension methods to manually resolve instances from a container. Some of these methods (e.g. `Resolve` and `TryResolve`) have a generic counterpart (`Resolve<T>` and `TryResolve<T>`), but others, namely `TryResolveNamed`, `TryResolveKeyed` and `TryResolveService`, dont.

## Desired Solution
The generic counterparts could just call the non-generic extension methods and then cast the `out` parameter in the same way as the generic version `TryResolve`.

## Alternatives You've Considered
Right know, one can either write their own extension methods or use other workarounds (e.g. resolve `IIndex<string, T>` and use `TryGetValue` as an alternative to `TryResolveNamed`).

## Additional Context
None

**Comment by lukoerfer** [comment] 2021-03-24 11:25
I can offer to prepare a pull-request with the changes I described above. Right now, it seems like there are no specific tests for many of the extension methods in `ResolutionExtensions`, so please give advice if there would be a need for additional tests.

**Comment by alsami** [comment] 2021-03-26 05:40
> I can offer to prepare a pull-request with the changes I described above. Right now, it seems like there are no specific tests for many of the extension methods in `ResolutionExtensions`, so please give advice if there would be a need for additional tests.

If that's a valid use case and you feel like sending a PR our way that would be great. My feeling is that whenever there is something new added, adding tests for those specific bits makes sense.

**Comment by alistairjevans** [comment] 2021-03-26 11:54
I actually got a little confused myself the other day by the absence of generic forms of `TryResolveNamed`, so I strongly agree with @alsami; if you're willing to add the methods and associated tests, that would would be great.

As a related note, you can just about use `if (ResolveOptionalNamed<IService>("name") is IService service)` to work-around this right now, but it's not as nice as `TryResolveNamed`.

I'm not sure of the benefit of `TryResolveService<>` over `TryResolve<>`?

**Comment by v0idzz** [comment] 2021-08-29 17:58
Since there has been no activity here for a long period of time, I decided to work on it and I already have some progress. However, as mentioned above, is there any benefit of `TryResolveService<>` over `TryResolve<>`? Or should I skip this one?

**Comment by alistairjevans** [comment] 2021-08-29 18:00
Thanks for picking this up @v0idzz. 

I think `TryResolveService` would just be a duplicate of `TryResolve`, so yes, skip it.

**Closed** 2021-08-29 18:38 UTC

**Comment by maulik-modi** [comment] 2021-10-11 05:28
@lukoerfer , Do you have anything else to add?
