### ISSUE TITLE
Thread safe reference "publishing" for objects that are created by container

### ISSUE THREAD

**Issue by pwnded** [autofac/Autofac#1088] opened 2020-02-26 12:02 UTC
When you create an object (via ctor invokation or using activator) there are 3 well-known steps that should be invoked in the following sequence (ideally): memory allocation in heap, c'tor invokation and linking reference from stack with object in memory. For the single thread, out of order (due to compiler optimizations or out of order read/write operations in processor, see MESI protocol) here is not a big deal. But, for multithreaded use-cases there can be a chance to consume a reference to an not yet initialized object (so-called out of order "publishing", see J.Richter for details).

The solution is to "publish" reference to the local variable (local reference in stack), and then distribute it using memory barrier to shared ("public") reference in stack.

I've faced such issue in Autofac (4.9.4), when my instance of particular type "A" is resolved and passed as an dependency to another class "B" (which performs call of some public API from "A"), but c'tor is not invoked yet on instance of "A". It leads to exception (for example, null reference because some filed is not initialized in ctor yet).

Extremly hard to reproduce (not possible for me, only few times for different customers).

Of cource, there is workaround to check if initialized in public API.
P.S: filed initialization in ctor of type "A" takes care about memory barries (MESI) and thread-safe reference "publishing" for the filed.

Could you please check the issue? Is it possible to provide possibility for thread safe reference "publishing"? Or make it an default implementation. Of cource, perf. degradation is expected in such cases due to memory barriers.

Thank you,

**Comment by weelink** [comment] 2020-02-28 09:04
This is a weird story. I have never heard something like this, where the compiler makes optimizations so that multithreading is basically broken and unusable. And you''ve experienced it several times with different customers. This makes me believe there might be something else going on.

Just for some clarification:
- How do you know this is the cause of the exception, since you can't reproduce it?
- Where is the multithreading in this scenario? "A" has to be created on thread 1 and "B" on thread 2. I don't think that this is possible if Autofac is in full control of the creation and initialization. Do you have some custom code that can interfere with the process?
- What do you mean by "thread safe reference publishing"? How does that look like?
- If compiler optimizations breaks multithreading, how is this something Autofac should fix? Shouldn't this be reported to the MS compiler team?
- If this can't be reproduced easilty, what is there to check?

**Comment by weelink** [comment] 2020-03-16 11:53
No update in 19 days. So I suggest to close this.

**Comment by alistairjevans** [comment] 2020-03-16 11:55
Agreed, thanks @weeklink. If more information comes available, we can re-open this issue.

**Closed by alistairjevans** 2020-03-16 11:55 UTC
