### ISSUE TITLE
ComponentNotRegisteredException is not serialized properly

### ISSUE THREAD

**Issue by MpDzik** [autofac/Autofac#631] opened 2015-04-04 12:38 UTC
ComponentNotRegisteredException is not marked with the SerializableAttribute, and therefore when the exception is passed between an AppDomain boundry, the following exception occurs:

System.Runtime.Serialization.SerializationException: Type 'Autofac.Core.Registration.ComponentNotRegisteredException' in Assembly 'Autofac, Version=3.5.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' is not marked as serializable.

I can provide a pull request to fix this.

**Comment by tillig** [comment] 2015-04-04 18:28
Duplicate of #456.

Exceptions in portable classes libraries can't be marked serializable. See #456 for a detailed explanation.

**Closed by tillig** 2015-04-04 18:28 UTC
Labels: duplicate
