### ISSUE TITLE
Autofac.Web calling Autofac v 3.4.0.0 even when Autofac 3.5.2.0 is installed

### ISSUE THREAD

**Issue by dougajmcdonald** [autofac/Autofac#664] opened 2015-07-24 11:03 UTC
I am using the NuGet Autofac package Autofac.Web (v 3.2) on .Net Framework 4.0.

Oddly when I update Autofac from 3.4 to 3.5.2.0 no amount of binding redirects seem to solve an explicit call to Autofac version 3.4.0.0.

I've logged the calls to the Assembly bindings and whilst my packages.config lists:

  <package id="Autofac" version="3.5.2" targetFramework="net40" />
  <package id="Autofac.Web" version="3.2.0" targetFramework="net40" />

I still get a call to 3.4:

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Autofac, Version=3.4.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da
 (Fully-specified)

etc etc

This fails as the version I have installed is 3.5.2 so it fails with a version incompatibility and gives me this at runtime:

Could not load file or assembly Autofac, Version=3.4.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da or one of its dependencies. The located assemblys manifest definition does not match the assembly reference.

Any thoughts?

**Comment by tillig** [comment] 2015-07-24 15:03
Can you post a repro somewhere? My first thought is "binding redirect" but since that's not working, I'd need to actually see it in action.

**Comment by hackfaq** [comment] 2015-07-25 19:27
can you post bind redirect config ? it works if redirected to 3.5.0.0, not 3.5.2.0

**Comment by dougajmcdonald** [comment] 2015-07-30 07:39
HI Guys, thanks for the reply's, the binding redirect I'm happy with:

      <dependentAssembly>
        <assemblyIdentity name="Autofac" publicKeyToken="17863af14b0044da" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.5.0.0" newVersion="3.5.0.0" />
      </dependentAssembly>

What's even more weird is that if I update to version 3.5.2 via nuget, I get the errors I described in the original post, but if I then downgrade to 3.4.0.0 I get a red squigly trying to use the method I want, but the app compiles and runs fine.

What's even weirder still is that the app compiles and runs, only if I don't build the app from a file with one of the red squigglies in it! If I try to build with the file in the attached screenshot as the active window, I get the errors shown in screenshot 2!

![missing method with 3 4](https://cloud.githubusercontent.com/assets/1190042/8977981/e702886c-3695-11e5-82e9-7efca908c181.PNG)

![error if build from file with missing method](https://cloud.githubusercontent.com/assets/1190042/8978043/715800fa-3696-11e5-8f2f-f90d63a88d82.PNG)

**Comment by tillig** [comment] 2015-07-30 14:17
Unfortunately, we're still going to need a repro on this in order to see it in action and troubleshoot. There's not enough information here to determine the root cause of the issues.

**Comment by tillig** [comment] 2015-09-04 15:50
Given there's been no repro posted and we can't help without that, I'm going to close this issue. If you can post a repro so we can see it and help, feel free to comment and we can reopen as needed.

**Closed by tillig** 2015-09-04 15:50 UTC

**Comment by ederbond** [comment] 2015-09-04 16:30
I'm facing the same issue. 
Have an Asp.NET Web.Forms application using .net framework 4.5.2 on Visual Studio 2015 and have installed the following packages on it:

<package id="Autofac" version="3.5.2" targetFramework="net452" />
<package id="Autofac.Web" version="3.2.0" targetFramework="net452" />

have the follwoing assembly binding configuration on my Web.Config file:

<dependentAssembly>
        <assemblyIdentity name="Autofac" publicKeyToken="17863af14b0044da" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.5.0.0" newVersion="3.5.0.0" />
</dependentAssembly>

But I get an error while the application start telling me that it could not load Autofac 3.4.0.0
A operação falhou.
Resultado da associação: hr = 0x80131040. Nenhuma descrição disponível.

Gerenciador de assemblies carregado de:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Executando sob executável  C:\Program Files (x86)\IIS Express\iisexpress.exe
--- Segue um log detalhado de erros. 

=== Informações sobre estado pré-associação ===
LOG: DisplayName = Autofac, Version=3.4.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da
 (Fully-specified)
LOG: Appbase = file:///D:/Monitor/CheckList/Monitor/WebApp/
LOG: PrivatePath inicial = D:\Monitor\CheckList\Monitor\WebApp\bin
LOG: Dynamic Base = C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\553fa0ce
LOG: Cache Base = C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\553fa0ce
LOG: AppName = fb0240b6
Chamando assembly: Autofac.Integration.Web, Version=3.2.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da.
===
LOG: esta associação começa no contexto de carregamento default.
LOG: usando arquivo de configuração de aplicativo: D:\Monitor\CheckList\Monitor\WebApp\web.config
LOG: usando arquivo de configuração de host: C:\Users\eder.cardoso\Documents\IISExpress\config\aspnet.config
LOG: usando arquivo de configuração da máquina de C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: referência pós-política: Autofac, Version=3.4.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da
LOG: a pesquisa de GAC não foi bem-sucedida.
LOG: tentando download de nova URL file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/Temporary ASP.NET Files/root/553fa0ce/fb0240b6/Autofac.DLL.
LOG: tentando download de nova URL file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/Temporary ASP.NET Files/root/553fa0ce/fb0240b6/Autofac/Autofac.DLL.
LOG: tentando download de nova URL file:///D:/Monitor/CheckList/Monitor/WebApp/bin/Autofac.DLL.
LOG: o download do assembly foi bem-sucedido. Tentando configuração do arquivo: D:\Monitor\CheckList\Monitor\WebApp\bin\Autofac.dll
LOG: entrando na fase de configuração do cache de download.
LOG: o nome do assembly é: Autofac, Version=3.5.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da
AVI: a comparação de nome de assembly resultou na incompatibilidade: Minor Version
ERR: a referência do assembly não correspondeu à definição de assembly localizada.
ERR: falha na configuração com hr = 0x80131040.
ERR: falha ao concluir configuração do assembly (hr = 0x80131040). Probing encerrado.

**Comment by tillig** [comment] 2015-09-04 16:34
Thanks for posting, but we still need a repro.

**Comment by ederbond** [comment] 2015-09-08 13:08
Thanks for replying tilling,
just found the problem.
My asp.net web.forms application was using setting an attribute ' appliesTo="v2.0.50727" ' on the     <assemblyBinding appliesTo="v2.0.50727" xmlns="urn:schemas-microsoft-com:asm.v1"> tag.
After removing the "appliesTo" attribute from the assembly binding tag and setting the AssimblyBinding as follows it worked perfectly:

<dependentAssembly>
        <assemblyIdentity name="Autofac" publicKeyToken="17863af14b0044da" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.5.0.0" newVersion="3.5.0.0" />
      </dependentAssembly>

**Comment by PGardockiDotNet** [comment] 2018-01-08 20:52
Another area to check is the web.config file to see if it is calling the dll with an older version number.
