### ISSUE TITLE
Deadlock on resolution of IIndex

### ISSUE THREAD

**Issue by andrewspiteri** [autofac/Autofac#1288] opened 2021-09-05 18:23 UTC
Seems to be a bug unless I'm doing something very stupid from my part: 

using keyed services is causing the application to deadlock. Upon investigation the culprit seems to be resolution of an IIndex service:  IIndex<string, IRestContentSerializer> in my case. 

Part of code getting in a deadlock:

```
  if (!_serializersFactory.TryGetValue(contentType, out IRestContentSerializer serializer))
    throw new InvalidOperationException($"Unable to locate serializer for content type {contentType}.");`
````

Caller:

``` 
public static Task ForEachAsync<T>(this IEnumerable<T> collection, Func<T, Task> itemCallback, CancellationToken cancellationToken = default)
{
    return Task.WhenAll(collection.Select(i =>
    {
        Task? p() => itemCallback(i);
        return Task.Run(p, cancellationToken);
    }));
}
```

My module setup

```     
protected override void Load(ContainerBuilder builder)
{
    builder.RegisterType<RestClientService>().As<IRestClientService>()
        .InstancePerLifetimeScope();

    builder.RegisterType<ContentSerializers.JsonRestContentSerializer>()
        .Named<IRestContentSerializer>(ContentType.Json);

    builder.RegisterType<ContentSerializers.TextRestContentSerializer>()
        .Named<IRestContentSerializer>(ContentType.Text);
     
    builder.RegisterType<DefaultRestClientRequestFactory>()
        .As<IRestClientRequestFactory>();

    base.Load(builder);
}
```

Stack:
![image](https://user-images.githubusercontent.com/10126706/132133524-120e4da8-b8ac-4669-8b7f-348029c9015c.png)

Tasks:
![image](https://user-images.githubusercontent.com/10126706/132133559-dcab7275-5ea0-4198-8480-3e66b52aedcb.png)

**Comment by tillig** [comment] 2021-09-05 19:38
I'm going to respond here so you know you're not being ignored, but you might not like the response. 😞 

**I'm not _personally_ going to be able to debug this.** This is due to a couple of reasons. First, there's not really enough information here to go on. The screen shots do show there may be something blocked, but there's a lot of other stuff going on here - it's not a minimal repro. Second, this sort of thing usually takes a long time to unwrap. Time that, I'm sad to say, I don't _personally_ have.

However, you might be able to help unwind it yourself, and if you can really narrow it down and do the leg-work here, you can probably get a fix faster (or figure out what's up in your code, if it's not Autofac).

First, I'd recommend creating a minimal repro. Like, super minimal - unit test level, if possible. I recommend this because in creating the repro and peeling back the layers of your custom code you may see where the problem is. Maybe it stops happening when you change something. Or, if you can really trim it down, you'll reduce that call stack and the number of moving pieces enough that we might be able to spend a much smaller amount of time with it - either way, it's a win.

Second, I'd recommend checking out [our debugging and troubleshooting documentation](https://autofac.readthedocs.io/en/latest/advanced/debugging.html). This tells you not only how to get some logging going on (so you might be able to see what's trying to resolve what) but also notes we [have Source Link enabled on all of our packages](https://github.com/dotnet/sourcelink) so you could hypothetically step right into the Autofac source to see what's up.

I do see that the notion of `IIndex<>` is [just handled like an open generic](https://github.com/autofac/Autofac/blob/f52dc4d877aaa7428b93ccf799a0e4a265a88c85/src/Autofac/ContainerBuilder.cs#L227) where the [value is lazy-resolved](https://github.com/autofac/Autofac/blob/f52dc4d877aaa7428b93ccf799a0e4a265a88c85/src/Autofac/Features/Indexed/KeyedServiceIndex.cs#L34). The lock we end up taking [is in the `DefaultRegisteredServicesTracker` for the lifetime scope](https://github.com/autofac/Autofac/blob/f52dc4d877aaa7428b93ccf799a0e4a265a88c85/src/Autofac/Core/Registration/DefaultRegisteredServicesTracker.cs#L293) However, there's only one instance of that per lifetime scope so I'm not sure how it'd deadlock off the top of my head - one thing would get the lock, the other would wait.

Hence the need to whittle this down a bit. I don't see the call stack in your screen shot getting that deep, so I'm not sure what the lock is.

I'm going to mark this as a question until we get more input on what's going on.

**Comment by andrewspiteri** [comment] 2021-09-07 05:00
I'll try to attach the source to my project and debug it a bit. Unfortunately it's not easy to replicate and you are correct it's a bit of a complicated scenario. Will let you know my findings.

**Comment by andrewspiteri** [comment] 2021-09-07 20:08
The issue resides in the usage of the lock statement in the lifetimescope class. Like you, I still cannot understand exactly why it should deadlock. 

If the creator initiates another thread which in turns tries to create a shared instance (of something else) while the lock is still in place it will deadlock.   
 
I can assume that you added the global lock() statement as a concurrent dictionary might call the creator() method more than once.  

When we had a similar issue, we added another dictionary, with the Ids and just an object (to use as the lock cookie). This should have the side effect to improve performance as well. With some minor additional memory footprint. 

If you agree I can create a pull request with a simple fix as follows... however note that I don't know Autofac code in detail. 

the code would look something like this:
`
        private readonly ConcurrentDictionary<Guid, object> _lockCookies = new ConcurrentDictionary<Guid, object>();

        /// <inheritdoc />
        public object CreateSharedInstance(Guid id, Func<object> creator)
        {
            if (creator == null)
            {
                throw new ArgumentNullException(nameof(creator));
            }

            //instead of using 1 object for all, since you don't need to.. 
            object lockCookie = _lockCookies.GetOrAdd(id, (i) => new object());

            lock (lockCookie)
            {
                if (_sharedInstances.TryGetValue(id, out var result))
                {
                    return result;
                }

                result = creator();
                if (_sharedInstances.ContainsKey(id))
                {
                    throw new DependencyResolutionException(string.Format(CultureInfo.CurrentCulture, LifetimeScopeResources.SelfConstructingDependencyDetected, result.GetType().FullName));
                }

                _sharedInstances.TryAdd(id, result);

                return result;
            }
        }
`


![image](https://user-images.githubusercontent.com/10126706/132290977-64f9bb69-bb37-4be0-ae0d-62795edbc7df.png)

**Comment by alistairjevans** [comment] 2021-09-07 20:36
Just wanting to make sure I understand what's going on here, do you have a component that, in the constructor:

1. Spins up another thread
2. Passes the lifetime scope into that new thread
3. Attempts to resolve an instance of a shared component from that same scope?
4. Blocks the constructor until that other thread is finished resolving things?

It's worth noting that the `_synchRoot` object is not completely global, the lock is specific to the current `ILifetimeScope`.

**Comment by andrewspiteri** [comment] 2021-09-07 20:48
I have a lifetimescope which i'm initializing my application with. At one point I have a collection for which I loop through it async. The loop is dummy like shown at the start of the thread above (as in it just dumps all the collection in the task scheduler to be picked up, since it contains a handfull of items). Each of these items will resolve my IRestClientService implementation, which will try to resolve the content serializer. At that point, everything gets locked up. 

The rest client is configured to create 1 instance per lifetimescope as per start of thread therefore creating a shared instance...
`
            builder.RegisterType<RestClientService>().As<IRestClientService>()
                .InstancePerLifetimeScope();
`

This is designed like this, so that requests can be queued, short circuited if server is down etc... 


![image](https://user-images.githubusercontent.com/10126706/132408733-f37ed66b-8113-45f2-b6d9-6f704ff95039.png)

**Comment by tillig** [comment] 2021-09-07 21:00
I'm a little underwater with the day job at the moment, but my gut is telling me that you'd want to do something like create a separate lifetime scope for each of these queued tasks rather than trying to share a single lifetime scope across them. On the other hand, if it's just (basically) this...

```c#
var scope = container.BeginLifetimeScope();
var tasks = new Task[100];
for(int = 0; i < 100; i++)
{
  tasks[i] = Task.Run(() => DoSomethingAsyncWith(scope));
}
await Task.WhenAll(tasks);
```

I'm still not sure how it's getting into a deadlock. I saw that `serializerFactory` reference and that makes me think there's more async going on here than just the one loop. I don't know what the factory is doing to resolve the registered things, like if it, too, has a lock somewhere for example.

Sorry I'm sort of jumping in and out here. Fires to fight and all that. I just feel like maybe there's more than just the one lock being contended for. I'm having a rough time seeing how a synchronous resolution to something is getting into a deadlock there without some sort of, like, circular dependency or similar.

**Comment by alistairjevans** [comment] 2021-09-07 21:00
Does each ContentSerializer also directly or indirectly reference IRestClientService?

**Comment by andrewspiteri** [comment] 2021-09-12 18:21
Hi, 

My apologies for the late reply as I was rather busy. It happens anywhere you resolve an object that is defined as instance per lifetimescope from multiple threads. 


The issue is that I cannot replicate it in a simple project so there must be something more to it. 

Then I do the following change to the lifetime scope class, the issue is resolved. But I'd rather understand exactly why before. 

![image](https://user-images.githubusercontent.com/10126706/132998465-5ae8f049-ef8c-4947-bbb2-f3c64fb024de.png)

**Comment by tillig** [comment] 2021-09-12 21:13
I'm really reluctant to mess with the locking here without actually knowing _exactly why_ this fixes it. Over the course of the years in Autofac we've tried to modify/optimize locking and this is usually one of those areas where changing it in one place inadvertently affects assumptions made in another place.

Also, this is sort of hot-path stuff so adding a lock lookup will affect resolution perf for every shared object resolve. People get to be [real sticklers about nanosecond-level DI benchmarks](https://ipjohnson.github.io/DotNet.DependencyInjectionBenchmarks/) so we really need to know what's going on so we can fix it.

This is happening with _literally any object_ getting resolved from the same lifetime scope but different threads?

Like, hypothetically, this is could deadlock?

```c#
var b = new ContainerBuilder();
b.RegisterType<object>().InstancePerLifetimeScope();
var c = b.Build();
using var scope = c.BeginLifetimeScope();

var tasks = new Task[1000];
for(var i = 0; i < 1000; i++)
{
  tasks[i] = Task.Run(() => scope.Resolve<object>());
}

Task.WaitAll(tasks);
```

I'm honestly not trying to be difficult or pedantic, it's just we _really_ need to figure out how the deadlock is happening. If we're using the same lock object for resolving things in the lifetime scope, the only way I can see to get deadlock is if there's some sort of circular dependency - thing A needs thing B; thing B needs thing A.

In a lot of cases we'll see this happen if there's something like service location going on during construction. Like:

```c#
public class MyThing
{
  public MyThing(ILifetimeScope scope)
  {
    var dependency = scope.Resolve<Dependency>();
  }
}
```

If you did something like this...

```c#
var b = new ContainerBuilder();
b.RegisterType<MyThing>().InstancePerLifetimeScope();
b.RegisterType<MyDependency().InstancePerLifetimeScope();
var c = b.Build();
using var scope = c.BeginLifetimeScope();

// Uh oh
scope.Resolve<MyThing>();;
```

The `MyThing` can't finish constructing without doing its own resolve, but the lock on the scope is already acquired because `MyThing` is in the resolve process. It can't do its own separate resolve and get the lock, sooooo deadlock.

Anyway, that's why it's important to understand more about what's going on here. I see that `serializersFactory` thing and I don't know what it's doing or when it's being called. There's async going on, but I can't tell if there's something intermixed with combined DI and service location.

**Comment by tillig** [comment] 2022-02-23 19:41
This has been sitting for a few months and we don't have a repro where we can see it and figure out what's going on, so we're pretty much stuck at the Autofac end. Given that, I'm going to close this.

If we can get a repro, we might be able to move forward, but the repro needs to be as absolutely simple as possible - not a giant ASP.NET Core project with a million handlers and loggers and crazy stuff. Boil it down to as small as it can get and still see the problem. (Usually we find that by doing that it's also easier to see "whoops!" sorts of things where maybe something isn't being handled right. It's much harder to find those needles buried in a giant haystack of code.)

While I recognize that there seemed to be a fix using multiple locks, we would need to understand exactly why that's fixing it and what other things might break if that change was made, hence the need to understand this on a deeper level.

If we can get that repro and a better understanding of the situation, we can reopen this issue and hopefully drive it to resolution.

**Closed by tillig** 2022-02-23 19:41 UTC
Labels: question, pending-input

**Comment by mddddb** [comment] 2025-01-16 13:35
Hi @tillig, I am more familiar with the .NET DI terms, so I will be using those, and my repro is also using .NET DI API.
Not sure if I can resurrect this issue, so let me know if I need to create 

We are hitting a similar issue with Singleton (Shared in Autofac?) services like in the repro below:

```csharp
using Autofac;
using Autofac.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;
using System.Threading;

namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var serviceCollection = new ServiceCollection();

            serviceCollection.AddSingleton(sp =>
            {
                return new ServiceA();
            });

            serviceCollection.AddSingleton<ServiceB>(sp =>
            {
                ServiceA serviceA = null;

                // start new thread
                var thread = new Thread(() =>
                {
                    serviceA = sp.GetService<ServiceA>();
                });
                thread.Start();
                thread.Join();

                return new ServiceB(serviceA);
            });

            var containerBuilder = new ContainerBuilder();
            containerBuilder.Populate(serviceCollection);

            var container = containerBuilder.Build();
            var serviceProvider = new AutofacServiceProvider(container);

            var serviceB = serviceProvider.GetService<ServiceB>();
        }
    }

    public class ServiceA
    {
    }

    public class ServiceB
    {
        public ServiceB(ServiceA serviceA)
        {
        }
    }
}
```

What we see happening is that
- we start running the implementationFactory delegate (instantiator delegate of the service) for ServiceB from thread1 during the resolution of the service
- thread1 gets the lock for `_synchRoot` of `LifetimeScope` ([here](https://github.com/autofac/Autofac/blob/72e8422491f935874e851a1e8d65e353c2cb7e93/src/Autofac/Core/Lifetime/LifetimeScope.cs#L258C1-L259C1))
- we try to resolve the ServiceA that is a dependency of ServiceB in thread2
- the implementationFactory delegate of ServiceA also tries to obtain the lock for `_synchRoot` of `LifetimeScope` in thread2
- thread2 is waiting for the lock, while thread1 is waiting for thread2
- deadlock

We also noticed that this specifically affects running the `implementationFactory` for the first time, i.e. while instantiating the Singleton/Shared instance. If the instances are already created before (service resolution already called) - the multithreaded resolution of the services is not an issue. I.e. if we do `serviceProvider.GetService<ServiceA>()` before resolving the ServiceB - there is no deadlock

The same code does not cause a deadlock with .NET DI implementation.

Based on what we see in https://autofac.readthedocs.io/en/latest/advanced/concurrency.html#deadlock-avoidance, `All container operations are safe for use between multiple threads` when it comes to resolution of services after the container is configured.
However, this bevahior does not seem to follow the statement in the docs, unless we misunderstood something.

Could you please help us here?

**Comment by tillig** [comment] 2025-01-16 13:49
I think you might be stretching the meaning of the statement in the docs. 

The intent of the statement is to say that is you have a container or scope you can have two different threads do two totally separate operations and it's fine. 

It didn't mean you could try to split one resolve operation across threads. The provider inside the lambda - the one you're passing to a different thread - is basically the same as the one doing the resolve outside the lambda. It's one big operation happening, not two separate operations. So you're trying to resolve part of a thing on one thread and part of a thing on a different thread. 

You can't do that. The whole operation must happen on one thread. 

Think of service resolution like running a constructor: it needs to be fast and it can't be async. There's no multi threaded constructor support in C# right? Same here.

If you can repro this without the threading, you might have something. If there's a simple fix that doesn't mess with the other locking we have to ensure proper sharing of single instances and such (no removal of existing locks, no new options to "opt out" of locking, etc.), we'd be happy to look at a PR.
