### ISSUE TITLE
BeginLifetimeScope with configurationAction drops IComponentRegistry.Registrations

### ISSUE THREAD

**Issue by willportnoy** [autofac/Autofac#852] opened 2017-05-16 17:58 UTC
I reproduced this issue with Autofac 3.5.2 but others have reported it with Autofac 4.5.0. (https://github.com/Microsoft/BotBuilder/issues/2277).

This is my actual usage:
https://github.com/Microsoft/BotBuilder/blob/497252e8d9949be20baa2cebaa6ce56de04461cf/CSharp/Library/Microsoft.Bot.Builder.Autofac/Fibers/FiberModule.cs#L63

This is a trimmed down test case:

```cs
        public interface IService
        {
        }

        public sealed class Service : IService
        {
        }

        [TestMethod]
        public void BeginLifetimeScope_Overloads()
        {
            var builder = new ContainerBuilder();

            var key = new object();

            builder
                .RegisterInstance(new Service())
                .Keyed<IService>(key)
                .SingleInstance();

            builder
                .Register(c =>
                {
                    var registrations = c.ComponentRegistry.Registrations.ToArray();
                    return Tuple.Create(registrations.Length);
                })
                .AsSelf();

            using (var container = builder.Build())
            {
                using (var scope = container.BeginLifetimeScope())
                {
                    var tuple = scope.Resolve<Tuple<int>>();
                    Assert.AreEqual(3, tuple.Item1);
                }

                using (var scope = container.BeginLifetimeScope(b =>
                {
                    // nothing in particular
                }))
                {
                    var tuple = scope.Resolve<Tuple<int>>();
                    // tuple.Item1 is incorrectly 1 instead of 3
                    Assert.AreEqual(3, tuple.Item1);
                }
            }
        }
```

**Comment by tillig** [comment] 2017-06-16 15:31
In a child lifetime scope where you don't add new registrations [you get a different component registry](https://github.com/autofac/Autofac/blob/v4.6.0/src/Autofac/Core/Lifetime/LifetimeScope.cs#L131) that is specific to the child scope and brings forward registrations from the parent as needed. When you add a configuration lambda, [you actually get a whole new registry that ensures you don't pollute the parent (a "scope restricted registry")](https://github.com/autofac/Autofac/blob/v4.6.0/src/Autofac/Core/Lifetime/LifetimeScope.cs#L189) - something you don't need if you're not configuring extra things in the lifetime scope.

Sooooooo... this is sort of "functioning as designed." Doing things where you enumerate through the registry like this isn't really something you'd normally want to do. Looking at the PR you noted, that's not really a catch-all anyway, since you're not capturing extensions like registration sources which won't be listed in the registry.

Given I'm not familiar with the Bot Framework beyond knowing of its existence, perhaps you can explain what you're trying to do so we can suggest a better way to do what you're trying to do.

**Comment by willportnoy** [comment] 2017-07-11 18:51
I need to be able to discover all services marked with a key so that I can resolve them from the container during the deserialization process.

**Comment by tillig** [comment] 2017-07-11 19:17
Can you `scope.ResolveKeyed<IEnumerable<IMyThing>>("mykey")` ?

**Comment by willportnoy** [comment] 2017-08-10 16:28
@tillig I don't have a statically or dynamically known Type to pass to ResolveKeyed.

In the short term, I worked around the issue with https://github.com/Microsoft/BotBuilder/commit/fdb443a3257dd62e2bd87727afdea793820a2ec7.

**Comment by tillig** [comment] 2017-12-13 19:45
Since it sounds like you've worked around this I'm going to close it.

The problem is, from a DI perspective, there's really not a great use case I'm aware of where you want to resolve a _thing_ and do something with that _thing_ but not have any idea _what that thing is_. It seems like keyed services or metadata may be an interesting way to... uh... "side-load?"... data in here but the challenge is that the data isn't about what should or shouldn't be _resolved_ so much as (it appears) an orthogonal issue of what should be _serialized_ somewhere.

Basically, there's not much _general_ use case out there for "resolve literally everything" or "find any old object type that has a particular metadata item associated but I don't know the type." An analogous thing might be, like, "Find every type in the system that's been marked with `[Serializable]` including stuff that might be generated through lambdas or dynamic code emitting." Autofac can handle a lot of dynamic stuff. That creates problems when you think about trying to get data about "all registrations in the container."

That said, I can think of a couple of ways to work around some of this that may help.

First, if you actually do want to enumerate _and instantiate_ the list of registrations that have a metadata item, you could register them as `object`. Like

```csharp
// If you want it to resolve as `A` make sure `AsSelf` is here because `As<object>` will
// make it ONLY resolve as object if you omit `AsSelf`
builder.RegisterType<A>().WithMetadata("serialize", true).AsSelf().As<object>();

// You can `As<IFoo>` also, if you want.
builder.RegisterType<B>().WithMetadata("serialize", true).As<IFoo>().As<object>();

// Or you can do both, whatever.
builder.RegisterType<C>().WithMetadata("serialize", false).AsSelf().As<IFoo>().As<object>();
```

When you resolve, you can resolve an `IEnumerable<Meta<Func<object>>>` (here's where I'm going by memory because I don't have VS up right now but it should work):

```csharp
foreach(var mfo in scope.Resolve<IEnumerable<Meta<Func<object>>>())
{
  // mfo is a Meta<Func<object>> - being a Func means it won't actually construct the
  // object or resolve dependencies until you call the Func, but you can get metadata.
  if(mfo.Metadata["serialize"] == true)
  {
    // We like this one, so we'll resolve it by calling the function.
    yield return mfo.Value();
  }
}
```

Another alternative would be to use the `ContainerBuilder.Properties` dictionary (a `Dictionary<string, object>`) along with a custom extension that adds a value and/or reads a value in there. That `Properties` dictionary gets persisted in the `ILifetimeScope.ComponentRegistry.Properties` property. When you spawn a new lifetime scope from that scope, all the properties will come along and inside the configuration lambda from `BeginLifetimeScope` you can append properties that will only live as long as the scope.

Something like this:

```csharp
public static IRegistrationBuilder<TLimit, TScanningActivatorData, TRegistrationStyle>
    AsSerializable<TLimit, TScanningActivatorData, TRegistrationStyle>(
        this IRegistrationBuilder<TLimit, TScanningActivatorData, TRegistrationStyle> registration)
{
    if (registration == null) throw new ArgumentNullException(nameof(registration));

    // Get the callback that will actually attach the registration to the built component
    // registry when ContainerBuilder.Build is called.
    var cb = registration.RegistrationData.DeferredCallback.Callback;

    Action<IComponentRegistry> updated = cr =>
    {
        // Make sure the registration goes through.
        cb(cr);

        // Add an entry to the component registry properties
        // so you can use it later.
        IList<Type> serializable;
        object rawValue;
        if(cr.Properties.TryGetValue("serializable", out rawValue))
        {
            list = rawValue as IList<Type>();
        }
        if(list == null)
        {
            list = new List<Type>();
        }
        list.Add(typeof(TLimit));
        cr.Properties["serializable"] = list;
    };

    return rb;
}
```

That would be used like:

```
builder.RegisterType<A>().AsSerializable().AsSelf().As<IFoo>();
```

Calling `builder.Build()` should automatically create a list of all the types marked serializable.

Then...

```
var serializableTypes = container.Properties["serializable"] as IList<Type>;
```

That is, instead of tracking the metadata literally _on each registration_ you still get to track it _while you're registering things_ but not have to deal with potentially resolving things or whatever. Arbitrary metadata about things, ready to go.

And that should propagate to child lifetime scopes. However, I will say that if you try to modify that collection using the same key ("serialize") in the dictionary, we don't have robust enough logic to know how to span two different lists across two dictionaries. We can fall back from the scope properties to the parent scope (or container) properties but you would likely want to append properties to a different entry in child scopes and enumerate both.

And, of course, something to keep in mind - this stuff all works great with _specifically registered things_ but if you implement a custom _registration source_ for more dynamic registration support or do something more complex than just registrations... even if we allowed you to enumerate the list of keyed registrations, it would _still_ not cover those more dynamic cases so it _still_ wouldn't be 100%. (Think stuff like `AnyConcreteTypeNotAlreadyRegisteredSource` that automatically allows resolution of things in the container that weren't specifically registered - full enumeration would be really expensive because it'd be literally every concrete type in the whole runtime system!)

Anyway, that's a lot but hopefully it gives you some ideas on how you can solve it. I don't think we'll be adding the ability to enumerate through all the keys or all the metadata for every registration due to the dynamic challenges above.

**Closed by tillig** 2017-12-13 19:45 UTC
