### ISSUE TITLE
Nested lifetime scopes sometimes return the incorrect service override

### ISSUE THREAD

**Issue by madelson** [autofac/Autofac#801] opened 2016-09-29 19:46 UTC
We have some code that uses nested lifetime scopes to "override" the registration for certain dependencies in certain regions of code:

```
var specialServiceInstance = ...
using (var scope = this._scope.BeginLifetimeScope(cb =>{
    cb.RegisterInstance(specialServiceInstance).As<IService>().SingleInstance();
})
{
    // ISpecialService is used downstream
    scope.Resolve<SomeOtherComponent>().DoStuff();
}
```

I'm aware that this doesn't truly "override" the registration of IService and that both registrations are still accessible, but it does change the default registration.

Recently, we changed the code such that there are multiple layers of such scopes registering different special dependencies. We found that in the innermost scope, the default dependency changes in a way that seems to be non-deterministic (although perhaps reliable given a single build). Something like:

```
var specialServiceInstance = ...
using (var scope = this._scope.BeginLifetimeScope(cb =>{
    cb.RegisterInstance(specialServiceInstance).As<IService>().SingleInstance();
})
{
    scope.Resolve<IService>(); // gives the special instance
    using (var innerScope = this._scope.BeginLifetimeScope(cb => { /* unrelated to IService */ })
    {
        innerScope.Resolve<IService>(); // gives the original instance from the container!
    }
}
```

Unfortunately, we haven't been able to isolate this to a small reproducible case. It currently happens only in our large application container and as mentioned only sometimes.

We are using Autofac 3.5.2.

---

**NOTE:** Until Oct. 25, 2016 the question mentioned in this issue involved the ordering of items resolved in a collection, not an incorrect instance being resolved individually. Comments and notes up until Oct. 25 are about the original question and not being able to rely on service ordering in a resolved collection. Future readers of the issue should take that into account and potentially skip down to comments starting Oct. 25.

**Comment by tillig** [comment] 2016-10-24 19:14
This is somewhat similar to a discussion that was had when the ASP.NET Core conforming container was brought out - it assumed that the order of _resolution_ was the same as the order of _registration_ which, in Autofac, it wasn't.

In Autofac 4 we fixed that to try to work with the conforming container spec and it seems to have resolved this issue. Here is the test I added and it passes:

```csharp
[Fact]
public void WhenRegisteredWithRegisterTypeInNestedScope()
{
    // Issue #801: Nested lifetime scopes cause the order of registrations to change.
    var cb = new ContainerBuilder();
    cb.RegisterType<Implementer1>().As<IService>();
    cb.RegisterType<Implementer2>().As<IService>();
    var c = cb.Build();

    using (var scope = c.BeginLifetimeScope(x => x.RegisterType<Implementer3>().As<IService>()))
    {
        var services = scope.Resolve<IEnumerable<IService>>().ToArray();

        Assert.IsType<Implementer1>(services[0]);
        Assert.IsType<Implementer2>(services[1]);
        Assert.IsType<Implementer3>(services[2]);
    }
}
```

So, given it's fixed in the latest, I'm going to close this issue.

That said, **it is strongly recommended that you not rely on resolution order for anything.** Even if it seems to work, it's not _guaranteed_. If you need guaranteed ordering, you need to add an `Order` property to your services and order them based on that (or based on an attribute, or whatever), similar to how ASP.NET MVC filter ordering is established.

**Comment by tillig** [comment] 2016-10-24 19:17
In fact, I rolled my test back because [we already had a test for this added in Autofac 4](https://github.com/autofac/Autofac/blob/develop/test/Autofac.Test/Features/Collections/CollectionOrderingTests.cs#L179).

**Comment by madelson** [comment] 2016-10-25 01:00
@tillig thanks for looking into this. Glad to see that the behavior of v4 matches what I was hoping to see.

Given your comment that ordering should not be relied upon, I'm curious if you have any advice for implementing the "override" pattern which we are trying to do. Is there any way to have one registration completely replace another instead of simply layering on top of it?

Thanks!

**Comment by tillig** [comment] 2016-10-25 01:32
In an override scenario you only resolve one thing, not a collection of things. The one thing you resolve will be correct based on last-in-wins (and considering `PreserveExistingDefaults`). The registration ordering only matters when you resolve a collection of things, in which case you should order predictably based on your own criteria.

**Comment by madelson** [comment] 2016-10-25 11:00
@tillig ok interesting. In that case my original question was mis-stated. The problem we were observing also showed up for resolving just one item. Not knowing that the two weren't equivalent, I mistakenly made my sample code use the sequence resolution so that it would be easier to understand. I will update the original post.

**Comment by tillig** [comment] 2016-10-25 13:15
Given we'd already gotten this far on one question/issue it would have been more optimal to open a new issue with the corrected question. From a "reading history" perspective, everything up to now no longer makes sense.

**Comment by tillig** [comment] 2016-10-25 17:11
I'm not sure what we can do about a problem that happens intermittently and only in a specific application. Things like that make me think about threading issues and race conditions. I'm not sure that's it, but that's what comes to mind. [We have a page on handling concurrency issues](http://docs.autofac.org/en/latest/advanced/concurrency.html) if it helps.

I tried testing this out in a lot of ways, like this:

```csharp
[Fact]
public void MostLocalRegistrationIsDefault()
{
    var cb = new ContainerBuilder();
    cb.RegisterType<object>();
    using (var container = cb.Build())
    {
        using (var ls1 = container.BeginLifetimeScope())
        {
            var o = new object();
            using (var ls2 = ls1.BeginLifetimeScope(b => b.RegisterInstance(o)))
            {
                using (var ls3 = ls2.BeginLifetimeScope())
                {
                    Assert.Same(o, ls3.Resolve<object>());
                }
            }
        }
    }
}
```

As you mentioned, it doesn't seem to be reproducible in a consistent fashion. We've also not had any other reports of it, which leads me to believe it's potentially application code.

Do you think you'll be able to reproduce it? If you can, we'd be happy to look into it more. If not... I'm not sure what I can do here, so I'd probably close the issue until we can get a repro or until someone else discovers the same issue.

**Comment by tillig** [comment] 2017-02-20 22:16
Since we haven't seen a consistent repro on this I'm going to close it. If we can get a repro and test against it, we can look into it further.

**Closed by tillig** 2017-02-20 22:16 UTC
