### ISSUE TITLE
Exceptions during AutoActivate/IStartable should be AutoActivationException rather than DependencyResolutionException

### ISSUE THREAD

**Issue by drauch** [autofac/Autofac#1093] opened 2020-03-16 14:28 UTC
Hi!

I've an IStartable that validates application configuration and throws an AggregateException with one or more ValidationExceptions if the application configuration is invalid. Unfortunately, Autofac catches all exceptions thrown by IStartables and rethrows them as DependencyResolutionExceptions, even though dependency resolution worked just fine. This is very misleading for me and for guys in operations.

Is there any way around this? Am I doing something wrong?

I'm using Autofac 4.9.4

**Comment by tillig** [comment] 2020-03-16 14:54
At this time there is no workaround. [The code specifically does this](https://github.com/autofac/Autofac/blob/2c63e85413249c014bd8dd0c35a7befcccadaf92/src/Autofac/Builder/StartableManager.cs#L51) so folks don't have to catch every possible exception type that any startable component might throw.

In the future it might be good to switch this to something more specific, like `AutoActivationException` or something similar, but likely we wouldn't want to just let the thrown exception bubble up because, again, this would make error handling code really complex.

Switching the exception type would be considered a breaking change because people with existing error handling are assuming this exception type will be thrown. Changing it on them will break their logic, so we'd have to keep this for a major release.

Would a different exception type be better for you or is the problem really that the root cause is getting wrapped in something you're not expecting?

**Comment by drauch** [comment] 2020-03-16 16:21
The main issue for me is that the exception tells me that "dependency resolution" failed, when in turn, everything resolved just fine, just executing some of the resolved components failed.

In an optimal world I could also tell the container.Build() call to not wrap exceptions thrown by auto-activated components (this could even be a non-breaking change if you just add a new enum value to ContainerBuildOptions). Most of the time, at least in our code bases, if building the container fails the whole application fails to start and some ops team member checks the logs for the reason. If it is a "ValidationException Configuration settings XYZ is required" he/she knows what to do, if it is a DependencyResolutionException he/she contacts the DEV team because obviously we didn't register all the necessary components at the container properly.

Best regards,
D.R.

**Comment by tillig** [comment] 2020-03-16 16:35
It sounds like if this was switched to an `AutoActivationException` it would at least disambiguate what happened, and I think that's fine. I feel pretty strongly that having it wrapped in _something_ is important to error handling efficiency, and there's a lot of precedent around that sort of behavior in the .NET world, so I don't think we'll be adding any new options specifically to allow for not wrapping the exceptions. I think it's OK that what we have is slightly opinionated in this regard.

However, it sounds like there is potentially a larger/different issue to solve on your end with your operations process and how the exceptions during container build are dealt with, and I think that'd be easy enough to handle in your application code:

```c#
IContainer container;
try
{
  container = containerBuilder.Build();
}
catch(DependencyResolutionException ex)
{
  if(ex.InnerException == null)
  {
    throw;
  }
  else
  {
    throw ex.InnerException;
  }
}
```

Simply unwrap the inner exception if there is one and rethrow. If there's not, just allow the existing exception to continue bubbling up.

You may have to experiment with that but it should get you the native exception for your ops team.

Also, it sounds like if this is something that pops up a lot, performing some better logging or error handling in your auto-activating components might improve your operations handling of things.

I'll update this issue to note that it's for an AutoActivationException; however, I would encourage you to also look at your app code and see if there's some improved error handling you can do from your end that will ease your immediate ops pain.

**Comment by tillig** [comment] 2020-03-16 16:39
Design notes re: `AutoActivationException`:

- This will be a breaking change because the exception type is changing. Save it for 6.0 or another major release.
- If there is a problem _resolving_ the component being auto-activated, continue throwing the `DependencyResolutionException`.
- If there is a problem _executing the `IStartable.Start` function on a startable component, use the `AutoActivationException`.

We might consider that resolving something for auto activation may, too, be an `AutoActivationException` since `.AutoActivate()` only does a resolve op and doesn't call any method after resolve. That would make it so building a container doesn't just yield an resolution-related exception and may be more semantically interesting.

**Comment by alistairjevans** [comment] 2020-03-16 16:48
If we were to create ``AutoActivationException`` derived from ``DependencyResolutionException``, it may make the change non-breaking? That way existing consumers continue to get the generic one, but people specifically interested in activation problems see the new one. Would that be too semantically confusing perhaps?

**Comment by tillig** [comment] 2020-03-16 16:55
I think if the argument is that "this isn't a dependency resolution issue, it's an issue during auto activation" (e.g., something that happens during `IStartable.Start` rather than something actually happening during the resolution process then having it derive from `DependencyResolutionException` doesn't make sense.

However, I could see a couple of options here.

- **All types of exceptions that happen as a part of auto activation become `AutoActivateException`. ** In this case, whether it's the resolve part _or_ the `Start()` call, it'd be this new exception type. I could go either way on whether it's derived from `DependencyResolutionException` in this case since it _may actually be_ from dependency resolution.
- **Only exceptions caused by calling `Start()` or some post-resolution action become `AutoActivateException`.** In this case, it would very explicitly _not_ be from resolution issues, so it wouldn't make sense to have it derive from DRE.

I don't have technical argumentation to back it up, but it _feels_ like having anything from auto activation become `AutoActivationException` would be right; and that if you want to know whether it was dependency resolution or something else you would look at the `InnerException`... in which case, `AutoActivationException` doesn't _feel_ like it'd be derived from DRE.

I could be swayed. I don't feel super strongly one way or the other. Only thing I feel pretty strongly about is not wanting to maintain a separate container build option to allow folks to configure this. We should pick a way and go with it.

**Comment by drauch** [comment] 2020-03-16 18:12
OK, I'm going to unsubscribe from the issue. I hope you don't feel it's rude of me, but the "solution" seems to be to look at the InnerException and that this responsibility is forced upon the users. Whether you introduce a DependencyResolutionException or AutoActivateException doesn't really matter to me anymore, because I need to employ a workaround anyways.

Thank you though for your quick replies - I'm impressed by the way you manage this open source dependency injection framework (and that although you want to find someone else maintaining it for quite some time already). So thank you again!

Best regards,
D.R.

**Comment by drauch** [comment] 2020-03-16 18:14
Actually, when I think of it, if I have to look at the inner exception, I'd rather have no breaking change at all, so I don't have to update my workaround. So if you just put in the effort for my scenario, don't waste your time. If you do it because it feels cleaner (which I can understand very well) then of course go ahead (but please put it in the changelog, so I know when to switch my workaround code to a different exception type :-))

**Closed** 2023-11-06 17:33 UTC
Labels: enhancement
