### ISSUE TITLE
AsImplementedInterfaces not Binding all Interfaces

### ISSUE THREAD

**Issue by squadwuschel** [autofac/Autofac#1277] opened 2021-05-26 20:09 UTC
## Describe the Bug

I am using autofac  6.2.0 in a .NET Core 3.1 web api Project.
I am using the AsImplementedInterfaces implementation to autobind all my Interfaces to my Classes.

The Problem is, that only the (2) ITodoItemManager binding ist working with the AsImplementedInterfaces but the (1) ITodoModelBuilder is not getting bindet and I get a error.

![grafik](https://user-images.githubusercontent.com/1572878/119722977-397ae480-be6d-11eb-967c-a61f6f20e7c6.png)
  
    InvalidOperationException: Unable to resolve service for type 'Squad.Gui.Web.Models.Todo.Interfaces.ITodoModelBuilder' while attempting to activate 'Squad.Gui.Web.Controllers.HomeController'.

I've debugged it so far, that i can tell that all Assemblies are loaded where the interfaces and classes are included what I am trying to autobind.

![grafik](https://user-images.githubusercontent.com/1572878/119724363-ea35b380-be6e-11eb-9e70-4736280c7899.png)

Code for autobinding
```c#
    var applicationAssemblies = LoadApplicationAssemblies("squad.");
    builder.RegisterAssemblyTypes(applicationAssemblies.ToArray()).AsImplementedInterfaces();
```

when I manualy register the ITodoModeBuilder its working 

```c#
  builder.RegisterType<TodoModelBuilder>().As<ITodoModelBuilder>()
```

## Steps to Reproduce

I'Ve added my small demo Solution with the Problem to repoduce the issue.

[WebTemplate.zip](https://github.com/autofac/Autofac/files/6549246/WebTemplate.zip)

Just set the webproject as start project and you should see the following error

![grafik](https://user-images.githubusercontent.com/1572878/119723601-eb1a1580-be6d-11eb-9911-95d050518a15.png)

## Expected Behavior

All Interfaces should be autobinded with AsImplementedInterfaces when all assemblies are added right.

## Exception with Stack Trace

```text
InvalidOperationException: Unable to resolve service for type 'Squad.Gui.Web.Models.Todo.Interfaces.ITodoModelBuilder' while attempting to activate 'Squad.Gui.Web.Controllers.HomeController'.
Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, bool isDefaultParameterRequired)
lambda_method(Closure , IServiceProvider , object[] )
Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider+<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider+<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

## Dependency Versions

Autofac:

**Comment by tillig** [comment] 2021-05-26 20:54
Running in a debug context or manually executing a registration causes the assembly binder to load some things that may not already be loaded. [We silently ignore types we can't load.](https://github.com/autofac/Autofac/blob/f52dc4d877aaa7428b93ccf799a0e4a265a88c85/src/Autofac/Features/Scanning/ScanningRegistrationExtensions.cs#L80)

Do something like this and see what you get:

```c#
using System.Diagnostics;
using System.Linq;
using Autofac.Util;

var applicationAssemblies = LoadApplicationAssemblies("squad.");
var loadable = applicationAssemblies.SelectMany(a => a.GetLoadableTypes()).ToArray();
Debug.WriteLine("LOADABLE TYPES:");
foreach (var t in loadable)
{
  Debug.WriteLine($"- {t.FullName}");
}
```

(Not writing this with a compiler, just trying to get help out fast. Point being, list the actual set of loadable types.)

Look in the list and see if both the type you want registered _and_ the interface are in the list. My guess is that one or both are not, and that the debugger (or the compiler, when you manually register) is what's doing the loading transparently.

**Comment by squadwuschel** [comment] 2021-05-27 18:03
I've added this code snipped and the Type I want to bind is listed

LOADABLE TYPES:
- <>f__AnonymousType0`1
- <>f__AnonymousType1`1
- Squad.Gui.Web.Program
- Squad.Gui.Web.Startup
- Squad.Gui.Web.WebSkeleton.OperationResult`1
- Squad.Gui.Web.WebSkeleton.ResultType
- Squad.Gui.Web.Models.ErrorViewModel
- Squad.Gui.Web.Models.IndexViewModel
- Squad.Gui.Web.Models.Todo.TodoItem
**- Squad.Gui.Web.Models.Todo.TodoModelBuilder
- Squad.Gui.Web.Models.Todo.Interfaces.ITodoModelBuilder**
- Squad.Gui.Web.Controllers.HomeController
- Squad.Gui.Web.Controllers.TodoController
- Squad.Gui.Web.Program+<>c
- Squad.Gui.Web.Startup+<>c
- Squad.Gui.Web.Models.Todo.TodoModelBuilder+<>c
...... some .net Core Assemblies ....
- Squad.Logic.Implementation.TodoItemsManager
- Squad.Logic.Implementation.TodoItemsManager+<GetAllTodoItems>d__1
- Squad.Logic.Interfaces.ITodoItemsManager
- Squad.Models.DomainModel.TodoItemModel


the two bold ones I want to bind are not binded.

**Comment by tillig** [comment] 2021-05-27 18:15
I should have read the exception closer. See this part in the stack?

`Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider...`

That means it's not going through Autofac at all to resolve stuff. Unless there's some inner exception with Autofac info that you've omitted, it's looking like the problem isn't that Autofac can't resolve the type; it's that you're not even going through Autofac to get there.

**Comment by squadwuschel** [comment] 2021-05-27 18:37
How can this happen? When I add it manually it works and when I don't add it its not using autofac for this interface to bind. 
I am not shure what I've done wrong, because there is not much I've configured so far for Autofac its only one line code witrh the "AsImplementedInterfaces"

**Comment by alistairjevans** [comment] 2021-05-27 18:51
Can you provide your Program.cs/Startup.cs configuration? Or an example repo with a very minimal reproduction?

Just to check that you aren't somehow 'building' your container with Autofac, but then not using Autofac for the actual resolve operation.

**Comment by squadwuschel** [comment] 2021-05-27 18:59
I've added the zipfile with my small demo project in the initial post, is that enough?

**Comment by tillig** [comment] 2021-05-27 23:14
Aside: The zip file might be easier to work with if it was more of a minimal repro thing. It's got the whole git repo, all the `.vs` folder with user-specific files, build output, UI assets, the whole shebang. Trying to figure this stuff out really is about "remove all the stuff until all that's left is the bit that shows the issue." That's why we look for a unit test we can run or a repo with a super minimal repro in it rather than a zip file.

**Comment by tillig** [comment] 2021-05-27 23:34
The project as provided in the zip file doesn't build. On build I see:

```
...\20_Gui\WebTemplate\Controllers\HomeController.cs(12,17): error CS0246: The type or namespace name 'ITodoModelBuilder' could not be found (are you missing a using directive or an assembly reference?) [...\20_Gui\WebTemplate\Gui.Web.csproj]
```

Looking at `HomeController` I see that there's a `Squad.Logic.Interfaces` namespace included but the `ITodoModelBuilder` isn't found.

![ITodoModelBuilder not found](https://user-images.githubusercontent.com/1156571/119908695-0df90800-bf08-11eb-92ab-3101d07bb88b.png)

The `TodoController` shows the same error.

`ITodoModelBuilder` looks to be in the `Squad.Gui.Web.Models.Todo.Interfaces` namespace, which is _not_ included by the controller.

![The ITodoModelBuilder interface](https://user-images.githubusercontent.com/1156571/119908831-5a444800-bf08-11eb-8754-c6e6e99f5fe8.png)

I further see that the `TodoModelBuilder` has a problem because the interface it's supposed to implement is not there. Again, it appears the wrong namespace is included here.

![TodoModelBuilder class](https://user-images.githubusercontent.com/1156571/119908953-9d062000-bf08-11eb-8ca0-300b40a7f714.png)

I'm not going to spend any more time debugging this. My current guess is that there are stale versions of libraries being used and/or cached and the problem is that while the controller is looking for `ITodoModelBuilder` from one namespace, the implementation is against a different namespace.

I'm not sure if other contributors have additional time to spend here, but I won't personally be able to come back until this is:

- Trimmed down to only a minimal repro - stick it in a repo rather than a zip file, remove _everything_ that doesn't have to do with the issue - all `.vs` stuff, all extra controllers, views that have nothing to do with the repro, everything. Super minimal repro that gets right to the heart of it. _Why? Because a lot of the time it turns out as the minimal repro is being created there's an 'aha!' moment where the issue becomes clear; and because it reduces the amount of stuff we have to poke through._
- Code that compiles - I kinda feel like that's a minimum for a repro.

I legitimately do apologize for having to kick it back to you like this. I do want to help, but while we'll do our best to troubleshoot stuff that has to do with Autofac, we're not a free consulting and debugging service. You'll have to do some work, too, if you need help.

**Comment by squadwuschel** [comment] 2021-05-28 05:46
thanks for your time, I will do my best to break this down into minimal repo i could host on github to reproduce the issue. 
It was my fault that I don't think so far that I've just zipped my "small" demo solution which was working on my lokal Environment sorry for that. I will be back when I got a small reproducable demo.

**Comment by squadwuschel** [comment] 2021-05-29 08:40
I've created the smales example possible and got the same problem I've also checked the Loadable Types example from above and there are all types included.

Here is the link to the git Repo

https://github.com/squadwuschel/autofacTest.git

its an .NET Core 3.1 WebApi project. Just hitting F5 in VS 2019 should compile it and starting browser and showing the error like above.

**Comment by tillig** [comment] 2021-05-29 18:35
The problem is that the types you're registering aren't the same as the types the controller is referring to.

This seems counter-intuitive, but it has to do with .NET [assembly load context](https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext). In a nutshell, there are some assemblies _already loaded_ into the application by the .NET assembly loader. Later, your code is trying to load _the same assemblies_ but using `Assembly.LoadFile`. This results in a duplicate _but different_ set of assemblies being loaded, such that the application has two copies of the same assembly loaded but in different contexts.

Here's some code you can put in `ConfigureContainer` in your app that shows the differences.

```c#
// There are some assemblies already loaded.
var appDomainAssemblies = AppDomain.CurrentDomain.GetAssemblies().Where(a => a.FullName.Contains("squad", StringComparison.OrdinalIgnoreCase));
Debug.WriteLine("ASSEMBLIES ALREADY LOADED:");
foreach (var a in appDomainAssemblies)
{
    Debug.WriteLine($"- {a.FullName}");
}

// Grab the assembly already loaded in the AppDomain.
var alreadyLoadedAssembly = appDomainAssemblies.First(a => a.GetName().Name.Equals("Squad.AutofacTest", StringComparison.OrdinalIgnoreCase));
Debug.WriteLine($"ALREADY LOADED: {alreadyLoadedAssembly.FullName} | {alreadyLoadedAssembly.CodeBase}");

// Some assemblies get loaded manually.
var applicationAssemblies = LoadApplicationAssemblies("squad.");
Debug.WriteLine("ASSEMBLIES LOADED BY LoadApplicationAssemblies:");
foreach (var a in applicationAssemblies)
{
    Debug.WriteLine($"- {a.FullName}");
}

// Grab the assembly just now loaded in a different context using Assembly.LoadFile.
var justLoadedAssembly = applicationAssemblies.First(a => a.GetName().Name.Equals("Squad.AutofacTest", StringComparison.OrdinalIgnoreCase));
Debug.WriteLine($"JUST LOADED: {justLoadedAssembly.FullName} | {justLoadedAssembly.CodeBase}");

// These two assemblies are NOT EQUAL.
Debug.WriteLine($"LOADED EQUAL? {alreadyLoadedAssembly == justLoadedAssembly}");

// Let's compare types.
var alreadyLoadedType = alreadyLoadedAssembly.GetTypes().First(t => t.Name.Equals("ITodoModelBuilder", StringComparison.OrdinalIgnoreCase));
var justLoadedType = justLoadedAssembly.GetTypes().First(t => t.Name.Equals("ITodoModelBuilder", StringComparison.OrdinalIgnoreCase));
Debug.WriteLine($"ALREADY LOADED: {alreadyLoadedType.FullName}");
Debug.WriteLine($"JUST LOADED: {justLoadedType.FullName}");
Debug.WriteLine($"ARE THOSE THE SAME TYPE? {alreadyLoadedType == justLoadedType}");
```

The output of this looks like:

```text
ASSEMBLIES ALREADY LOADED:
- Squad.AutofacTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
ALREADY LOADED: Squad.AutofacTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null | file:///C:/dev/autofacTest/AutofacTest/bin/Debug/netcoreapp3.1/Squad.AutofacTest.dll
ASSEMBLIES LOADED BY LoadApplicationAssemblies:
- Squad.AutofacTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
JUST LOADED: Squad.AutofacTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null | file:///C:/dev/autofacTest/AutofacTest/bin/Debug/netcoreapp3.1/Squad.AutofacTest.dll
LOADED EQUAL? False
ALREADY LOADED: Squad.AutofacTest.Models.Interfaces.ITodoModelBuilder
JUST LOADED: Squad.AutofacTest.Models.Interfaces.ITodoModelBuilder
ARE THOSE THE SAME TYPE? False
```

This is why the manual registration works - when you have the manual registration...

```c#
builder.RegisterType<TodoModelBuilder>().As<ITodoModelBuilder>();
```

...the compiler is binding this to the _same type_ as the one in the constructor for the controller - they're all in the same assembly.

When you do the assembly loading and registering, the registration is literally a _different type_, at least according to the runtime type loader. It's a "ghost" sort of, where it has the same _name_ but it's not _literally the same bytes loaded into memory_ so it's not _the same type_.

You can further prove this is the case by changing the assembly scanning registration to look like this:

```c#
var applicationAssemblies = AppDomain.CurrentDomain.GetAssemblies().Where(a => a.FullName.Contains("squad", StringComparison.OrdinalIgnoreCase));
builder.RegisterAssemblyTypes(applicationAssemblies.ToArray()).AsImplementedInterfaces();
```

That is, if you use the stuff that's already loaded instead of using the `Assembly.LoadFile` assemblies, everything actually works.

**Assembly loading problems are hard.** They're even harder in .NET Core where dependencies don't actually always come from the folder where the application is compiled/running. [We have an issue about trying to write some docs to help a little with this](https://github.com/autofac/Documentation/issues/101) but assembly loading isn't an Autofac concern; it's .NET and the app developer.

I would recommend:
- If you're _not_ writing plugins, just use the assemblies loaded in the current domain. If you're using IIS, [look into using the `BuildManager` to get these](https://autofac.readthedocs.io/en/latest/faq/iis-restart.html) to make sure you don't have any surprises.
- If you _are_ writing plugins, you'll need to start diving into proper handling of assembly loading in .NET Core. I'd guess that you'll also have to get into how to load those assemblies' dependencies because, again, it's not necessarily the easiest thing in the world.

However, at least for this issue, Autofac is functioning as designed so I'm going to close it.

**Closed by tillig** 2021-05-29 18:35 UTC

**Comment by squadwuschel** [comment] 2021-05-31 12:17
Thx for your detailed explanation. I got it working. It's not straight forward but it works. The problem was, that I don't only have the webprojekt I got some more project DLLs with managers to autobind.

and the code for 

    var applicationAssemblies = AppDomain.CurrentDomain.GetAssemblies().Where(a => a.FullName.Contains("squad", StringComparison.OrdinalIgnoreCase));

![grafik](https://user-images.githubusercontent.com/1572878/120191226-f9738300-c219-11eb-9a1d-519e44913d5b.png)

only loads the web assembly and not my other project assemblies. 
And the compiled web project creates the following DLLs
![grafik](https://user-images.githubusercontent.com/1572878/120190436-e0b69d80-c218-11eb-8f07-2598c28d65ed.png)

 - squad.gui.web.dll
 - squuad.gui.web.views.dll

and this seems not to be the same "assembly" as the "AppDomain.CurrentDomain.GetAssemblies()..." loads, because with this load I only got one assembly loaded and this is the right Assembly for the autobinding.

So to get my WebProject Assembly and all my other Project dependend assemblies I am using this function

        private List<Assembly> LoadApplicationAssemblies(string partOfassemblyNamespace)
        {
            var ass = System.IO.Path.GetDirectoryName(Assembly.GetEntryAssembly().Location);
            var assemblyList = new List<Assembly>();

            foreach (var file in Directory.GetFiles(ass, "*.dll"))
            {
                try
                {
                    //exclude also the gui.web, because we load them below
                    if (file.ToLower().Contains(partOfassemblyNamespace.ToLower()) && !file.ToLower().Contains("gui.web"))
                    {
                        assemblyList.Add(Assembly.LoadFile(file));
                    }
                }
                catch (Exception)
                {
                    // ignored
                }
            }

            var applicationAssemblies = AppDomain.CurrentDomain.GetAssemblies().Where(a => a.FullName.Contains("squad", StringComparison.OrdinalIgnoreCase));

            foreach (var applicationAssembly in applicationAssemblies)
            {
                if (assemblyList.All(x => x.FullName != applicationAssembly.FullName))
                {
                    assemblyList.Add(applicationAssembly);

                }
            }

            return assemblyList;
        }

like you mentioned it has nothing todo with autofac it seems to be a problem with the assembly loading.

**Comment by alsami** [comment] 2021-05-31 13:36
In general as a recommendation, don't use `AppDomain.CurrentDomain.GetAssemblies`.

Instead maintain a list of assemblies you want to load types from, something like this:

```csharp
var types = new Assembly[] { typeof(MyClass).Assembly, typeof(MyOtherClass).Assembly };
```

This requires you to maintain the list, yes, but it also makes sure that you only load what you want. Sometimes explicitness works just better than implicitness.
