### ISSUE TITLE
Instance per Owned not working with keyed Owned Instances

### ISSUE THREAD

**Issue by Firedragonweb** [autofac/Autofac#1094] opened 2020-03-16 20:21 UTC
When registering and resolving an owned instance with Keyed, InstancePerOwned services cannot be resolved without specifying the key. This should be possible in order to allow setting the correct lifetime for dependend services, regardless of the particular flavor that was used to resolve the registration.

Repo with the Issue in UnitTest form:
https://github.com/Firedragonweb/InstancePerOwnedIssue

Exception raised:

> Autofac.Core.DependencyResolutionException : An exception was thrown while activating λ:Autofac.Features.OwnedInstances.Owned`1[[InstancePerOwnedIssues.IRoot, InstancePerOwnedIssues, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] -> InstancePerOwnedIssues.RootA.
> Data:
>   ActivatorChain: λ:Autofac.Features.OwnedInstances.Owned`1[[InstancePerOwnedIssues.IRoot, InstancePerOwnedIssues, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] -> InstancePerOwnedIssues.RootA
> 
>   ----> Autofac.Core.DependencyResolutionException : Unable to resolve the type 'InstancePerOwnedIssues.Service' because the lifetime scope it belongs in can't be located. The following services are exposed by this registration:
> InstancePerOwnedIssues.Service
> 
> Details
>   ----> Autofac.Core.DependencyResolutionException : No scope with a tag matching 'InstancePerOwnedIssues.IRoot' is visible from the scope in which the instance was requested.
> 
> If you see this during execution of a web application, it generally indicates that a component registered as per-HTTP request is being requested by a SingleInstance() component (or a similar scenario). Under the web integration always request dependencies from the dependency resolver or the request lifetime scope, never from the container itself.
>    at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
>    at Autofac.Core.Resolving.InstanceLookup.Execute()
>    at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
>    at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
>    at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
>    at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
>    at Autofac.Core.Container.ResolveComponent(ResolveRequest request)
>    at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
>    at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
>    at Autofac.ResolutionExtensions.ResolveKeyed[TService](IComponentContext context, Object serviceKey, IEnumerable`1 parameters)
>    at Autofac.ResolutionExtensions.ResolveKeyed[TService](IComponentContext context, Object serviceKey)
>    at InstancePerOwnedIssues.Tests.InstancePerOwnedTest() in D:\Repos\InstancePerOwnedIssue\InstancePerOwnedIssues\InstancePerOwnedIssues\UnitTest1.cs:line 41
> --DependencyResolutionException
>    at Autofac.Core.Resolving.InstanceLookup..ctor(IResolveOperation context, ISharingLifetimeScope mostNestedVisibleScope, ResolveRequest request)
>    at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
>    at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(ResolveRequest request)
>    at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass0_0.<CanSupplyValue>b__0()
>    at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
>    at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
>    at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
> --DependencyResolutionException
>    at Autofac.Core.Lifetime.MatchingScopeLifetime.FindScope(ISharingLifetimeScope mostNestedVisibleScope)
>    at Autofac.Core.Resolving.InstanceLookup..ctor(IResolveOperation context, ISharingLifetimeScope mostNestedVisibleScope, ResolveRequest request)

**Comment by tillig** [comment] 2020-03-16 20:28
The code, for easier reading:

```c#
using Autofac;
using Autofac.Features.OwnedInstances;
using NUnit.Framework;

namespace InstancePerOwnedIssues
{
    public class Tests
    {
        [Test]
        public void SingleInstanceTest()
        {
            ContainerBuilder builder = new ContainerBuilder();
            builder.RegisterType<Service>().AsSelf().SingleInstance();
            builder.RegisterType<RootA>().Keyed<IRoot>("A");
            builder.RegisterType<RootB>().Keyed<IRoot>("B");
            IContainer container = builder.Build();
            Owned<IRoot> ownedRoot = container.ResolveKeyed<Owned<IRoot>>("A");
            Service service = container.Resolve<Service>();
            Assert.That(ReferenceEquals(ownedRoot.Value.Dependency, service), Is.True);
        }

        [Test]
        public void InstancePerLifetimeTest()
        {
            ContainerBuilder builder = new ContainerBuilder();
            builder.RegisterType<Service>().AsSelf().InstancePerLifetimeScope();
            builder.RegisterType<RootA>().Keyed<IRoot>("A");
            builder.RegisterType<RootB>().Keyed<IRoot>("B");
            IContainer container = builder.Build();
            Owned<IRoot> ownedRoot = container.ResolveKeyed<Owned<IRoot>>("A");
            Service service = container.Resolve<Service>();
            Assert.That(ReferenceEquals(ownedRoot.Value.Dependency, service), Is.False);
        }

        [Test]
        public void InstancePerOwnedTest()
        {
            ContainerBuilder builder = new ContainerBuilder();
            builder.RegisterType<Service>().AsSelf().InstancePerOwned<IRoot>();
            builder.RegisterType<RootA>().Keyed<IRoot>("A");
            builder.RegisterType<RootB>().Keyed<IRoot>("B");
            IContainer container = builder.Build();
            Owned<IRoot> ownedRoot = container.ResolveKeyed<Owned<IRoot>>("A");
            Assert.That(ownedRoot.Value.Dependency, Is.Not.Null);
        }
    }

    public class Service
    {
    }

    public interface IRoot
    {
        Service Dependency { get; }
    }

    public class RootA : IRoot
    {
        public RootA(Service dependency)
        {
            Dependency = dependency;
        }

        public Service Dependency { get; }
    }

    public class RootB : IRoot
    {
        public RootB(Service dependency)
        {
            Dependency = dependency;
        }

        public Service Dependency { get; }
    }
}
```

**Comment by alistairjevans** [comment] 2020-03-16 22:22
From an initial look, something does seem a bit odd here, perhaps related to the ``KeyedService`` used as the ``Owned`` lifetime scope . I'll try and take a look when I have a bit of time.

**Comment by alexmg** [comment] 2020-03-22 21:45
The issue here is that the `InstancePerOwned<IRoot>` is not registered with a key so the tag applied to the `MatchingScopeLifetime` is a `TypedService` for `IRoot`. A `KeyedService` is resolved for `IRoot` when resolving the `Owned<IRoot>(key)` and this does not match the `TypedService` applied when configuring the `InstancePerOwned<IRoot>`.

There is an overload of `InstancePerOwned` that takes a key and would work in the unit tests above where `"A"` is being resolved.

```
builder.RegisterType<Service>().InstancePerOwned<IRoot>("A");
```

Unfortunately, it only allows a single key to be provided and attempting to chain a second call to the `InstancePerOwned` method will result in the `MatchingScopeLifetime` configured in the first call being replaced.

```
builder.RegisterType<Service>().AsSelf().InstancePerOwned<IRoot>("A").InstancePerOwned<IRoot>("B");
```

The same problem will occur even when the registrations are made as two separate statements.

```
builder.RegisterType<ServiceForHandler>().InstancePerOwned<IRoot>("A");
builder.RegisterType<ServiceForHandler>().InstancePerOwned<IRoot>("B");
```

The unit test would fail with the above because the `"A"` keyed service was replaced with the `"B"` keyed service.

We could add another overload of `InstancePerOwned` that takes multiple keys. You would need to provide all possible key values that `IRoot` could be resolved with.

```
builder.RegisterType<Service>().InstancePerOwned<IRoot>("A", "B");
```

It would also be possible to create an internal type that wraps the `IServiceWithType` created by `InstancePerOwned` and use that as the tag in the `MatchingScopeLifetime`. It could have an equality implementation that attempts to compare as `KeyedService` first, `IServiceWithType` second, and `object` last for user defined tags. The issue is the potential ambiguity of a being able to provide a key to `InstancePerOwned` but then allowing a regular service to become the catch all when a key is not provided.

With the first change in place the registration below would work for keyed services of `"A"` and `"B"` but nothing else.

```
builder.RegisterType<Service>().InstancePerOwned<IRoot>("A", "B");
```

With the second change in place the registration below would work for any keyed or regular service.

```
builder.RegisterType<Service>().AsSelf().InstancePerOwned<IRoot>();
```

**Comment by Firedragonweb** [comment] 2020-03-23 06:43
I would see applications for both solutions, actually.
If you only want to register your component for specific flavors of IRoot, but more than one, you would need the first approach.

However, if you don't care about the flavor of IRoot and only have the first solution, you would need to change every registration of that kind, if you add a new flavor of IRoot, which has a very high potential for bugs in the software, if you forget one.

**Closed** 2020-04-19 04:57 UTC

**Comment by alexmg** [comment] 2020-04-19 05:04
An `InstancePerOwned` without a key can now be used for `Owned<T>` instances that are resolved with a key. I also added an overload of `InstancePerOwned` that accepts multiple keys. I did this for consistency with the existing single key based overload. The alternative was to remove the  single key based overload which does not offer much value as you can only have a single lifetime configured for a service. I opted to avoid the breaking change but could still be convinced otherwise.
