### ISSUE TITLE
When throwing a DependencyResolutionException, the type that can't be resolved should be included

### ISSUE THREAD

**Issue by opiants** [autofac/Autofac#679] opened 2015-09-10 02:18 UTC
`DependencyResolutionException: No scope with a Tag matching 'AutofacWebRequest' is visible from the scope in which the instance was requested. This generally indicates that a component registered as per-HTTP request is being requested by a SingleInstance() component (or a similar scenario.) Under the web integration always request dependencies from the DependencyResolver.Current or ILifetimeScopeProvider.RequestLifetime, never from the container itself.
Autofac.Core.Lifetime.MatchingScopeLifetime.FindScope(ISharingLifetimeScope mostNestedVisibleScope)`

In the above exception, it doesn't tell me what the offending type is. This means that in order to fix it, I would have to trial and error my component registrations.

These are the the final calls in the stack trace:

`Autofac.Core.Lifetime.MatchingScopeLifetime.FindScope(ISharingLifetimeScope mostNestedVisibleScope)
Autofac.Core.Resolving.InstanceLookup..ctor(IComponentRegistration registration, IResolveOperation context, ISharingLifetimeScope mostNestedVisibleScope, IEnumerable``1 parameters)
Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable``1 parameters)
Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable``1 parameters)
Autofac.Features.Collections.CollectionRegistrationSource.<>c__DisplayClass0_1.<RegistrationsFor>b__1(IComponentRegistration cr)
`

This is for Autofac.Dnx v4.0.0-alpha4 but I believe it's the same case for other versions as well.

**Comment by tillig** [comment] 2015-10-15 00:21
This appears to be a duplicate of #621.

**Closed by tillig** 2015-10-15 00:21 UTC
Labels: enhancement
