### ISSUE TITLE
Cannot resolve a generic type when generic constraint in interface is `class` keyword but in concrete type is an actual class

### ISSUE THREAD

**Issue by gordon-matt** [autofac/Autofac#1303] opened 2021-12-13 06:45 UTC
## Describe the Bug

A type was not able to be resolved due to a generic constraint on the concrete type being an actual class while the interface's generic constraint was simply the keyword `class`.

## Steps to Reproduce

Create an interface, with `class` for the generic constraint. Example:

```
public interface IRepository<T, TKey>
    where T : class
```
and a concrete class deriving from it, with the generic constraint being an actual class and not just the keyword `class`:

```
public class Repository<T, TKey> : IRepository<T, TKey>
    where T : BaseEntity<TKey>
```

Register it:
```
builder.RegisterGeneric(typeof(Repository<,>)).As(typeof(IRepository<,>)).InstancePerDependency();
```

## Expected Behavior

Since the generic constraint on the concrete class is actually a class, it should not be an issue and Autofac should be able to resolve it.

## Exception with Stack Trace

```text
Autofac.Core.Registration.ComponentNotRegisteredException: The requested service 'MyApp.Data.IRepository`2[[MyApp.Data.Entities.UserCredential, MyApp.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Guid, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.

Stack Trace: 
ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
ResolutionExtensions.Resolve[TService](IComponentContext context)
HotelDetailControllerTests.DetailTest() line 32
ThreadOperations.ExecuteWithAbortSafety(Action action)
```

## Dependency Versions

Autofac: 6.3.0

**Comment by tillig** [comment] 2021-12-13 15:05
I think the problem here is similar to one of [covariance vs. contravariance](https://docs.microsoft.com/en-us/dotnet/standard/generics/covariance-and-contravariance).

The interface says "I support any `T` when `T` is any kind of class; and any `TKey` at all." Cool, so for _any backing type_, I should be able to resolve `IRepository<Exception, string>`, right? Because `Exception` is a class.

Except the backing type here doesn't actually fulfill the contract of the full `IRepository<T, TKey>` interface. It only allows `T` when `T` is a specific type. There's a way to cast DOWN from `BaseEntity<TKey>` to a `class`, but for the interface itself, from a contract perspective, you can't cast from any old `class` UP to `BaseEntity<TKey>`.

That's my first guess. These things can be hard to figure out without really debugging deep and I still get messed up with covariance/contravariance issues. I get it backwards all the time.

**If you switch your `Repository<T, TKey>` to either have no constraint or use just `class`, does it resolve?** Finding that out would help us narrow down what's going on.

I know we have [a lot of open generics tests, including some with constraints](https://github.com/autofac/Autofac/blob/f52dc4d877aaa7428b93ccf799a0e4a265a88c85/test/Autofac.Test/Features/OpenGenerics/ComplexGenericsTests.cs) to verify things like this, including [one that has some nested constraints just like this](https://github.com/autofac/Autofac/blob/f52dc4d877aaa7428b93ccf799a0e4a265a88c85/test/Autofac.Test/Features/OpenGenerics/ComplexGenericsTests.cs#L99) but to make some of them work [you have to use modifiers like `in` for contravariance] and [`out` for covariance](https://github.com/autofac/Autofac/blob/f52dc4d877aaa7428b93ccf799a0e4a265a88c85/test/Autofac.Test/Features/OpenGenerics/ComplexGenericsTests.cs#L81).

**If you make the repository interface `IRepository<in T, TKey>` does that fix it?** Or... `out`? Man, I get these confused.

Just trying to narrow down what might be happening. I don't have a ton of time to super dig into complex stuff like this so the more you can do up front the faster you might get a resolution.

**Comment by gordon-matt** [comment] 2021-12-13 19:59
Thanks for your time.

>If you switch your Repository<T, TKey> to either have no constraint or use just class, does it resolve?>

Yes, that works. However, it's more of a pain, because I then do not have access to the `Id` property from `BaseEntity<TKey>`. As a workaround for now, I guess I can use a constraint of `IBaseEntity<TKey>` on the interface. I haven't tried it yet, but I expect it should work.

>If you make the repository interface IRepository<in T, TKey> does that fix it? Or... out?>

If I try either `in T` or `out T`, I get an "Invalid variance" error (CS1961) on multiple methods.

**Comment by tillig** [comment] 2021-12-13 23:59
What about if you switch to `IRepository<T, TKey> where T : BaseEntity<TKey>` - put the constraint on the interface?

I'm trying to figure out if this is a bug or if it's actually doing the right thing despite it seeming wrong. My gut says it's right because of that casting thing - that since the constraint isn't on the interface, the backing type doesn't fulfill the contract. At the same time, it sort of seems like you should be able to register it and get a runtime error if you try to resolve something that doesn't fit the contract.

This stuff kinda breaks my brain.

I'll be honest, I have some vacation coming up in a couple of days and will be taking a break (or really, really trying) from coding for a couple of weeks to un-burn-out. I don't know that we'll have this nailed by then. You may be stuck with the workaround through January or longer if we can't point to a specific part in the code that's stopping this from working and, subsequently, reason out whether that's correct.

@alistairjevans I hate to drag you in here, but a second set of eyes might help me unwrap things. I've been mitigating log4j and the mental language/context switching is causing me to squint real hard here but not actually arrive at any answers.

**Comment by alistairjevans** [comment] 2021-12-14 09:05
Hmm, so, unless I'm missing something in the original issue raise, I can't reproduce this. Here's my recreation of the steps presented originally, and this test passes:

```csharp
private interface IRepository<T, TKey>
    where T : class
{
}

private class Repository<T, TKey> : IRepository<T, TKey>
    where T : BaseEntity<TKey>
{
}

private class BaseEntity<TKey>
{
}

private class UserCredential : BaseEntity<Guid>
{
}

[Fact]
public void Isse1303ClassConstraint()
{
    var builder = new ContainerBuilder();

    builder.RegisterGeneric(typeof(Repository<,>)).As(typeof(IRepository<,>)).InstancePerDependency();

    var container = builder.Build();

    var repo = container.Resolve<IRepository<UserCredential, Guid>>();

    Assert.IsType<Repository<UserCredential, Guid>>(repo);
}
```

Is my test missing anything?

**Comment by gordon-matt** [comment] 2021-12-14 09:07
Odd. I will put together a small sample app as soon as I can find a minute

**Comment by gordon-matt** [comment] 2021-12-15 00:21
Okay, I have a test repo for you, here: [AutofacTypeVarianceIssue](https://github.com/gordon-matt/AutofacTypeVarianceIssue). If you run it, you will get the error. Then open `TestRepository.cs` and change the generic constraint (I've commented it out for convenience sake.. just comment the `BaseEntity<TKey>` one and uncomment the `class, IEntity` one) and you will see it works.

I'm not sure if there's perhaps a good reason for this not working, but it seems to be that since `ITestRepository<T, TKey>` specifies `T` to be a `class`... any class... then `TestRepository<T, TKey>` should be able to either specify `class` again or whatever specific actual class it wants to use.. and Autofac should be able to resolve it. No?

**Comment by alistairjevans** [comment] 2021-12-15 18:27
OK, was extremely confused for a minute there, but it looks like the problem you have in that example is that there are two `BaseEntity` classes. The one in `Extenso.Data.Entity`, which `TestRepository<T, TKey>` has a constraint on, and the one that `Person` derives from, in  `AutofacTypeVarianceIssue.Data.Entities`.

If you change your `TestRepositoryClass` to make the constraint class equal to the one on `Person`, the solution runs ok:

TestRepository.cs:
```csharp
using AutofacTypeVarianceIssue.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace AutofacTypeVarianceIssue.Data
{
    public class TestRepository<T, TKey> : Extenso.Data.Entity.EntityFrameworkRepository<T>, ITestRepository<T, TKey>
        // where T : class, IEntity
        where T : BaseEntity<TKey>
    {
        public TestRepository(Extenso.Data.Entity.IDbContextFactory contextFactory, ILoggerFactory loggerFactory)
            : base(contextFactory, loggerFactory)
        {
        }

        DbContext ITestRepository<T, TKey>.GetContext()
        {
            return base.GetContext();
        }
    }
}
```

Or, other way round, you can change your `Person` class:

```csharp
    public class Person : Extenso.Data.Entity.BaseEntity<int>
    {
        public string FamilyName { get; set; }

        public string GivenNames { get; set; }

        public DateTime DateOfBirth { get; set; }
    }
```

My guess is some name conflict / namespace issue is happening in your app in the same way it is here.

**Comment by tillig** [comment] 2021-12-15 18:47
Sounds like this is the likely challenge so I'm going to close this one. If you can provide a minimal repro that has _no dependencies outside Autofac and, like, common .NET SDK stuff_, we can reopen and reinvestigate. I think a good minimum bar for repro on something like this would be that you have to be able to put it in an issue comment - like in code fences - and assume it's a single Xunit test. All the types, as small as possible, no extra anything, and the test. If it takes a whole repo with a .csproj and extra references, it's not minimal enough. We need to be able to rule out the interaction of any third-party components.

**Closed by tillig** 2021-12-15 18:47 UTC

**Comment by gordon-matt** [comment] 2021-12-15 19:59
Amazing.. Sometimes it really does just need a fresh pair of eyes. Thank you for your time.. it is indeed working fine.
