### ISSUE TITLE
Lifetime scope in an unobserved task

### ISSUE THREAD

**Issue by rosskostron** [autofac/Autofac#971] opened 2019-03-26 19:28 UTC
since updating from 4.8.1, the following scenario is now throwing an ObjectDisposedException when calling Resolve() inside of DoWork() even though I do not call Dispose() until after DoWork() is complete

    public void TriggerWork()
    {
        ILifetimeScope lifetimeScope = this._lifetimeScope.BeginLifetimeScope();

        _ = Task.Run(async () =>
        {
            try
            {
                await this.DoWork(lifetimeScope);
            }
            finally
            {
                lifetimeScope.Dispose();
            }
        });
    }

    private async Task DoWork(ILifetimeScope nestedLifetimeScope)
    {
        IService service = nestedLifetimeScope.Resolve<IService>();
        await service.DoLotsOfWork();
        
        IAnotherService anotherService = nestedLifetimeScope.Resolve<IAnotherService>();
        await anotherService.DoEvenMoreWork();
    }

**Comment by tillig** [comment] 2019-03-26 20:02
I'm not able to reproduce this in a unit test. On first glance it appears there's some sort of condition where `lifetimeScope` is going out of scope for the `TriggerWork` method and the closure isn't being respected or something, but I've not got a lot of experience with unobserved tasks, fire and forget style. It might be something you could [ping Stephen Cleary on](https://blog.stephencleary.com/2013/11/taskrun-etiquette-examples-even-in.html) to see if he has ideas, since he seems to be the community expert.

I did notice that [unobserved task exceptions don't bubble up to the caller](https://stackoverflow.com/questions/33086371/what-happens-if-i-dont-await-a-task), so either you're seeing it in a debugger or this is partial code that doesn't show how you're figuring out there's an exception going on.

Without some sort of a way to repro it, I can't debug it.

[In 4.9.0 we added code that will actively throw an ObjectDisposedException if an activator is called from a lifetime that's been disposed](https://github.com/autofac/Autofac/releases/tag/v4.9.0) - #945, #960. It may be that there is something going on where you were inadvertently making use of a bug that we've fixed. I'm guessing; I don't actually know.

We do use [SourceLink for debugging now](https://github.com/dotnet/sourcelink) to make it easier to step into the Autofac core code. If you can't create a repro for us, that may be a way to figure out on your end what's going on and give us some pointers.

**Comment by tillig** [comment] 2019-07-05 17:28
Since we haven't heard back on this, I'm going to close it. If there's a way we can reproduce it in a unit test scenario, let us know by opening a new issue, otherwise we're sort of stuck. Thanks!

**Closed by tillig** 2019-07-05 17:28 UTC
