### ISSUE TITLE
[Bug (maybe?)] Concurrency test failing sporadically

### ISSUE THREAD

**Issue by alsami** [autofac/Autofac#1175] opened 2020-07-23 07:38 UTC
## Describe the Bug

I've noticed that one of the tests is sometimes failing during CI

## Steps to Reproduce
Hard to reproduce, does not always fail.

![image](https://user-images.githubusercontent.com/2729205/88262245-179e5780-ccc8-11ea-9da7-5865640c4c95.png)

Check out the existing test `Autofac.Test.Concurrency.ConcurrencyTests.RepeatedResolveWhileTheScopeIsDisposing_ObjectDisposedExceptionThrownOnly`

## Expected Behavior

Concurrency-Test should not throw `System.NullReferenceException`

## Exception with Stack Trace

```text
  Stack Trace:
     at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request) in /home/appveyor/projects/autofac/src/Autofac/Core/Lifetime/LifetimeScope.cs:line 297
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) in /home/appveyor/projects/autofac/src/Autofac/ResolutionExtensions.cs:line 1061
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters) in /home/appveyor/projects/autofac/src/Autofac/ResolutionExtensions.cs:line 899
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Test.Concurrency.ConcurrencyTests.<>c__DisplayClass7_0.<ResolveWhileTheScopeIsDisposing_ObjectDisposedExceptionThrownOnly>b__1() in /home/appveyor/projects/autofac/test/Autofac.Test/Concurrency/ConcurrencyTests.cs:line 174
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Autofac.Test.Concurrency.ConcurrencyTests.ResolveWhileTheScopeIsDisposing_ObjectDisposedExceptionThrownOnly() in /home/appveyor/projects/autofac/test/Autofac.Test/Concurrency/ConcurrencyTests.cs:line 186
   at Autofac.Test.Concurrency.ConcurrencyTests.RepeatedResolveWhileTheScopeIsDisposing_ObjectDisposedExceptionThrownOnly() in /home/appveyor/projects/autofac/test/Autofac.Test/Concurrency/ConcurrencyTests.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
Results File: /home/appveyor/projects/autofac/test/Autofac.Test/TestResults/_appveyor-vm_2020-07-23_05_50_31.trx
```

## Dependency Versions

All the code based on `v6` for sure.

**Comment by alistairjevans** [comment] 2020-07-28 07:07
I've spent some time trying to recreate this, and have had no luck. 

@alsami, have you got links to the CI builds that failed? How many times have you seen this?

**Comment by alsami** [comment] 2020-07-28 07:43
> I've spent some time trying to recreate this, and have had no luck.

Yeah me too. Rider has a functionality to "run test until it fails". Did that for half an hour, no luck.



> @alsami, have you got links to the CI builds that failed? How many times have you seen this?

Here the [link](https://ci.appveyor.com/project/Autofac/autofac/builds/34254898) where only `codecov.yml` was added.

**Comment by alistairjevans** [comment] 2020-07-29 05:39
Not sure where to go with this one now. So far I've tried the following, with no luck at getting a recreate:

- Run the tests a load of times on Windows and Ubuntu.
- Running the tests with code coverage attached, just in case that was related.
- Altering the timings to make them more random within the test, to give a distribution of wait times.
- Tried limiting the thread pool size to more closely resemble the 2-core Ubuntu build server.

I've been through the code for `ResolveComponent`, and I'll just lay out my analysis here.

```csharp
public object ResolveComponent(ResolveRequest request)
{
    if (request == null) throw new ArgumentNullException(nameof(request));

    // This is where the disposal is checked. This method is AggressiveInlining, so exceptions thrown
    // in this method will end up displaying as though they were from the ResolveComponent method.
    CheckNotDisposed();

    // Nothing in the below code could throw a null reference exception that results in the
    // displayed stack trace. None of the below methods are inlined, so would show a different frame at the top of the stack.
    var operation = new ResolveOperation(this, DiagnosticSource);
    var handler = ResolveOperationBeginning;
    handler?.Invoke(this, new ResolveOperationBeginningEventArgs(operation));
    return operation.Execute(request);
}

[MethodImpl(MethodImplOptions.AggressiveInlining)]
private void CheckNotDisposed()
{
    // Invokes the method IsTreeDisposed which does the actual check, then throws a clear ObjectDisposedException.
    if (IsTreeDisposed())
        throw new ObjectDisposedException(LifetimeScopeResources.ScopeIsDisposed, innerException: null);
}

[MethodImpl(MethodImplOptions.AggressiveInlining)]
private bool IsTreeDisposed()
{ 
    // This line here is the only possible place that could ever throw a null reference exception,
    // if IsDisposed was false, and  _parentScope was somehow changed to be null after it's checked for being an object, 
    // but before we call IsTreeDisposed.
    // However, due to the nature of the Disposable class, IsDisposed is guaranteed to always be true before
    // _parentScope is set to null, so I can't see how it could ever trip up invoking IsTreeDisposed on the parent scope.
    return IsDisposed || (_parentScope is object && _parentScope.IsTreeDisposed());
}
```

I'm pretty confused at this point.

**Comment by alsami** [comment] 2020-07-29 05:54
So the part where it says that the error actually occurred in `ResolutionExtensions` is irrelevant?

```text
/home/appveyor/projects/autofac/src/Autofac/ResolutionExtensions.cs:line 1061
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters) in /home/appveyor/projects/autofac/src/Autofac/ResolutionExtensions.cs:line 899
```

Code for line `1061` in `ResolutionExtensions`
```csharp
[SuppressMessage("Microsoft.Design", "CA1007:UseGenericsWhereAppropriate")]
public static bool TryResolveService(this IComponentContext context, Service service, IEnumerable<Parameter> parameters, [NotNullWhen(returnValue: true)] out object? instance)
{
    if (context == null)
    {
        throw new ArgumentNullException(nameof(context)); // here
    }

    if (!context.ComponentRegistry.TryGetServiceRegistration(service, out var serviceRegistration))
    {
        instance = null;
        return false;
    }

    instance = context.ResolveComponent(new ResolveRequest(service, serviceRegistration, parameters));
    return true;
}
```
and for line 899
```csharp
public static object ResolveService(this IComponentContext context, Service service, IEnumerable<Parameter> parameters)
{
    if (context == null)
    {
        throw new ArgumentNullException(nameof(context));
    }

    if (service == null)
    {
        throw new ArgumentNullException(nameof(service));
    }

    if (parameters == null)
    {
        throw new ArgumentNullException(nameof(parameters));
    }

    if (!context.TryResolveService(service, parameters, out var instance))
    {
        throw new ComponentNotRegisteredException(service); // here
    }

    return instance;
}
```

**Comment by alistairjevans** [comment] 2020-07-29 05:59
The stack trace indicates that the frame at the top of the stack is the `ResolveComponent` method:

```

**Comment by alistairjevans** [comment] 2020-07-29 06:01
The stack trace indicates that the frame that threw the exception is `ResolveComponent`:

```
at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request) in /home/appveyor/projects/autofac/src/Autofac/Core/Lifetime/LifetimeScope.cs:line 297
```

That method doesn't access any properties of the passed-in `ResolveRequest`, so the callers are unlikely to be the problem.

**Comment by alistairjevans** [comment] 2020-08-05 07:57
Right, so after running the Appveyor CI about 20 times on v6, I cannot get this to reproduce at all on CI either now; currently howling at the moon in frustration.

I have downloaded the Appveyor-build DLLs and decompiled it, and IL for the relevant locations is identical to a local build of the same code (as you'd expect).

I'm going to raise a PR for a change to protect the only possible location that could be responsible for the null ref, even though logically speaking I don't understand how it would ever hit it.

It sucks, because I can't prove that the change fixes it, only that it may be sensible to make the change anyway.

**Comment by alsami** [comment] 2020-08-05 09:09
Maybe that's the best you could do. I am wondering is the `is object` in a specific moment is true, but then something happens and the second part throws. If that still doesn't fixed it, would be some sort of locking be an option? I know that's always bad for performance.

**Comment by tillig** [comment] 2020-08-05 14:24
Hopefully the PR, which got merged, fixes it. Let's close this for now and if it rears its ugly head again, we can reopen.

**Closed by tillig** 2020-08-05 14:24 UTC
