### ISSUE TITLE
RegisterAssemblyModules() throws System.IO.FileNotFoundException when loading System.Private.* (Self-contained .NET Core application)

### ISSUE THREAD

**Issue by gitchomik** [autofac/Autofac#878] opened 2017-10-19 12:59 UTC
I have got this issue when method `RegisterAssemblyModules()` tries to load library with reference to _System.Private.ServiceModel_

The problem probably can be also related to any other _System.Private.*_
because sometime these files can be located in subdirectories, for example:
`bin\netcoreapp2.0\publish\runtimes\unix\lib\netstandard2.0\`
or 
`bin\netcoreapp2.0\publish\runtimes\win7\lib\netstandard2.0\`

Quick pseudocode scenario:
1. Create project B (B.dll)
- add reference _System.ServiceModel.Primitives, System.ServiceModel.Http_, there is no need to directly 
reference _System.Private.ServiceModel_, but after `dotnet publish` _System.Private.ServiceModel.dll_ will appear in application subdir `bin\netcoreapp2.0\publish\runtimes\win7\lib\netstandard2.0\`
- create 'Service.cs' and use _System.ServiceModel.*_
- create ```class Module : Autofac.Module``` and register 'Service'
2. Create project A (A.dll)
- **DO NOT** reference B.dll (adding reference to B.dll you will fix this problem)
- pseudocode : ```containerBuilder.RegisterAssemblyModules("B.dll");```
3. run
```
dotnet publish A
dotnet publish B
dotnet bin\netcoreapp2.0\publish\A.dll
```
4. throws
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Private.ServiceModel, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Private.ServiceModel, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element)
   at Autofac.Util.TypeExtensions.IsCompilerGenerated(Type type)
   at Autofac.Features.Scanning.ScanningRegistrationExtensions.<>c__DisplayClass3_0.<ScanTypes>b__2(Type t)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Autofac.Features.Scanning.ScanningRegistrationExtensions.ScanTypes(IEnumerable`1 types, IComponentRegistry cr, IRegistrationBuilder`3 rb)
   at Autofac.ContainerBuilder.Build(IComponentRegistry componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at Autofac.ModuleRegistrationExtensions.RegisterAssemblyModules(IModuleRegistrar registrar, Type moduleType, Assembly[] assemblies)
   at Program.Main(String[] args) in c:\_!_Projekt\.NET_Standard\Autofac.bug\A\Program.cs:line 26
```

Check this out full issued code:
https://github.com/gitchomik/Autofac.bug

**Additional info:**
Self-contained .NET Core application deployment.
Autofac 4.6.2
.NET Standard 2.0,
Windows 10 x64 or docker microsoft/dotnet:2.0.0-runtime-jessie (Linux ubuntu 4.10.0-37-lowlatency)

**Comment by tillig** [comment] 2017-10-27 18:57
I was able to reproduce it, but as it turns out this isn't so much about Autofac and is more about how .NET Core handles dynamic assembly loading and probing paths.

In .NET classic (the full desktop installed framework) the various framework packages were either in your `bin` folder or in the GAC. Now there's a whole runtime dependency chain and one app when published doesn't necessarily include all the runtime requirements for some other, separate, unreferenced app/plugin.

There are a lot of StackOverflow questions and issues about how to properly dynamically load a separate, unreferenced assembly. By and large it appears you need to implement the `AssemblyLoadContext` class and handle assembly lookups. I don't have a working example myself, but these should get you where you're going.

- https://shazwazza.com/post/custom-assembly-loading-with-aspnet-core/
- dotnet/corefx#21982
- https://stackoverflow.com/questions/37895278/how-to-load-assemblies-located-in-a-folder-in-net-core-console-app
- https://www.codeproject.com/Articles/1194332/Resolving-Assemblies-in-NET-Core

**Closed by tillig** 2017-10-27 18:57 UTC
