### ISSUE TITLE
Crash on IOS with linker enabled

### ISSUE THREAD

**Issue by tzachshabtay** [autofac/Autofac#842] opened 2017-04-01 02:41 UTC
On IOS, when the mono linker is enabled (and it’s enabled by default and recommended by Xamarin) it strips out all parts of the framework which are not in use. The linker does not support reflection, however, therefore it does not recognize the call to 'GetRuntimeMethod(nameof(Convert.ChangeType)' (which is called in ConstructorParameterBinding -> ConvertPrimitiveType) as using the 'Convert.ChangeType' method and strips it away unless it's explicitly used somewhere else, crashing Autofac if that method is called (null reference exception as ‘GetRuntimeMethod’ returns null).

Note PR https://github.com/autofac/Autofac/pull/841 that I opened as possible solution for that.

To reproduce, try resolving a constructor with optional float parameters on an IOS device when the linker is enabled. Note that by default the linker is disabled on the IOS simulator but enabled on a device, so you won't reproduce it on the simulator unless you explicitly enable the linker on the simulator.

As a real case for reproduction, you can use this branch (note that I will add a workaround in a future commit so get the commit from this day): https://github.com/tzachshabtay/MonoAGS/tree/IOS, and run DemoQuest.IOS.

<details>
<summary>This is the exception I got by doing that:</summary>

```
Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = AGSCamera (ReflectionActivator), Services = [AGS.API.ICamera], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> Value cannot be null.
Parameter name: method (See inner exception for details.) ---> System.ArgumentNullException: Value cannot be null.
Parameter name: method
  at System.Linq.Expressions.Expression.Call (System.Reflection.MethodInfo method, System.Linq.Expressions.Expression arg0, System.Linq.Expressions.Expression arg1) [0x0004c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/dlr/Runtime/Microsoft.Scripting.Core/Ast/MethodCallExpression.cs:548 
  at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.ConvertPrimitiveType (System.Linq.Expressions.Expression valueExpression, System.Type conversionType) [0x0003b] in <fdcd048585a94c00af1b381645caf165>:0 
  at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.GetConstructorInvoker (System.Reflection.ConstructorInfo constructorInfo) [0x00066] in <fdcd048585a94c00af1b381645caf165>:0 
  at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate () [0x00077] in <fdcd048585a94c00af1b381645caf165>:0 
  at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance (Autofac.IComponentContext context, System.Collections.Generic.IEnumerable`1[T] parameters) [0x000a9] in <fdcd048585a94c00af1b381645caf165>:0 
  at Autofac.Core.Resolving.InstanceLookup.Activate (System.Collections.Generic.IEnumerable`1[T] parameters) [0x0001a] in <fdcd048585a94c00af1b381645caf165>:0 
   --- End of inner exception stack trace ---
  at Autofac.Core.Resolving.InstanceLookup.Activate (System.Collections.Generic.IEnumerable`1[T] parameters) [0x0004d] in <fdcd048585a94c00af1b381645caf165>:0 
  at Autofac.Core.Resolving.InstanceLookup.Execute () [0x0006b] in <fdcd048585a94c00af1b381645caf165>:0 
  at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance (Autofac.Core.ISharingLifetimeScope currentOperationScope, Autofac.Core.IComponentRegistration registration, System.Collections.Generic.IEnumerable`1[T] parameters) [0x0005f] in <fdcd048585a94c00af1b381645caf165>:0 
  at Autofac.Core.Resolving.ResolveOperation.ResolveComponent (Autofac.Core.IComponentRegistration registration, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00000] in <fdcd048585a94c00af1b381645caf165>:0 
  at Autofac.Core.Resolving.ResolveOperation.Execute (Autofac.Core.IComponentRegistration registration, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00000] in <fdcd048585a94c00af1b381645caf165>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 
  at DemoGame.DemoStarter+<Run>c__AnonStorey8+<Run>c__async7.MoveNext () [0x00163] in /Users/zachi/Projects/MonoAGS/Source/Demo/DemoQuest/Program.cs:33 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.6.0.10/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018 
  at AGS.Engine.AGSSyncContext+<Post>c__AnonStorey0.<>m__0 () [0x0000c] in /Users/zachi/Projects/MonoAGS/Source/Engine/AGS.Engine/Game/AGSSyncContext.cs:34 
  at AGS.Engine.AGSSyncContext.PumpMessages () [0x00008] in /Users/zachi/Projects/MonoAGS/Source/Engine/AGS.Engine/Game/AGSSyncContext.cs:28 
  at AGS.Engine.AGSGame+<Start>c__AnonStorey1+<Start>c__async3.MoveNext () [0x0004c] in /Users/zachi/Projects/MonoAGS/Source/Engine/AGS.Engine/Game/AGSGame.cs:134 
```
</details>

**Comment by tzachshabtay** [comment] 2017-04-01 02:50
Some responses to @tillig from the PR thread:

1. Yes, thought the same think about asking support for nameof from Xamarin, just figured I'll put a PR here first as my previous experience with Xamarin dictates it might take a while (if they agree at all). I reported a bug on the mono linker (https://github.com/mono/linker/issues/55), I hope that's the right place for that, will see what they say, otherwise will report in their bugzilla and link in the issue. 

2. Regarding a manifest file, they have a linker configuration file which they describe here (https://developer.xamarin.com/guides/cross-platform/advanced/custom_linking/) although I didn't see any description there of how to name the file and where to put it. Plus it will probably require additional work to use that and making sure it's copied in the build, it seems much simpler calling it once from code. And also, like you said, this might pose a problem with other platforms as well, so by using code you can solve this for various platforms (i.e I would argue this should have been done for UWP instead of a manifest, if that was possible).

3. Regarding where to put it, it makes sense to me to put it in that same class, i.e in a close place and not in a central location as it will make it easier to maintainers to see it if they change the code.

4. How do we know if we fix the overall issue? Well, I don't. I searched the entire solution for `GetRuntimeMethod`, this is the only place. I don't what other reflection methods might be used in the solution though and don't know if there's some tool that's doing that. One thing that can maybe be done is adding to the CI build the ability to run the unit tests on either an ios device (with something like Xamarin test cloud, maybe?) or the ios simulator with the linker enabled (maybe it's possible using a docker container?).

5. Regarding the failing code analysis on the PR, it fails because it uses the culture unaware version of Convert.ChangeType, but I'm using that because that's what the reflection code is doing. This means that the code that is in production is breaking the analyzer, only the analyzer is not smart enough to catch that. So it's either fixing the original reflection calling code to use the IFormatProvider (by passing InvariantCulture?), which I'm not really sure how, as I've never used the Expression API myself, or suppressing the error.

**Comment by tillig** [comment] 2017-04-01 03:02
I only mentioned the UWP thing because the "only happens when a certain compilation setting is enabled" sort of thing was similar. In UWP the problem was/is that UWP by default doesn't bring in reflection symbols for types unless you specify to do so. That creates a problem when you want to register types that aren't yours with DI. That's not something we can change in code. The only solution is, truly, to use a manifest and specify which types you need to allow reflection over. There was literally nothing we could do from our end to change that.

The similarity is that this is happening with reflection, which auto-instantiation in .NET effectively requires. You happen to be seeing it in `nameof` usage, but since almost everything in Autofac has _something_ to do with reflection and getting runtime type information, I feel like this might get _you_ past the thing you're seeing but won't actually _solve the larger problem_. Which is to say, if there is a way to handle this in an "official" capacity, I'd rather use that and document what you need to do to make it work rather than just hack something in really quick to get around it.

Side note on the `Convert.ChangeType` thing - not that it matters at this moment, but since the call you added to the `static` constructor really doesn't matter, you'd just pass in something like `CultureInfo.InvariantCulture` and call it good. It just needs _some_ culture provider and in this throwaway case it doesn't really matter which one.

Anyway, I'm going to close the PR for now and we can work through here what the correct solution is. If it is to just pop something in the static constructor, we can revive #841 and go from there.

I'm not much of an iOS guy so it'll take me a bit to look into this. Any additional docs/links/examples you can point to with examples, any simpler/dedicated repro you can provide, etc. are welcome. I don't know if @alexmg may have more iOS experience than me, but I'll tag him and see if he has something to add.

**Comment by tzachshabtay** [comment] 2017-04-01 03:58
Regarding the side note on `Convert.ChangeType`, no, I can't just pass `InvariantCulture` in my method and call it good, as then it's not the same method used in `ConvertPrimitiveType` so the linker will be keeping the wrong method (tested this to make sure I know what I'm saying). 
If I add `InvariantCulture` to the static constructor, then it needs to be added to the call in `ConvertPrimitiveType` as well using the Expression API.

**Comment by tillig** [comment] 2017-04-01 05:32
I guess that makes me think even more that we need to solve this differently. I don't know if there's a guarantee about which overload the linker will "want" (unless that's documented?) for its `nameof` use so just including the one overload may not work from linker version to linker version. I know in general there's no guaranteed order to how .NET will return methods when queried; I have to assume that about the handling in mono, too.

Anyway, interesting stuff. We'll need to dig more into this.

**Comment by tillig** [comment] 2017-04-01 05:44
Which tools/versions are you using? (Visual Studio, Xamarin Studio, etc.) Reason I ask is I see some issues [like this one](https://bugzilla.xamarin.com/show_bug.cgi?id=37585) that make it sound like some of these things are fixed in newer tools. Maybe not this specific thing, but it'll help to know which versions you're on.

**Comment by tzachshabtay** [comment] 2017-04-01 13:41
I'm using Xamarin Studio 6.2.1 (build 3).
As for your earlier comment, I believe `nameof` is replaced at compile time (http://stackoverflow.com/questions/26573102/is-nameof-evaluated-at-compile-time), so the linker probably will not be able to support it at all. If it was possible I can see only one possible conclusion the linker could make, which is to keep all of the overloads.

**Comment by tillig** [comment] 2017-04-03 18:42
For reference (as we work this through) the `nameof` usage causing problems is [on line 187 of `ConstructorParameterBinding`](https://github.com/autofac/Autofac/blob/db0d058b5b58a99c80928e9ad46142271ad0f64e/src/Autofac/Core/Activators/Reflection/ConstructorParameterBinding.cs#L187) and looks like this:

```csharp
        public static MethodCallExpression ConvertPrimitiveType(Expression valueExpression, Type conversionType)
        {
            var changeTypeMethod = typeof(Convert).GetRuntimeMethod(nameof(Convert.ChangeType), new[] { typeof(object), typeof(Type) });
            return Expression.Call(changeTypeMethod, valueExpression, Expression.Constant(conversionType));
        }
```

Something that confuses me is that the `nameof(Convert.ChangeType)` should be evaluated by the compiler to be a string, so it should effectively have been resolved to the following by the time the linker got to it:

```csharp
        public static MethodCallExpression ConvertPrimitiveType(Expression valueExpression, Type conversionType)
        {
            var changeTypeMethod = typeof(Convert).GetRuntimeMethod("ChangeType", new[] { typeof(object), typeof(Type) });
            return Expression.Call(changeTypeMethod, valueExpression, Expression.Constant(conversionType));
        }
```

What I'm wondering is: Is the problem the use of `nameof` or is it the use of `GetRuntimeMethod`? **I have a feeling it's `GetRuntimeMethod` and the `nameof` part is a red herring.** The exception stack trace is showing that the problem is with `changeTypeMethod` being null; if the `nameof` part wasn't working I think the call to `GetRuntimeMethod` would actually be failing with some sort of exception. This is actually [alluded to in the mono linker issue](https://github.com/mono/linker/issues/55).

Part of the challenge in fixing this is that we actually need the reflection `MethodInfo` for `Convert.ChangeType` to build up the expression. Off the top of my head I'm not sure how to get that without something like a call to `GetRuntimeMethod`. It'd be nice if there was a `methodof` operator the way there's a `typeof` operator [but that's not coming](https://blogs.msdn.microsoft.com/ericlippert/2009/05/21/in-foof-we-trust-a-dialogue/) so... reflection it is.

Note technically we should be getting the three-parameter `Convert.ChangeType` to include formatter info explicitly, but we're not - which is why the static reference to the three-parameter version wouldn't have worked [in the pull request](#841). That's unrelated to the overall problem here but answers that question.

Given a lot of what Autofac does has to do with reflection (getting the list of constructors in a type, etc.) I still think there's got to be a better way to handle this. I think we'd end up hacking something in to fix this one thing and run into a different thing elsewhere. Going to have to think some more on this.

**Comment by tzachshabtay** [comment] 2017-04-03 19:58
1. Just to clear up regarding "what the problem is" and `nameof`: From Autofac's perspective `nameof` works and `GetRuntimeMethod` returns null. That's because `nameof` is evaluated in the compiler, before the linker strips away the method. I thought that the reason you brought up `nameof` was because it's a potential solution to the problem from the linker side, not because it's the problem. I.E if by some magic the linker can be made aware of `nameof` (either by the compiler supplying some metadata or by the linker going over the original source code in addition to the compiled code) it can leave the method in, and then `GetRuntimeMethod` will work.

2. Regarding your last paragraph, about other uses of reflection in Autofac. There's a subtle but important difference: `Convert.ChangeType` is a framework method, whereas resolving constructors on a type is used on client code. Note that when configuring the IOS project you actually have 3 choices for the linker: strip everything, strip framework code, don't strip. The default is "strip framework code", which is why resolving constructors work by default. If 'strip everything' is selected, then it won't work if those constructors are not used but there's a `Preserve` attribute the user can put on the methods he/she wants to keep (this is not something that can be done with framework code as you don't have access to the code), and it's not something Autofac can do on its side (or at least I don't see anything you can do, except maybe document it somewhere), you have no knowledge on which constructors and types will be called on the client side, so that's up to the user to address.

**Comment by tzachshabtay** [comment] 2017-04-03 20:23
Either I was blind before or they just added more information to the linker configuration file page (https://developer.xamarin.com/guides/cross-platform/advanced/custom_linking/), but it actually explains how to do this and it seems pretty simple: add the xml file to the project and set the `Build Action` to `Link Description`, so that's a viable alternative solution.

**Comment by tillig** [comment] 2017-04-04 13:05
Looks like they're [going to use the mono linker for .NET Core](https://github.com/dotnet/corefx/pull/17825) and they intend to use the XML mechanism to stop it from over-trimming thing there, too.

Given that, I think this is probably an issue we can handle with some docs and an example XML file. It's more than zero work for the consumer but appears to be the way this is intended to be handled.

**Comment by tillig** [comment] 2017-04-18 21:48
@tzachshabtay Did you ever figure out the right linker XML file for this?

**Comment by tzachshabtay** [comment] 2017-04-20 03:28
The link I posted in my last comment explains how to add the XML linker file.

**Comment by tillig** [comment] 2017-04-20 03:35
Right, I was curious if you had a working example we could start from for documentation.

**Comment by tzachshabtay** [comment] 2017-04-20 03:38
No, I used my first proposal on my project as a workaround, which solves it for me.

**Comment by tillig** [comment] 2017-04-24 22:04
[I added some docs on Xamarin and .NET Native](http://autofac.readthedocs.io/en/latest/advanced/cross-platform-apps.html) to help address the reflection challenges folks might see in compiling down to native platforms.

**Closed by tillig** 2017-04-24 22:04 UTC
Labels: question

**Comment by tzachshabtay** [comment] 2017-04-24 23:50
Not sure why you would want the users digging in the documentation when you can solve this issue for everybody with one file inclusion (or one line of code).

**Comment by tillig** [comment] 2017-04-25 00:48
We solved this with documentation for several reasons:

1. Adding the "one line of code" isn't maintainable long-term since refactoring one area of that class can potentially pretty easily break the "fix" and we don't really have the ability to test on every platform under every linker configuration.
2. That line might fix it for core Autofac but not necessarily for any of the extras or extension libraries, which may also need their own lines of code.
3. That line might fix it for Xamarin + iOS but doesn't necessarily fix it for UWP with .NET Native or any other cross-platform compilation mechanism.
4. That line might fix it for Autofac but doesn't necessarily fix it for application code, which raises exceptions when app code doesn't also include all the reflection metadata (e.g., #686).

Since each compilation mechanism has its own way to set up directives for what to include or filter out, the best solution that will be sustainable long term is to help people understand why things are working the way they are so each app can solve it in the recommended way for the platform.

**Comment by 1iveowl** [comment] 2019-09-26 10:31
Some more documentation that seems related to this here: https://stackoverflow.com/questions/58114288/autofac-build-throws-exception-on-latest-xamarin-ios-when-linker-configured-to
