### ISSUE TITLE
Property injection is not registered correctly within modules

### ISSUE THREAD

**Issue by MFFoX** [autofac/Autofac#903] opened 2018-04-02 19:17 UTC
This was originally reported in October 2015, [here](https://stackoverflow.com/questions/33374519/autofac-only-works-in-controllers-not-for-referenced-class-libraries).

When a service is registered within a module via `PropertiesAutowired()`, the property is not injected. Instead, there are no autofac registration errors, the service is just null.

To reproduce:

AutofacModule.cs

    public class AutofacModule : Module
    {
        protected override void Load(ContainerBuilder builder)
        {
            builder.RegisterType<MyService>().AsSelf().InstancePerLifetimeScope()
                .PropertiesAutowired(PropertyWiringOptions.AllowCircularDependencies);
        }
    }

Startup.cs

```
//in ConfigureServices
var containerBuilder = new ContainerBuilder();
containerBuilder.Populate(services);
containerBuilder.RegisterModule(new AutofacModule());

var container = containerBuilder.Build();
return new AutofacServiceProvider(container);
```

SomeOtherService.cs

```
public class SomeOtherService {
    public MyService Service { get; set; } //will remain null when used
}
```

As a workaround, you can move the registration into `ConfigureServices` and it works ie

```
//in ConfigureServices
var containerBuilder = new ContainerBuilder();
containerBuilder.Populate(services);
containerBuilder.RegisterModule(new AutofacModule());

builder.RegisterType<MyService>().AsSelf().InstancePerLifetimeScope()
    .PropertiesAutowired(PropertyWiringOptions.AllowCircularDependencies);

var container = containerBuilder.Build();
return new AutofacServiceProvider(container);
```

I am using .NET Core 1.1.2 and Autofac 4.6.2. I can build a reproducible project if that'd be easier.

**Comment by tillig** [comment] 2018-04-02 19:47
Actually, if it's not too much trouble, that would be _very_ helpful. I've seen a lot of .NET Core projects out there using modules without issue so it'd be good to see something reproducing the specific challenge you're running into. Thanks!

**Comment by ngruson** [comment] 2018-04-15 12:34
Shouldn't you use PropertiesAutowired on SomeOtherService since that's the class containing the property you want to autowire? Just made a sample that works ok with ASP.NET Core 2.0 and Autofac 4.7.0 or 4.6.2. I don't have Core 1.1 installed. What version of Autofac.Extensions.DependencyInjection are you running?

**Comment by tillig** [comment] 2018-04-16 16:35
That's an excellent point, I see `MyService` getting properties autowired but I don't see where `SomeOtherService` is getting its properties set up as autowired. If `SomeOtherService` needs its properties populated, that registration also needs `PropertiesAutowired()`.

I'm going to close this issue based on that being the likely answer here. If there is a reproduction I can see where this isn't working, I can reopen it after I validate there's something going wrong.

**Closed by tillig** 2018-04-16 16:35 UTC
