### ISSUE TITLE
IStartable doesn't allow dependencies to respect singleton behavior

### ISSUE THREAD

**Issue by LexxFedoroff** [autofac/Autofac#722] opened 2016-03-04 09:11 UTC
Hello!
I've found some issue if I register type as SingleInstance.
Type is registered as singleton but it instance is created twice.
Version Autofac 3.5.2 and Autofac.4.0.0-rc1-177

Sample code, it should not assert but do it

``` cs
using System;
using System.Diagnostics;
using System.Threading;
using Autofac;

namespace AutofacTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var builder = new ContainerBuilder();
            builder.RegisterModule<RootModule>();
            var container = builder.Build();

            Console.WriteLine("done");
            Console.ReadLine();
        }
    }

    public interface ISemaphor
    {
    }

    public sealed class Startable : IStartable
    {
        private readonly ISemaphor[] _semaphors;

        public Startable(ISemaphor[] semaphors)
        {
            _semaphors = semaphors;
        }

        public void Start()
        {
        }
    }

    public sealed class Singleton : ISemaphor
    {
        private static int _count;

        public Singleton()
        {
            Interlocked.Increment(ref _count);
            Debug.Assert(_count < 2);
        }
    }

    public sealed class RootModule : Module
    {
        protected override void Load(ContainerBuilder builder)
        {
            builder.RegisterModule(new SubModule1());
            builder.RegisterModule(new SubModule2());
        }
    }

    public sealed class SubModule1 : Module
    {
        protected override void Load(ContainerBuilder builder)
        {
            builder.RegisterModule(new CoreModule());
        }
    }

    public sealed class SubModule2 : Module
    {
        protected override void Load(ContainerBuilder builder)
        {
            builder.RegisterModule(new CoreModule());
        }
    }

    public sealed class CoreModule : Module
    {
        protected override void Load(ContainerBuilder builder)
        {
            builder.RegisterType<Startable>().AsImplementedInterfaces();
            builder.RegisterType<Singleton>().AsImplementedInterfaces().SingleInstance();
        }
    }
}
```

**Comment by tillig** [comment] 2016-03-04 18:34
I've simplified the reproduction and added it as a failing unit test.

```csharp
private interface IStartableDependency { }

private class StartableDependency : IStartableDependency
{
    private static int _count = 0;

    public StartableDependency()
    {
        _count++;
    }

    public static int Count
    {
        get
        {
            return _count;
        }

        set
        {
            _count = value;
        }
    }
}

private class StartableTakesDependency : IStartable
{
    public StartableTakesDependency(IStartableDependency[] dependencies)
    {
    }

    public void Start()
    {
    }
}

[Fact]
public void StartableComponentsObeySingletonUsage()
{
    // Issue #722
    var builder = new ContainerBuilder();
    StartableDependency.Count = 0;
    builder.RegisterType<StartableTakesDependency>().AsImplementedInterfaces();
    builder.RegisterType<StartableDependency>().AsImplementedInterfaces().SingleInstance();
    builder.RegisterType<StartableTakesDependency>().AsImplementedInterfaces();
    builder.RegisterType<StartableDependency>().AsImplementedInterfaces().SingleInstance();
    builder.Build();
    Assert.Equal(1, StartableDependency.Count);
}
```

It doesn't seem to be a threading issue, so the interlocking/thread safety stuff doesn't matter. It also doesn't seem to have anything to do with module registration. I'm guessing there's something in the way we handle `IStartable` that's not jiving well with the handling of singletons.

**Comment by provan** [comment] 2016-11-21 20:14
Hi! I've even more simplified.

```csharp
private class Singleton
{
	private static int _count = 0;

	public Singleton()
	{
		_count++;
	}

	public static int Count
	{
		get { return _count; }

		set { _count = value; }
	}
}

[Fact]
public void StartableComponentsObeySingletonUsage()
{
	// Issue #722
	var builder = new ContainerBuilder();
	Singleton.Count = 0;
	builder.RegisterType<Singleton>().AsSelf().SingleInstance();
	builder.RegisterType<Singleton>().AsSelf().SingleInstance();
	builder.Build().Resolve<Singleton[]>();
	Assert.Equal(1, Singleton.Count);
}

```

**Comment by tillig** [comment] 2016-11-21 20:43
@provan There's no usage of `IStartable` or `AutoActivate` anywhere in your example. Your example is actually functioning as designed. You registered _two copies_ of a service, which is, for Autofac, _two wholly separate things_. You then resolved all of them. That's two singleton services, so the count will be two. That's correct.

**Comment by tillig** [comment] 2016-11-21 20:44
Of course, now that I see what it's doing... I can see that my simplification is _also_ wrong. I'm going to have to look at this more closely.

**Comment by tillig** [comment] 2016-11-21 20:46
@LexxFedoroff On reading this further, I'm actually thinking this is functioning as designed. As we've seen as we simplify what's going on, you're actually registering two different instances of the same service. If you wanted a true singleton, you can only register the thing once. Which means there may not actually be a bug here after all - and that it has nothing to do with `IStartable` so much as just not creating duplicate registrations.

Am I missing something?

**Comment by provan** [comment] 2016-11-21 22:19
@tillig  Are you sure that this behavior is correct?

For example, there is a hierarchy of modules (as in the first comment). The base module (CoreModule) registers SingletonService as SingleInstance().
CoreModule may be reused in different components, resulting in more than one registration of CoreModule and hence SingletonService.
Thus, from CoreModule's perspective service is registered as a singleton, but in fact there is no guarantee that it will remain a Singleton.
It depends on how many times CoreModule will be registered and how client would resolve my service: Resolve<TService>() or Resolve<TService[]>()
It does not seem very clear and does not allow full control over the code.

```csharp
[Fact]
public void SingletonResolvedViaEnumerable() // FAIL
{
	var builder = new ContainerBuilder();
	SingletonService.Count = 0;
	builder.RegisterType<SingletonService>().AsSelf().SingleInstance();
	builder.RegisterType<SingletonService>().AsSelf().SingleInstance();
	builder.Build().Resolve<IEnumerable<SingletonService>>();
	Assert.Equal(1, SingletonService.Count); 
}

[Fact]
public void SingletonResolvedTwice() // SUCCESS
{
	var builder = new ContainerBuilder();
	SingletonService.Count = 0;
	builder.RegisterType<SingletonService>().AsSelf().SingleInstance();
	builder.RegisterType<SingletonService>().AsSelf().SingleInstance();
	var container = builder.Build();
	container.Resolve<SingletonService>();
	container.Resolve<SingletonService>();
	Assert.Equal(1, SingletonService.Count); 
}

```

**Comment by tillig** [comment] 2016-11-21 22:33
First let me annotate the latter test.

```csharp
[Fact]
public void SingletonResolvedTwice()
{
  var builder = new ContainerBuilder();
  SingletonService.Count = 0;

  // First registration. Pretty standard.
  builder.RegisterType<SingletonService>().AsSelf().SingleInstance();

  // Second registration. This does two things:
  // - Add a second "copy" of the registration to the container.
  // - "Overrides" the first one. When you resolve a single object instance, you'll
  //   get this one activating, not the first registration.
  // There is NO EQUALITY CHECK anywhere to say, "If this was already
  // registered, treat it as the same." It's TWO DIFFERENT SERVICES inside
  // Autofac. They just happen to be backed by the same type.
  builder.RegisterType<SingletonService>().AsSelf().SingleInstance();

  var container = builder.Build();

  // This resolves that SECOND registration. The first one is never activated.
  container.Resolve<SingletonService>();

  // Again, the SECOND registration. First is still never activated.
  container.Resolve<SingletonService>();

  // Correctly passes - only one of the registrations was ever activated.
  // Just like with other services, it's last-in-wins. You just had two
  // of the same service.
  Assert.Equal(1, SingletonService.Count);
}
```

Knowing what we now know from that annotation...

```
[Fact]
public void SingletonResolvedViaEnumerable()
{
  var builder = new ContainerBuilder();
  SingletonService.Count = 0;

  // Just as with the first test, this is two separate services. Thus, there
  // are technically two registered, not one. The lifetime of each of these
  // is singleton, but that doesn't have any correlation to how many times
  // you chose to register the singleton.
  builder.RegisterType<SingletonService>().AsSelf().SingleInstance();
  builder.RegisterType<SingletonService>().AsSelf().SingleInstance();
  var container = builder.Build();

  // Of course we'll get TWO here because there are two different services.
  // Again, there is no EQUALITY checking going on. You registered twice,
  // you'll get two.
  container.Resolve<IEnumerable<SingletonService>>();

  // Fails because two different activations ran - both of the ones you registered.
  Assert.Equal(1, SingletonService.Count); 
}
```

This overlaps heavily with #747 - trying to figure out how to make sure a given module is only registered once. [We have a unit test illustrating how to use the property bag to opt-in and avoid duplicate module registration.](https://github.com/autofac/Autofac/blob/v4.2.0/test/Autofac.Test/ModuleTests.cs#L109)

It is up to the developer to make sure they're not double-registering things. This is totally functions-as-designed.

**Comment by tillig** [comment] 2016-11-21 22:35
Given this looks like the problem isn't with `IStartable` but actually with handling duplicate registrations, unless we hear otherwise in a week we'll go ahead and close it.

**Closed** 2017-06-20 14:55 UTC
Labels: bug
