### ISSUE TITLE
True decorators

### ISSUE THREAD

**Issue by ggrnd0** [autofac/Autofac#838] opened 2017-03-23 16:22 UTC
Now is 2 way to register multiple decorators:
1) http://stackoverflow.com/a/23407663 -- not flexible
2) veeery long way:
     - register implementor in `key='decorated'`
     - register 
            1. SmartDecoratorT decorator `decorated -> null`
            2. multiple ?DecoratorBuilder  as you need
    ```
    interface IDecoratorBulider<T>{T BuildDecorator(T target);}

    abstract class SmartDecoratorBase<T> {
        SmartDecoratorBase(T target, IEnumerable<IDecoratorBulider<T>> buliders){
            this.decorated = Bulid(target, buliders);
        }
        T Bulid(T target, IEnumerable<IDecoratorBulider<T>> buliders) {
            foreach(var builder in builders) target = builder.BuildDecorator(target);
            return target;
        }
    }

    class SmartDecoratorT : SmartDecoratorBase<T>,T{
        SmartDecoratorT (T target, IEnumerable<IDecoratorBulider<T>> buliders) 
            : base(target, buliders)
        { }

        void TMethod(){ decorated.TMEthod(); }
    }

    class SomeDecorator : T {
        SomeDecorator (T target, F dep) 
        {
            this.decorated=target;
             this.dep=dep;
        }

        void TMethod(){ 
            dep.X();
            decorated.TMEthod(); 
        }
    }

    class SomeDecoratorBuilder : IDecoratorBulider<T> {
        SomeDecorator (F dep) 
        {
             this.dep=dep;
        }

        T BuildDecorator (T target) 
        {
            return new SomeDecorator (target, dep);
        }
    }
    ```

    its very difficult to write for every T

Is there is simple 3 way?

**Comment by tillig** [comment] 2017-03-23 16:29
Based on the StackOverflow question you linked and the example of "decorator builders" I gather the question is about conditional registration of decorators. (I don't understand the title "True decorators" - we support decorators, but conditional registration is a challenge.)

Assuming that's the case, this is a duplicate of #727 where we're already talking about ideas around improving decorator usage, particularly with respect to conditionals. I'm going to close it as duplicate.

If it's not a duplicate, I'll need a better explanation of what you're trying to do and an updated title with additional clarity.

**Closed by tillig** 2017-03-23 16:29 UTC

**Comment by ggrnd0** [comment] 2017-03-23 16:43
It is not duplicate.

It is not about conditional registration of decorators.

You do not support decorators - you support adapters to itself with different key names....

But i need combination of multiple decorators for any T service registered in container.
 - I do not know will service be decorated before some one register decorator.
 - I do not want implement&register SmartDecorator for every T.
 - I do not want to use keys - its crutch for decorators. As i understand keys did not design for it?
    Keys is good idea, but not for decorators.
    For example: if i resolve T service from key="x1", it must be decorated with decorators from key = "x1"

**Comment by tillig** [comment] 2017-03-23 16:46
We do support decorators. [Here's the documentation on it.](http://autofac.readthedocs.io/en/latest/advanced/adapters-decorators.html) I agree the syntax isn't terribly pretty, but that's different than not supporting it at all.

The documentation shows how to register an open generic decorator.

Does that help?

**Comment by tillig** [comment] 2017-03-23 16:48
If you have a suggestion or request for better decorator syntax, consider opening an issue with what you'd _like_ and how you propose it would work. That way we can have a discussion about the design and improvements and prepare it for implementation. That would also separate it from the question of "how do I...?" and move it into more of a feature/enhancement request.

**Comment by ggrnd0** [comment] 2017-03-23 16:51
I already reed documentation.
It is not decorators - its just adapters T to T...
Yes, its use RegisterAdapter method =)

> If you have a suggestion or request for better decorator syntax

My english to bad to explain it :/
But i can code. I will make example today.

**Comment by tillig** [comment] 2017-03-23 17:03
[The adapter and decorator patterns are really, really similar.](http://stackoverflow.com/questions/6999834/is-this-called-adapter-adapter-vs-decorator) In an adapter, you basically _change the interface_ of one type to another; in a decorator you wrap an object that has a particular interface with another object that has the _same interface_, adding some logic along the way.

In both cases, there is a similarity:
- Start with initial object - we'll call that `Initial`
- Wrap the initial object with _something else_ - we'll call that `Wrapper`

If the `Wrapper` has the same interface as `Initial` - that's a **decorator**.

If the `Wrapper` changes the interface of `Initial` - that's an **adapter**.

I think we reuse some logic in the core library since they're so similar, so the internal naming may appear confusing, but it's still a decorator.

I look forward to your example.

**Comment by ggrnd0** [comment] 2017-03-24 18:55
Example code https://github.com/ggrnd0/autofac-decorator

There is 2 test.
1st for `2. veeery long way:`
2nd for `true decorators i want`

**Comment by tillig** [comment] 2017-03-24 19:13
It appears the disconnect here is that _you_ want control over the application of the decorators rather than delegating it to Autofac. Which is to say, you have this decorator factory thing and you want Autofac to use that instead of its own internal implementation. Is that right?

If not, I'm still not getting it.

**Comment by tillig** [comment] 2017-03-24 19:14
@alexmg Do you have any insight here?

**Comment by ggrnd0** [comment] 2017-03-24 19:18
There is `DecorationWrapper<T>` is just workaround i use now.

I want `RegisterTrueDecorator<T>()` method works to pass `DecorationWrapperTest`.

I do not want Autofac use `DecorationWrapper<T>`.
i want something better:
 - decorators bound to its namedScope
 - multiple decorators applyed to T from it's namedScope
 - current *decoration* feature will works with TrueDecorators as it specified in `DecorationWrapperTest`
 - i think there must be feature `decorator ordering` which will sort decorators

**Comment by tillig** [comment] 2017-03-24 19:21
None of these things have to do with the decorator pattern at all. Instead, it sounds like you want some enhancements to the syntax to make it easier to register decorators and possibly some new features.

Is that correct?

**Comment by ggrnd0** [comment] 2017-03-24 19:31
The problem in parameters `fromKey, toKey`

If i specify 2+ decorators from(X)to(Y) only last will applyed
Also it require use different namedScope for registering and resolving T.

I want it will work with multiple decorators in current scope only.

I fix type 2ns test class name is `TrueDecoratorTest`. Check code again, please.

**Comment by ggrnd0** [comment] 2017-03-24 20:01
Any ideas ?

**Comment by tillig** [comment] 2017-03-24 20:12
This is going to take me some time to think about. Keep in mind this isn't my full time job and I'm not paid for it. Also, I'm on the west coast of the US and we're heading into spring break so I'm going to be taking some time off with my family. I won't be able to address any of this in any deep capacity in a super soon fashion.

My initial thoughts:
- The `fromKey` / `toKey` thing is one way to specify order.
- We don't have a way to say "register arbitrary decorator for type `T` and just apply them all in order." That's one of the syntax improvement requests I was talking about.
- There is a problem with the notion of passing parameters to decorators that may create a challenge. Is the parameter for the decorator or for the thing it's decorating? If you resolve something `WithParamter(...)` which thing uses the parameter? Right now we assume decorators themselves don't get parameters.

Again, though, _none of this has anything to do with the decorator pattern_. The way I read this, you want:

- A way to register decorators without having to specify keys.
- A way to register decorators so they only apply to a specific named/keyed service.
- A way to specify decorator order.

You are right that we don't have a great solution to any of that except for some cumbersome challenges around using `fromKey` and `toKey` in a confusing manner. This could be accomplished with some syntax improvements to remove the key requirement as well as some enhancements for things like ordering.

Is there something I'm missing?

**Comment by ggrnd0** [comment] 2017-03-24 20:21
> There is a problem with the notion of passing parameters to decorators that may create a challenge

if there is multiple decorators registered:
```
    var t = new Decorator1(
        new Decorator2(
            ...
                new DecoratorN(implementation)
            ...
        )
    );
```

its all i think.
But as specified in `TrueDecoratorTest` it can works with current decorator implementation.
Transiting service between namedScope is not bad sometimes...

**Comment by ggrnd0** [comment] 2017-03-24 20:25
decorator order is not very important, but if it can be implemented it is must=)

**Comment by alexmg** [comment] 2017-03-25 01:35
I'm sure some of these are already covered by existing issues. I will read through this in detail a bit later and extract any new issues.

**Comment by ggrnd0** [comment] 2020-02-17 11:26
Had any thing done with decorators?
i may need .net DI on next project...

**Comment by ggrnd0** [comment] 2020-02-17 12:06
Just found new sintax https://autofaccn.readthedocs.io/en/latest/advanced/adapters-decorators.html
looks fine, but. 
How it works with scopes(keys)?
is it able to register decorator only for one scope="handler"?
how it works with adapters?

can i register service in scope=handler
register decorator in scope=handler
register adapter from scope=handler
register global decorator
and they all will work together?

```
new GlobalDecorator(
    new Adapter(
        new HandlerScopeDecorator(
            new Service()
        )
    )
)
```

**Comment by alexmg** [comment] 2020-02-21 12:14
@ggrnd0 

> How it works with scopes(keys)?

You can apply a decorator to a keyed service, resolve it by key, and the decorator is applied.

> is it able to register decorator only for one scope="handler"?

You can add decorators in child lifetime scopes and they will apply only in that scope.

> how it works with adapters?

The new syntax is for decorators and not adapters.

> If i
register service in scope=handler
register 7 decorators in scope=handler
register adapter from scope=handler to global (fromKey="handler", toKey not defined)
register 13 global decorators
Will they all work together?

You will need to test this one out for yourself.
