### ISSUE TITLE
Not compatible with .NetPortable 4.5 via Nuget

### ISSUE THREAD

**Issue by ivanlopezmolina** [autofac/Autofac#910] opened 2018-04-19 19:56 UTC
Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Any solution?

Thanks.

**Comment by ivanlopezmolina** [comment] 2018-04-19 20:43
Hi @tillig  

Correct me if I'm wrong, I think you are talking about .NetStardard and I'm talking about .NetPortable.

Thanks!

**Comment by tillig** [comment] 2018-04-19 20:54
@ivanlopezmolina Please take a moment to look through the documentation I linked in my comment. Portable Class Libraries have been replaced by using `netstandard` in the .NET space. In the process of doing that, NuGet and .NET have created "equivalent profiles" so you can see that `Profile111` from Portable Class Libraries is compatible with `netstandard1.1`.

When PCL was superseded by `netstandard`, NuGet tooling was also updated to understand the compatibility matrix. When we see errors like `Profile111` not being compatible with `netstandard1.1` it usually means the tools - NuGet and Visual Studio - aren't updated far enough to have the compatibility matrix built in.

Hence: **Please make sure you have the latest Visual Studio and NuGet.**

If you have the latest tooling and you're still seeing the problem, we need to see a reproduction so we can try replicating the behavior.

**Comment by ivanlopezmolina** [comment] 2018-04-19 21:01
@tillig Thanks 

I'm using Visual Studio for Mac in a Xamarin.Forms project, it created the solution with a PCL, then I'll try to migrate it to Standard,

Thanks again,

My best.

**Comment by tillig** [comment] 2018-04-19 21:06
I'm going to close this for now. If it continues to be an issue _and_ you can show us a reproduction where we can see it in action, we can reopen.

I might recommend StackOverflow first since there are more folks available there and definitely more folks familiar with Xamarin.Forms and VS for Mac. If you do that, instead of double-posting, please just put a link to the question in this issue and we can follow up on StackOverflow.

**Closed by tillig** 2018-04-19 21:06 UTC
