### ISSUE TITLE
Consider allowing a delegate to return null when ResolveOptional is being used.

### ISSUE THREAD

**Issue by huysentruitw** [autofac/Autofac#1342] opened 2022-08-22 08:37 UTC
**NOTE**: I have seen [this slightly related issue](https://github.com/autofac/Autofac/issues/708) but it is not exactly the same. The behavior of the `Resolve` method is correct as you have mentioned, but the behavior of `ResolveOptional` is weird in combination with a custom delegate service activator.

## Problem Statement

When using Autofac in combination with MS DI (using `AutofacServiceProviderFactory`), the behavior of `serviceProvider.GetService` (optionally resolving a service)  in combination with a delegate registration fails when the delegate returns `null`, while this is supported by MS DI when you don't throw Autofac in the mix.

A test demonstrating this difference in behavior:

```
[Test]
public void GetService_ShouldAllowNullFromDelegate()
{
    var serviceCollection = new ServiceCollection();
    serviceCollection.AddScoped<MyService>(sp => null);
    var serviceProvider = serviceCollection.BuildServiceProvider();

    // This works:
    Assert.That(serviceProvider.GetService<MyService>(), Is.Null);

    var factory = new Autofac.Extensions.DependencyInjection.AutofacServiceProviderFactory();
    var builder = factory.CreateBuilder(serviceCollection);
    var serviceProviderWithAutofac = factory.CreateServiceProvider(builder);

    // This fails:
    Assert.That(serviceProviderWithAutofac.GetService<MyService>(), Is.Null);
}
```

Because of this, we cannot trust the runtime behavior of `sp.GetService` vs `sp.GetRequiredService` in our application.

## Desired Solution

A delegate should be allowed to return `null`, as it should be treated as a custom activator. Otherwise the existence of `Resolve` vs `ResolveOptional` doesn't make sense in combination with such custom activator.

In Autofac, I believe this test should succeed:

```c#
[Fact]
public void WhenDelegateReturnsNull_ResolveOptionalReturnsNull()
{
    var builder = Factory.CreateEmptyComponentRegistryBuilder();
    builder.Register(Factory.CreateDelegateRegistration<string>(null));

    var target = new ContainerBuilder(builder).Build();

    var inst = target.ResolveOptional<string>();

    Assert.Null(inst);
}
```

## Alternatives You've Considered

I tried to create a PR, but the fact that an instance cannot be `null` during the resolve operation is baked-in very hard in Autofac, while in my opinion this should only be checked at the very end. So this would probably be a breaking change. My idea would be to pass a `allowNullInstance` boolean to the `ResolveRequest` object so we know when the Instance is allowed to be `null`. We would set `allowNullInstance` to `true` when creating the `ResolveRequest` from `TryResolveService`. But even then, we would have to remove the `[DisallowNull]` attribute on `Instance` and remove the `null`-check in the `DelegateActivator`.

**Comment by alistairjevans** [comment] 2022-09-17 07:54
The general principle we've followed is that components that consume other services, would not generally expect a service to be null, if a service has been registered. You've already linked to the issue #708 where we've outlined the design choice to that regard.

The `ResolveOptional` case where a delegate returns null is an interesting one, but I still think it's unwise to return null from a delegate registration. I often find returning a `no-op` implementation of a service for a delegate registration when there is nothing to do can often be cleaner than returning null from the perspective of the consuming component, which doesn't need to check for null, it can just happily consume the service without having to modify the component itself.

I'll also add that if you have nullable reference types enabled (which is the default in recent project templates), then you'll get a compiler warning trying to return a nullable type from the registered Microsoft DI Lambda:

![image](https://user-images.githubusercontent.com/19165743/190846499-969512d6-21a1-4b8a-9f58-537926e6af15.png)

Evidently MS don't think you should be returning null there either, probably because they're using `null` on `GetService` to indicate the service has not been registered.

Anyway, besides all that, it would be a big breaking change for our users to change now what happens if they return null from an activator, so I'm going to close this as "functioning as designed".

**Closed by alistairjevans** 2022-09-17 07:54 UTC
