### ISSUE TITLE
[4.9.3] ResolutionExtensions.TryResolve ArgumentNullException

### ISSUE THREAD

**Issue by tNRevan** [autofac/Autofac#1015] opened 2019-08-14 11:40 UTC
After updating 4.9.2 -> 4.9.3 I get the exception when calling `ResolutionExtensions.TryResolve(this IComponentContext context, Type serviceType, out object instance);`:

`System.ArgumentNullException: 'Value cannot be null.
Parameter name: type':
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
   at Autofac.Util.TypeExtensions.ParameterCompatibleWithTypeConstraint(Type parameter, Type constraint)
   at Autofac.Util.TypeExtensions.<>c__DisplayClass7_1.<IsCompatibleWithGenericParameterConstraints>b__1(Type constraint)
   at System.Linq.Enumerable.Any[TSource](IEnumerable'1 source, Func'2 predicate)
   at Autofac.Util.TypeExtensions.IsCompatibleWithGenericParameterConstraints(Type genericTypeDefinition, Type[] parameters)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator'2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17'2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator'2.MoveNext()
   at Autofac.Core.Registration.ComponentRegistry.GetInitializedServiceInfo(Service service)
   at Autofac.Core.Registration.ComponentRegistry.RegistrationsFor(Service service)
   at System.Linq.Enumerable.<SelectManyIterator>d__17'2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator'2.MoveNext()
   at Autofac.Core.Registration.ComponentRegistry.GetInitializedServiceInfo(Service service)
   at Autofac.Core.Registration.ComponentRegistry.TryGetRegistration(Service service, IComponentRegistration& registration)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable'1 parameters, Object& instance)
   at XXX.Core.IoC.ContravariantFactory'1.ResolveGenericType(Object obj, Type& closedGenericType)
   at XXX.GUI.Options.OptionViewResolver.GetDataTemplateFor(Type optionType)
`

I am resolving for the `interface IOptionViewFactory<in BasicOption>`. There is a registered type implementing the interface: `CommonOptionViewFactory : IOptionViewFactory<BasicOption>, ...` I also use the ContravariantRegistrationSource. Reverting back to 4.9.2 fixes the issue. I don't use any integration package. I use .NET Framework 4.7.2.

**Comment by alistairjevans** [comment] 2019-08-14 11:46
I believe this is a duplicate of #1009, which has been fixed; 4.9.4 will contain the fix.

**Closed by alistairjevans** 2019-08-14 11:46 UTC
Labels: duplicate
