### ISSUE TITLE
Request for registration validation

### ISSUE THREAD

**Issue by mrychter** [autofac/Autofac#872] opened 2017-09-28 06:17 UTC
Hi,

I'm building core services for large app and we switched from castle windsor to autofac. Everything is working fine in automatic registration approch using assemly scanning and modules but we have latelly interesting case: there were 2 implementations of one interface and autofac of course register them in random order that wrong implementation was resolved from business point of view. Of course manual registration do the job but it would be nice to have some validation on IContainer level to at least give as output information about every single registered service and if it has more then one implementation it should mark this default implmentation - which will be resolved when asking container using resolve<ISomeService>. The purpose is to force developers to register specific concrete implementation when there are available multiple but maintain auto registration. 

I looked in code and there is a way but i don't want to go deep using reflection - it wouldbe nice to have public methods for this purpose.

Or maybe thaere are already stuff that is presnt in autofac 4.1?

**Comment by tillig** [comment] 2017-09-28 12:13
Duplicate of #853

**Closed by tillig** 2017-09-28 12:13 UTC
