### ISSUE TITLE
Autofac 6+ fails Biztalk Build: 'The "AddBizTalkHiddenReferences" task failed unexpectedly.'

### ISSUE THREAD

**Issue by fabsenet** [autofac/Autofac#1286] opened 2021-08-24 13:25 UTC
## Describe the Bug

New BizTalk Project with added Autofac reference fails to build:
```txt
PS C:\code\autofacRepro> msbuild
Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 8/24/2021 3:01:10 PM.
Project "C:\code\autofacRepro\autofacRepro.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Any CPU".
Project "C:\code\autofacRepro\autofacRepro.sln" (1) is building "C:\code\autofacRepro\autofacRepro.btproj" (2) on node 1 (default targets).
C:\Program Files (x86)\MSBuild\Microsoft\BizTalk\BizTalkCommon.targets(190,9): error MSB4018: The "AddBizTalkHiddenReferences" task failed unexpectedly. [C:\code\autofacRepro\autofacRepro.btproj]
C:\Program Files (x86)\MSBuild\Microsoft\BizTalk\BizTalkCommon.targets(190,9): error MSB4018: System.ArgumentException: String cannot have zero length. [C:\code\autofacRepro\autofacRepro.btproj]
C:\Program Files (x86)\MSBuild\Microsoft\BizTalk\BizTalkCommon.targets(190,9): error MSB4018:    at System.Reflection.AssemblyName..ctor(String assemblyName) [C:\code\autofacRepro\autofacRepro.btproj]
C:\Program Files (x86)\MSBuild\Microsoft\BizTalk\BizTalkCommon.targets(190,9): error MSB4018:    at Microsoft.VisualStudio.BizTalkProject.BuildTasks.AddBizTalkHiddenReferences.GetAssemblyNamesFromItems(ITaskItem[] items) [C:\co
de\autofacRepro\autofacRepro.btproj]
C:\Program Files (x86)\MSBuild\Microsoft\BizTalk\BizTalkCommon.targets(190,9): error MSB4018:    at Microsoft.VisualStudio.BizTalkProject.BuildTasks.AddBizTalkHiddenReferences.Execute() [C:\code\autofacRepro\autofacRepro.btproj
]
C:\Program Files (x86)\MSBuild\Microsoft\BizTalk\BizTalkCommon.targets(190,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\code\autofacRepro\autofacRep
ro.btproj]
C:\Program Files (x86)\MSBuild\Microsoft\BizTalk\BizTalkCommon.targets(190,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [C:\code\autofacRepro\autofacRepro.btproj]
Done Building Project "C:\code\autofacRepro\autofacRepro.btproj" (default targets) -- FAILED.

Done Building Project "C:\code\autofacRepro\autofacRepro.sln" (default targets) -- FAILED.

Build FAILED.
```

## Steps to Reproduce

 - Stack: Windows 10, Visual Studio 2019 professional, BizTalk Server 2020 developer edition.
 - In Visual Studio create a new Biztalk Server Project
 - Manage Nuget Package, Add Autofac
 - F6 (Build) or run msbuild

I attached the sample project but sadly you will need the Biztalk Installation to follow along.
[autofacRepro.zip](https://github.com/autofac/Autofac/files/7039366/autofacRepro.zip)

## Expected Behavior

Build without errors

## Dependency Versions

Autofac: 6.2.0

packages.config file:
```xml
<packages>
  <package id="Autofac" version="6.2.0" targetFramework="net472" />
  <package id="Microsoft.Bcl.AsyncInterfaces" version="5.0.0" targetFramework="net472" />
  <package id="System.Buffers" version="4.5.1" targetFramework="net472" />
  <package id="System.Diagnostics.DiagnosticSource" version="5.0.1" targetFramework="net472" />
  <package id="System.Memory" version="4.5.4" targetFramework="net472" />
  <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net472" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="5.0.0" targetFramework="net472" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.4" targetFramework="net472" />
</packages>
```

## Additional Info

The repro is the essence of migrating a rather large biztalk app to biztalk 2020. The error itself is neither helpful nor is it covered in recent search results. I disassembled the AddBizTalkHiddenReferences build task, but I am not sure, I can share any of it here because of copyright risks. The task gets a list of project references and checks, whether a handful of biztalk assemblies are already added and otherwise will add them before building. I could not track the real issue here exactly, but it might have to do with the assembly name. somewhere some string becomes empty.

Interestingly autofac 5.2 compiles just fine. 6.0 - 6.2 fail the build.

**Comment by tillig** [comment] 2021-08-24 13:54
I'll be totally up front here - I have never used BizTalk and I don't really have the ability to debug any of this. It doesn't sound like an Autofac issue, though I recognize it may seem like it. The `AddBizTalkHiddenReferences` task, if you search for `AddBizTalkHiddenReferences task failed unexpectedly`, yields a lot of reasons the failure could happen. I recognize the results may not be recent, but that doesn't necessarily mean they're not valid.

If it was me, I'd probably pop open the assembly with the build task (Google tells me it's `Microsoft.VisualStudio.BizTalkProject.BuildTasks.dll`) in a disassembler like [dotPeek](https://www.jetbrains.com/decompiler/) or [JustDecompile](https://www.telerik.com/products/decompiler.aspx) and see what the task is actually doing inside.

However, here's my hypothesis:

It looks like it's failing in a method `GetAssemblyNamesFromItems` where it's trying to create a new `System.AssemblyName` and that's exploding. I know in MSBuild an "item" is an XML element from inside an `ItemGroup`.

Looking in your `btproj` file, you have `ItemGroup` three times - one for references, one for compile items, one for `None` items to ignore. Since it's complaining about the assembly name of something, let's assume it's a references problem.

I see you're using the "original" style of references, where it's got `HintPath` and `packages.config` rather than newer reference style. As part of that, I see that the `HintPath` for Autofac is the only one that has `netstandard` in it. All the others are `net45` or `net461` or similar.

**That seems interesting** and leads me to my total shot-in-the-dark guess: _Perhaps the way the `AssemblyName` is being created is not compatible with `netstandard2.0` somehow?_

Build tasks don't necessarily run in the same framework as the target of the project. Your project may target .NET 4.7.2, but the build tasks may have been built against (and be running?) .NET 4.5.1, which isn't `netstandard2.0` compatible. They're doing the build, not the runtime work, so that's totally possible.

You could test it by rolling back Autofac and then updating (or adding) some other `netstandard2.0` dependency. I don't have a suggestion on exactly what. However, it should yield the same error.

You might be able to fix it by using a .NET Core version of MSBuild - `dotnet msbuild myproject.proj` - which would force the _build_ to run in a newer framework.

However, that's just my guess based on what's here. Obviously I can't reproduce it or troubleshoot it.

And... since I can't repro it, troubleshoot it, or otherwise attribute the issue _to Autofac_, I'm going to close the issue. I'd love to help more, but my time is pretty limited lately and I'd put money down that this is a build/target framework/BizTalk issue, not Autofac. I'm sorry **I can't help more**. If you're able to narrow it down to an actual Autofac issue (ie, not a build error with a potentially poorly written build task) and show us a repro that we can use to troubleshoot, we can open the issue back up.

**Closed by tillig** 2021-08-24 13:54 UTC

**Comment by fabsenet** [comment] 2021-08-24 14:48
Hi @tillig,

thats fair and okay to me. I reply for now to mostly help others which are maybe landing here via google:

You are partly right, as I had the same idea and tried to add other nuget packages for tests as well. nodatime (3.0.5) or Azure.Storage.Blobs (12.9.1). All these have in common that they are not listing .net framework as a dependency but .net standard or .net 5.
