### ISSUE TITLE
Child container with AnyConcreteTypeNotAlreadyRegisteredSource in parent container throws on resolving instance

### ISSUE THREAD

**Issue by inf9144** [autofac/Autofac#1357] opened 2022-11-30 16:21 UTC
Hello,
i have two classes "Outer" and "Inner". "Inner" is a dependency for "Outer".
Outer is registered as type and inner is registered as instance because it's constructor is private.
Both are registered to a child lifetimescope. The root lifetimescope has AnyConcreteTypeNotAlreadyRegisteredSource.
Autofac throws a NoConstructorsFoundException for inner and does not respect the registration of the instance.
If you remove AnyConcreteTypeNotAlreadyRegisteredSource everything works like expected.

Sample code:

```
internal class Program {
   private static void Main(string[] args) {
      ContainerBuilder builder = new();
      _ = builder.RegisterSource<AnyConcreteTypeNotAlreadyRegisteredSource>();

      var container = builder.Build();

      var childContainer = container.BeginLifetimeScope(childContainerBuilder => {
         _ = childContainerBuilder
            .RegisterType<Outer>();

         _ = childContainerBuilder
            .RegisterInstance(Inner.Instance);
      });

      var resolved = childContainer.Resolve<Outer>();
      _ = childContainer.Resolve<Inner>();
   }
}

public class Outer {

   public Outer(Inner inner) {

   }
}

public class Inner {
   public static Inner Instance = new();

   private Inner() { }
}
```

Can you please help me? I cant see why this is happening.

Best regards,
Alex

**Comment by tillig** [comment] 2022-11-30 16:29
ACTNARS is really fussy and, honestly, has always been far more trouble than it's worth. I honestly wish we'd just deprecate that thing.

**This is a duplicate of #1028** - for which we do not have a solution. PRs welcome. However, if there is _any possible way_ you can get away with _not_ using ACTNARS, your life will be better for it. Register things you want to inject and nothing else.

Side note, that whole `_=` discard assignment seems weird. You don't have to do that you know.

**Closed by tillig** 2022-11-30 16:29 UTC

**Comment by inf9144** [comment] 2022-11-30 16:49
> ACTNARS is really fussy and, honestly, has always been far more trouble than it's worth. I honestly wish we'd just deprecate that thing.
> 
> **This is a duplicate of #1028** - for which we do not have a solution. PRs welcome. However, if there is _any possible way_ you can get away with _not_ using ACTNARS, your life will be better for it. Register things you want to inject and nothing else.

What i right now use it for is: I got classes with dependencies from the container that i don't want to register because they are used at exactly one location in my code. If i could do Resolve<MyType> which would work if all constructor parameters can be filled, i would be happy. I just want to avoid hundreds of lines boilerplate for those types. :-/

> Side note, that whole `_=` discard assignment seems weird. You don't have to do that you know.
Misconfigured Visual Studio clean up settings - used my preview instance where i try a lot ;-)

**Comment by tillig** [comment] 2022-11-30 16:53
> I got classes with dependencies from the container that i don't want to register because they are used at exactly one location in my code

Generally stuff like this can be handled with assembly scanning. Even if you used assembly scanning to specify "all types in a namespace in this assembly over here" or something like that, it might be cleaner than using ACTNARS.

**Comment by inf9144** [comment] 2022-12-05 14:19
Adjusted to assembly scanning. You are totally right - it's much better and i found some errors that ACTNARS did cover from me (wrong instance injected and such). But i think you are right - this thing should be deprecated or a warning should be adeed to the documentation. At first glance reading the documentation it sounds really nice and you build your app on sand :-/

**Comment by LongJSilver** [comment] 2026-04-14 17:01
Hello, 
I have a similar problem with ACTNARS and subscopes, and i was just about to open an issue for it (with minimal example project and all) when i stumbled into this one. I don't know If the preferred option would be opening a new duplicate issue instead of adding my perspective here, in that case let me know and i will do so.

I understand the "Just register everything you need" argument but i'm dealing with an application that really is unaware of the types it might need to construct until moments before it needs to do so (it has to do with dynamically loaded plugins), and is thus unable to register everything at startup; now since registration is forbidden after building the container, anything that comes later can only be handled in 2 ways:

1. Once you know the type you need to create, instantiate a dummy subscope, register that one type and construct it. This works and i have done so, but it feels wasteful and brittle, but also hints (to me at least) that this operation *should* be possible natively without workarounds.
2. Use an equaly ugly trick like this:
``` csharp
        IComponentContext result = null!; //to be captured

        bool WorkaroundPredicate(Type t) {
            return result != null && result.IsRegistered(t);
        };

        builder.RegisterSource(new AnyConcreteTypeNotAlreadyRegisteredSource(WorkaroundPredicate));

        //register stuff
        builder.Register(BuildService).As(typeof(Service)).SingleInstance();
        builder.RegisterType(typeof(UsefulClass_Registered)).As(typeof(UsefulClass_Registered)).SingleInstance();
        //complete the build and return the container
        return result = builder.Build();

```
  This works because the WorkaroundPredicate gets invoked by ACTNARS just before 
  
  `registrationAccessor(service).Any()`
  
  Which for some reason fails to find a registration when the queried service was registered as factory and has a private constructor; by passing an external function that checks against the entire container we are able to better ascertain whether a registration exists or not, and return before ACTNARS injects itself into the mix (though i suspect if something was only registered *Keyed* then we would miss it because ACTNARS doesn't tell us if it's processing a keyed resolution, and neither it provides us the key to perform the check).

Again, The fact that workarounds like this succeed suggests the registrations are valid and present, but something in the registration source lookup mechanism fails to find them.

Finally an observation: if you happen to know which type is going to raise an exception (like during debug), then Invoking methods like "IsRegistered(serviceType)" 3 times (and swallowing the exception the first 2 times) somehow fixes the problem, and after that the registrations become visible to ACTNARS. If needed i can provide a full example that shows this.

Is there any way this could be looked into? I would try it myself but i really can't find my bearings into this code base :/

**Comment by tillig** [comment] 2026-04-14 17:16
@LongJSilver Don't file a duplicate issue. This is fine.

If I'm super honest, ACTNARS is far more trouble than it's worth. It causes all sorts of problems from registering a bunch of unexpected types and filling in constructors with unexpected dependencies to more complex things like this... and it makes me want to deprecate it rather than keep trying to fight through all the details to make it keep working. It's not something other DI frameworks support, and intentionally so - it's got a lot of downside and very little upside in today's codebases. I'm not saying there's zero value, but the cost/benefit to owning and maintaining ACTNARS - for me (the current pretty much sole person doing any work on Autofac) doesn't balance out.

So: I'm happy to take a PR that won't break backwards compatibility, but ACTNARS is not something I'm going to invest time or effort into in any foreseeable future.

**Comment by LongJSilver** [comment] 2026-04-14 17:32
Thank you for the quick response.

I find your perspective completely reasonable, and your remark that "It's not something other DI frameworks support, and intentionally so" makes me think that maybe this is the wrong tool for the job.

Still, since constructing a type by resolving all its dependencies falls entirely within DI/Container Framework's capability i really don't know what the conventional alternative to using one would be. It would require a tool that deals with the constructor and parameter resolution but still leans on my container of choice to resolve the dependencies once it knows what they are.

Is there something i'm missing? are you able to suggest libraries or even design patterns to deal with problems like this? 
Any insight is appreciated, thank you very much

**Comment by tillig** [comment] 2026-04-14 17:37
The answer, as noted earlier, is to couple assembly scanning with explicit registrations. You're right that the DI framework will create and inject the objects as needed during construction, but the problem here stems from the desire to effectively _register literally every type in the whole application_ (which includes types out of every NuGet package you reference, every `System.*` type from every base library assembly, etc.) and try to make that "just work." (This is effectively what ACTNARS is doing - it's dynamically including every possible type from every referenced library.)

Your problems go away if you are more explicit about what you're registering. Even if it's you explicitly scanning specific libraries (maybe by naming convention, so it's only _your_ app libraries?) and then finding all implementations of certain interfaces of your choosing... even being just that much more selective removes ACTNARS from the mix and solves your problems.

I can't recommend an alternate solution because this _is the solution_. It may not be the solution you want to hear or have to deal with, but... that's the solution. Sorry.

**Comment by LongJSilver** [comment] 2026-04-14 17:51
Alright, thank you for your time! 
Have a nice day
