### ISSUE TITLE
Cannot inject HttpClient for ASP.NET Core AddHttpClient() using an interface

### ISSUE THREAD

**Issue by spetz** [autofac/Autofac#934] opened 2018-09-17 06:59 UTC
Hello,

I've been using Autofac as my default IoC container on top of ASP.NET Core and it works great, however, I found a small issue.

Let's say I have the following class:

```csharp
public class OrdersServiceClient : IOrdersServiceClient
{
    private readonly HttpClient _client;

    public OrdersServiceClient(HttpClient client)
    {
        _client = client;
    }
}
```

Register it using `AddHttpClient()`

```csharp
services.AddHttpClient<OrdersServiceClient>();
```

And of course, I populate the services using Autofac extension:

```csharp
builder.Populate(services);
```

Such code works just fine (Autofac is able to inject `HttpClient` into `OrdersServiceClient`), yet, when I make use of a generic version by providing an interface:

```csharp
services.AddHttpClient<IOrdersServiceClient, OrdersServiceClient>();
```

The Autofac container can't inject `HttpClient` resulting with the following stack trace:

```csharp
Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = OrderCreatedHandler (ReflectionActivator), Services = [MyApp.Handlers.IEventHandler`1[[MyApp.Messages.Events.OrderCreated, MyApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], MyApp.Handlers.Orders.OrderCreatedHandler], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = OrdersServiceClient (ReflectionActivator), Services = [MyApp.Infrastructure.Clients.IOrdersServiceClient], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'MyApp.Infrastructure.Clients.OrdersServiceClient' can be invoked with the available services and parameters:
Cannot resolve parameter 'System.Net.Http.HttpClient client' of constructor 'Void .ctor(System.Net.Http.HttpClient)'. (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = OrdersServiceClient (ReflectionActivator), Services = [MyApp.Infrastructure.Clients.IOrdersServiceClient], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'MyApp.Infrastructure.Clients.OrdersServiceClient' can be invoked with the available services and parameters:
Cannot resolve parameter 'System.Net.Http.HttpClient client' of constructor 'Void .ctor(System.Net.Http.HttpClient)'. (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'MyApp.Infrastructure.Clients.OrdersServiceClient' can be invoked with the available services and parameters:
Cannot resolve parameter 'System.Net.Http.HttpClient client' of constructor 'Void .ctor(System.Net.Http.HttpClient)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetValidConstructorBindings(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
```
I'm using the latest versions of Autofac (4.8.1) and Autofac.Extensions.DependencyInjection (4.3.0).

**Comment by alexmg** [comment] 2018-09-17 13:17
Hi @spetz. I'm glad Autofac is working well for you.

I knocked up a quick test app (ASP.NET Core 2.1) to inject a typed client into a controller using an interface and wasn't able to reproduce this issue. 

In your stack trace it appears you are resolving an `IEventHandler<OrderCreated>` service implemented by `OrderCreatedHandler`. Perhaps more pieces need to be in place to see this issue.

Can you provide a more complete example that reproduces the issue?

**Comment by spetz** [comment] 2018-09-17 14:09
@alexmg thank you for the quick reply.

Mentioned `IEventHandler<OrderCreated>` is just a part of overall services, yet, even when I run try to run in the simplest scenario e.g.

```csharp
private readonly IOrdersServiceClient _client;

public OrdersController(IOrdersServiceClient client)
{
    _client = client;
}

[HttpGet("{id}")]
public async Task<ActionResult<OrderDto>> Get(Guid id)
    => await _client.GetAsync(id);
```

It still crashes with the same error (it works fine for a non-interface injection, as previously described).

```csharp
Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'MyApp.Clients.OrdersServiceClient' can be invoked with the available services and parameters:
Cannot resolve parameter 'System.Net.Http.HttpClient client' of constructor 'Void .ctor(System.Net.Http.HttpClient)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetValidConstructorBindings(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
```

**Comment by peterjohnsonme** [comment] 2018-10-18 19:58
I am getting the same error, in a similar setup.

**Comment by tillig** [comment] 2018-10-18 20:33
I've also set up a repro based on the [example here](https://github.com/aspnet/HttpClientFactory/blob/master/samples/HttpClientFactorySample/Program.cs) and can't reproduce it. It uses the very same typed registration - `services.AddHttpClient<IInterface, TClient>()` - and it resolves correctly. Without a reproduction where this actually fails, we won't be able to troubleshoot it.

Project:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="4.8.1" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="4.3.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
  </ItemGroup>
</Project>
```

Program.cs

```csharp
using System;
using System.Net.Http;
using System.Threading.Tasks;
using Autofac;
using Autofac.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Linq;

namespace HttpClientFactoryTest
{
    public class Program
    {
        private interface IGitHubClient
        {
            Task<HttpResponseMessage> GetJson();
        }

        public static void Configure(IServiceCollection services)
        {
            // Log everything to console.
            services.AddLogging(b =>
            {
                b.AddFilter((category, level) => true);
                b.AddConsole(c => c.IncludeScopes = true);
            });

            // Client configured to get the list of services from GitHub.
            services.AddHttpClient<IGitHubClient, GitHubClient>(c =>
            {
                c.BaseAddress = new Uri("https://api.github.com/");
                c.DefaultRequestHeaders.Add("Accept", "application/vnd.github.v3+json");
                c.DefaultRequestHeaders.Add("User-Agent", "HttpClientFactoryTest");
            });
        }

        public static void Main(string[] args) => Run().GetAwaiter().GetResult();

        public static async Task Run()
        {
            try
            {

                var serviceCollection = new ServiceCollection();

                Configure(serviceCollection);

                var builder = new ContainerBuilder();
                builder.Populate(serviceCollection);
                var container = builder.Build();
                var services = new AutofacServiceProvider(container);

                // This is what will throw if Autofac can't resolve the service...
                Console.WriteLine("Creating a client...");
                var github = services.GetRequiredService<IGitHubClient>();

                Console.WriteLine("Sending a request...");
                var response = await github.GetJson();

                var data = await response.Content.ReadAsAsync<JObject>();
                Console.WriteLine("Response data:");
                Console.WriteLine(data);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error encountered: {0}", ex);
            }

            Console.WriteLine("Press a key to exit...");
            Console.ReadKey();
        }

        private class GitHubClient : IGitHubClient
        {
            public GitHubClient(HttpClient httpClient)
            {
                this.HttpClient = httpClient;
            }

            public HttpClient HttpClient { get; }

            public async Task<HttpResponseMessage> GetJson()
            {
                var request = new HttpRequestMessage(HttpMethod.Get, "/");

                var response = await this.HttpClient.SendAsync(request).ConfigureAwait(false);
                response.EnsureSuccessStatusCode();

                return response;
            }
        }
    }
}
```

**Comment by peterjohnsonme** [comment] 2018-10-18 21:10
I do appreciate the repro here.  In my case, it was a simple out-of-order builder.Populate(serviceCollection) call.

**Comment by laurencee** [comment] 2018-10-23 01:35
In my case what I found the order of the registrations matter.

Works
```
containerBuilder.RegisterModule(new CustomModule(Configuration));
containerBuilder.Populate(services);
```

Doesn't work
```
containerBuilder.Populate(services);
containerBuilder.RegisterModule(new CustomModule(Configuration));
```

**Comment by tillig** [comment] 2018-10-23 16:33
As with everything in registrations, order is _very important_.

- Last in wins. (This is how overrides work.)
- Once you call `Populate` it doesn't matter if you add stuff to the `ServiceCollection` because the point of `Populate` is to translate the contents of the `ServiceCollection` into Autofac. After that's done, it doesn't matter if you add stuff to the `ServiceCollection` because... you already converted everything. It's not a real-time ongoing connection.

I'm going to close this issue. It sounds like order is the factor here. If a repro can be provided that shows the issue in action where the order of registrations is correct, we can reopen at that time.

**Closed by tillig** 2018-10-23 16:33 UTC

**Comment by steelmaker** [comment] 2019-08-05 07:15
I have same problem.

I used AutofacServiceProviderFactory with action parameter.

`var hostBuilder = Host.CreateDefaultBuilder(args)
                                  .ConfigureWebHostDefaults(webBuilder =>
                                   {
                                       webBuilder.UseStartup<Startup>();
                                   })
                                  .UseServiceProviderFactory(new AutofacServiceProviderFactory(builder =>
                                   {
                                       builder.RegisterModule<AutofacModule>();
                                   }))`

And this factory used doubtful order initialization

`public class AutofacServiceProviderFactory : IServiceProviderFactory<ContainerBuilder>
    {
...
        /// <summary>
        /// Creates a container builder from an <see cref="IServiceCollection" />.
        /// </summary>
        /// <param name="services">The collection of services.</param>
        /// <returns>A container builder that can be used to create an <see cref="IServiceProvider" />. 
       </returns>
        public ContainerBuilder CreateBuilder(IServiceCollection services)
        {
            var builder = new ContainerBuilder();

            builder.Populate(services);

            _configurationAction(builder);

            return builder;
        }
...
}
`

May be u have alternative initialization way?

p.s.: 
`webBuilder.ConfigureServices(services => services.AddAutofac())`
used same factory

**Comment by alsami** [comment] 2019-08-05 07:43
@steelmaker have you tried using `ConfigureContainer` delegate within your `Startup` class as explained [here](https://autofaccn.readthedocs.io/en/latest/integration/aspnetcore.html?highlight=ASP.NET%20Core#quick-start-with-configurecontainer)?

From the code you are posting I am assuming that you are already running .NET-Core 3 preview. With an on-going issue [here](https://github.com/autofac/Autofac.Extensions.DependencyInjection/issues/36) as well.

If you feel like the order is wrong I'd kindly asked you to open an issue in that [repository](https://github.com/autofac/Autofac.Extensions.DependencyInjection).
