### ISSUE TITLE
AutoActivate not working for named scope registrations

### ISSUE THREAD

**Issue by joergpichler** [autofac/Autofac#1150] opened 2020-06-15 13:20 UTC
My intention is to register components in lifetimescopes that auto activate once the scope is created. I have found this issue https://github.com/autofac/Autofac/issues/567 where it is stated that it should work, but for me it does not. Happens for 4.9.4 and 5.2.0

    class Program
    {
        public const string InnerScope = nameof(InnerScope);

        static void Main(string[] args)
        {
            var builder = new ContainerBuilder();

            builder.RegisterType<ScopedComponent>().As<IScopedComponent>().InstancePerMatchingLifetimeScope(InnerScope);
            builder.RegisterType<AutoActivatedComponent>().As<IAutoActivatedComponent>()
                .InstancePerMatchingLifetimeScope(InnerScope).AutoActivate();

            var container = builder.Build();

            using (var scope = container.BeginLifetimeScope(InnerScope))
            {
                var autoActivatedComponent = scope.Resolve<IAutoActivatedComponent>();
            }
        }
    }

    public interface IScopedComponent
    {
    }

    public class ScopedComponent : IScopedComponent
    {
    }

    public interface IAutoActivatedComponent
    {
    }

    public class AutoActivatedComponent : IAutoActivatedComponent
    {
        public AutoActivatedComponent(IScopedComponent scopedComponent)
        {
            if (scopedComponent == null)
            {
                throw new ArgumentNullException(nameof(scopedComponent));
            }
        }
    }

**Comment by alistairjevans** [comment] 2020-06-15 13:31
Can you be clear as to what you are seeing vs what you expect?

Are you saying that the `AutoActivatedComponent` constructor is not invoked when the `InnerScope` lifetime scope is created?

**Comment by joergpichler** [comment] 2020-06-15 14:13
Sure. I expect the code to work :)

Currently 'builder.Build()' throws an exception

Autofac.Core.DependencyResolutionException
  HResult=0x80131500
  Message=An error occurred while attempting to automatically activate registration 'Activator = AutoActivatedComponent (ReflectionActivator), Services = [ConsoleApp1.IAutoActivatedComponent, AutoActivate], Lifetime = Autofac.Core.Lifetime.MatchingScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope'. See the inner exception for information on the source of the failure.
  Source=Autofac
  StackTrace:
   at Autofac.Builder.StartableManager.StartStartableComponents(IDictionary`2 properties, IComponentContext componentContext)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\Joerg\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 18

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
DependencyResolutionException: Unable to resolve the type 'ConsoleApp1.AutoActivatedComponent' because the lifetime scope it belongs in can't be located. The following services are exposed by this registration:
- ConsoleApp1.IAutoActivatedComponent
- AutoActivate

Details

Inner Exception 2:
DependencyResolutionException: No scope with a tag matching 'InnerScope' is visible from the scope in which the instance was requested.

If you see this during execution of a web application, it generally indicates that a component registered as per-HTTP request is being requested by a SingleInstance() component (or a similar scenario). Under the web integration always request dependencies from the dependency resolver or the request lifetime scope, never from the container itself.

**Comment by alsami** [comment] 2020-06-15 14:26
I've created a [small project](https://github.com/alsami/AutofacIssue1150) based on the source-code provided by the issue.

Should that even be working like that? There can't be a named-scope when building the container. Changing both registrations to `InstancePerLifetimeScope()` removes the exception.

**Comment by alistairjevans** [comment] 2020-06-15 14:29
I imagine that the problem goes away if the AutoActivating component is registered inside the named lifetime scope's configuration:

```csharp
        var container = builder.Build();

        using (var scope = container.BeginLifetimeScope(InnerScope, cfg => 
        { 
           cfg.RegisterType<AutoActivatedComponent>().As<IAutoActivatedComponent>()
                                                     .InstancePerMatchingLifetimeScope(InnerScope).AutoActivate();
        }))
        {
            var autoActivatedComponent = scope.Resolve<IAutoActivatedComponent>();
        }
```

Something like that anyway.

**Comment by tillig** [comment] 2020-06-15 14:44
We actually have [a unit test that _ensures_ this is the behavior.](https://github.com/autofac/Autofac/blob/2c63e85413249c014bd8dd0c35a7befcccadaf92/test/Autofac.Specification.Test/Features/StartableTests.cs#L35) It's been around for at least five years.

The workaround is, as @alistairjevans said, to register the component in the lifetime scope.

I see the _intent_ of the code is to sort of "pre-load" a thing that will auto activate only in the named lifetime scope. It's not an unreasonable thing to consider now that we have the notion of auto activation of registrations added in a lifetime scope, but it does have some larger implications if we were to consider adding the feature. We'd need to define what the desired behaviors are around additional related cases.

For example, what should happen with this registration?

```c#
builder.RegisterType<AutoActivatedComponent>()
       .InstancePerLifetimeScope()
       .AutoActivate();
```

The root container is a lifetime scope. Does it activate there _and_ in every child? Or does it effectively only auto activate the one time at the container level? If it's intended to skip the root container, how do we inform that? Or is this an API setting? How does it/should it interact with the multitenant support, where each tenant gets a named lifetime scope as their "root container?"

This is a long way of saying:

- This doesn't work now (and somewhat intentionally, too)
- It hasn't worked for at least five years
- It's not a five minute fix so it's best to consider using the workaround if possible
- We should probably decide if this is something we'd like to allow, and, if so, figure out how it should behave in various related cases.
- Whatever comes out of this, we should [update the AutoActivate documentation](https://autofaccn.readthedocs.io/en/latest/lifetime/startup.html#auto-activated-components) to explain what's supported and what's not so this doesn't surprise others.

**Comment by alsami** [comment] 2020-06-15 14:48
I will create an issue for the docs and dig into it a bit to get a better understanding.

**Comment by alsami** [comment] 2020-07-05 07:04
@tillig @alistairjevans 

I looked into it a bit. As @tillig already said, there is a test that actually validates the described problem in this issue. (`StartableTests` -> `AutoActivate_InvalidLifetimeConflictsWithAutoStart`).

In theory, or as far as I understood, we could make that work by changing the behavior of `AutoActivate()` to not throw when there is no matching scope.

So basically this:

```csharp
var containerBuilder = new ContainerBuilder();
containerBuilder
    .RegisterType<SomeService>()
    .InstancePerMatchingLifetimeScope("someNamedScope")
    .AutoActivate();

var container = containerBuilder.Build(); // now we do not throw anymore, but wait for the scope to be created and then auto-activate SomeService

using var someNamedScope = container.BeginLifetimeScope("someNamedScope"); // now SomeService is being created automatically
```

What do you think? Is that desirable or should we stick to the current behavior, add more documentation and maybe a better description when the exception is being thrown?

**Comment by alistairjevans** [comment] 2020-07-05 07:46
I think that `InstancePerMatchingLifetimeScope` combined with `AutoActivate` does intuitively feel like it should only auto-activate within that scope. If there's a change here that won't break the world I'd definitely be in favour.

I'd like to understand more about what you mean by 'not throwing'. I'm assuming you don't mean just to swallow the exception?

One problem we might run into is that AutoActivated only ever fires **once** for a given registration, regardless of nested scopes.

For example, what should intuitively happen here:

```csharp
var containerBuilder = new ContainerBuilder();

containerBuilder
    .RegisterType<SomeService>()
     .AsSelf()
    .InstancePerMatchingLifetimeScope("someNamedScope")
    .AutoActivate();

var container = containerBuilder.Build(); 

// service is activated here
using var someNamedScope = container.BeginLifetimeScope("someNamedScope"); 

// should the same service be activated again in the second scope?
using var aSecondScope = container.BeginLifetimeScope("someNamedScope");
```

Things then get complicated, because now the 'should auto-activate' metadata property is not just a registration attribute, but a registration+scope attribute.

**Comment by alsami** [comment] 2020-07-05 08:02
> I'd like to understand more about what you mean by 'not throwing'. I'm assuming you don't mean just to swallow the exception?

The current behavior says, I will auto activate your service on Container build time but only if I am able to find a [matching scope](https://github.com/autofac/Autofac/blob/develop/test/Autofac.Specification.Test/Features/StartableTests.cs#L35).

If we would make the decision to support auto activated components for named scopes, that are being registered during the initial building of the container, like described in this issue, we would not throw the exception. Instead we would activate it when the actual scope is being created.

> One problem we might run into is that AutoActivated only ever fires **once** for a given registration, regardless of nested scopes.

That is a good question that I've also asked myself. I'd guess that we should not create a shared state between two physically existing scopes.



> Things then get complicated, because now the 'should auto-activate' metadata property is not just a registration attribute, but a registration+scope attribute.

Agree, it would make things more complicated.

**Comment by alsami** [comment] 2020-07-15 16:13
Any further opinions on that? If you were to say that this is by design and should stay that way, I could update the docs.

**Comment by tillig** [comment] 2020-07-15 16:19
I think in the 5.x codeline this is probably just how it is. If there's a way to update it for 6.0, great, but I haven't spent any time on it and don't have time now to look into it. I recognize it's an issue, but it's lower priority [for me] than some others.

**Comment by tillig** [comment] 2021-01-26 21:15
Resolution here is just going to be the update to the docs to caution people about some of these edge cases. [Closed in this PR.](https://github.com/autofac/Documentation/pull/132)

**Closed by tillig** 2021-01-26 21:15 UTC
Labels: enhancement

**Comment by G18SSY** [comment] 2021-11-03 10:40
Just for the benefit of anyone else who ends up reading this issue you can also use the `RegisterBuildCallback()` method and `ChildLifetimeScopeBeginning` event to manually do an AutoActivate type behavior. In my use case I didn't have access to the `BeginLifetimeScope()` method call because this is done in a core library we use at work, so instead I used the below code. It's not particularly elegant but it is a workable solution as a last resort:

``` csharp
protected override void Load(ContainerBuilder builder)
{
    builder.RegisterType<Foo>()
           .As<IFoo>()
           .InstancePerMatchingLifetimeScope("Something");

    builder.RegisterBuildCallback(OnContainerBuild);
}

private static void OnContainerBuild(ILifetimeScope scope)
{
    scope.ChildLifetimeScopeBeginning += OnChildLifetimeScopeBeginning;
    TryAutoActivateFoo(scope);
}

private static void OnChildLifetimeScopeBeginning(object sender, LifetimeScopeBeginningEventArgs e)
    => TryAutoActivateFoo(e.LifetimeScope);

/// <summary>
/// Attempts to resolve a <see cref="Foo"/> as a workaround for AutoActivate() with tagged lifetime scopes.
/// </summary>
private static void TryAutoActivateFoo(ILifetimeScope scope)
{
    bool success = false;

    try
    {
        success = scope.TryResolve(out IFoo _);
    }
    catch (DependencyResolutionException) { }

    if (success)
        Debug.WriteLine("Successfully resolved a Foo");
}
```

In my case I caught the `DependencyResolutionException` because I didn't have access to the tag for the lifetime scope at compile time. If you have access to the tag you're probably better off checking the tag:
``` csharp
private static void TryAutoActivateFoo(ILifetimeScope scope)
{
    if (scope.Tag.Equals("Something"))
        scope.Resolve<IFoo>();
}
```

**Comment by tillig** [comment] 2023-09-09 04:09
Thanks for the feedback, but we're at least three years into this consistent behavior and far more than that on the method names so neither are likely to change in the foreseeable future.
