### ISSUE TITLE
Difference between RegisterType<T>() and RegisterType(Type)

### ISSUE THREAD

**Issue by ksmithRenweb** [autofac/Autofac#840] opened 2017-03-29 16:10 UTC
I spent some time in the Autofac code to understand what is happening that I believe is wrong.

First off, when using `RegisterType<T>()` everything works fine.
It is when you use `RegisterType(Type t)` that interesting behavior occurs.

1) Register Types to ContainerBuilder using `RegisterType(Type t)`
2) Later, try to resolve using `Resolve<T>()` or test with `IsRegistered<T>()`
3) exception occurs because it can't find the registered type.

If you dig into the code, you will find that it is actually registered, but it's GetHashCode() is returning a different hash code. So it can't find the type in the dictionary of registered types.

First attempt at a fix:
1) Update GetHashCode in TypedService to return a hashcode for type.FullName.GetHashCode()
2) Update Equals to compare hashcode to determine equality.
3) different exception occurs. (Cannot cast exception)

While digging into the code I noticed that the difference in `RegisterType<T>()` and `RegisterType(Type t)` is how it uses it's next call. They call `ForType<T>()` and `ForType(Type t)` respectively. Which then build a Registration Builder slightly differently. 
`IRegistrationBuilder<TImplementer, ConcreteReflectionActivatorData, SingleRegistrationStyle>`
vs
`IRegistrationBuilder<object, ConcreteReflectionActivatorData, SingleRegistrationStyle>`

The difference is that the call `RegisterType(Type t)` is telling registration to use it as an object.

My theory is that Autofac is creating an "object" and then trying to cast it as the type you are resolving. Thereby causing the "Cannot cast exception".

This isn't a small bug, since it deals heavily with Autofac's internal wiring. So I wrote off the feature I was writing, and looking for another way.

**Comment by tillig** [comment] 2017-03-29 16:49
Do you have a failing unit test or simple repro you can share? I _kind of_ understand what you're saying but seeing it in a simple, concrete code form can help make sure we're on the same page.

Also, it seems the issue I'd around the difference between `RegisterType<T>()` and `RegisterType(Type)` so I'm going to update the issue title to be less "general."

**Comment by tillig** [comment] 2017-03-29 16:56
Note I also added some formatting to the original question. In your update, try to use backticks around inline code - otherwise the GitHub markdown processor will treat generics like `Resolve<T>()` like there's an inline HTML tag rather than rendering it.

**Comment by tillig** [comment] 2017-04-17 21:06
I'm not able to reproduce this. Here's a set of XUnit tests that do what I gather you're trying to do:

```csharp
using Autofac;
using System;
using Xunit;

namespace AutofacRegisterType.Test
{
    public class RegisterTests
    {
        [Fact]
        public void UsingGeneric()
        {
            var builder = new ContainerBuilder();
            var type = typeof(Dependency);

            // Register using the RegisterType<T>() overload
            builder.RegisterType<Dependency>();
            var container = builder.Build();
            Assert.True(container.IsRegistered<Dependency>());
            Assert.True(container.IsRegistered(type));
            Assert.NotNull(container.Resolve<Dependency>());
            Assert.NotNull(container.Resolve(type));
        }

        [Fact]
        public void UsingTypeObjects()
        {
            var builder = new ContainerBuilder();
            var type = typeof(Dependency);

            // Register using the RegisterType(Type) overload
            builder.RegisterType(type);
            var container = builder.Build();
            Assert.True(container.IsRegistered<Dependency>());
            Assert.True(container.IsRegistered(type));
            Assert.NotNull(container.Resolve<Dependency>());
            Assert.NotNull(container.Resolve(type));
        }

        private class Dependency
        {
        }
    }
}
```

These tests both pass. I tried all the combinations of registering and resolving using both the generic overloads and the reflection-based type overloads and I can't get it to fail.

I'm going to close this and if you can provide a failing unit test that illustrates the issue we can reopen it.

**Closed by tillig** 2017-04-17 21:06 UTC

**Comment by ksmithRenweb** [comment] 2017-06-16 15:56
Sorry I never came back and added a test myself. But. I tracked down the bug, and it's not in Autofac.
What I was trying to do was load types from assemblies and register them with Autofac. Here are a couple of unit tests to highlight what the actual issue is and a fix. 
```
[Test]
public void UnitTestFails()
{
    var assembly = Assembly.LoadFile(@"C:\test.dll");

    var type = assembly.GetType("test.Class");
    Assert.IsNotNull(type);

    Assert.AreEqual(typeof(test.Class), type);
}

[Test]
public void UnitTestPasses()
{
    var assembly1 = Assembly.LoadFile(@"C:\test.Class.dll");

    var assembly = Assembly.Load(assembly1.FullName); // <<<<<<<<<<<<<<<<<<<<

    var type = assembly.GetType("test.Class");
    Assert.IsNotNull(type);

    Assert.AreEqual(typeof(test.Class), type);
}
```
So, thank you for looking into it. - Kevin
