### ISSUE TITLE
A component with multiple services across registrations that expose different lifetime scopes may not always use the expected lifetime scope

### ISSUE THREAD

**Issue by morgul77** [autofac/Autofac#511] opened 2014-04-10 20:53 UTC
Hi

We have an issue under these exact circumstances:
*Two components (A and B, implementing IA, and IB) share a single interface.
*We register both with instance per dependency(default)
*We then register just B as  IB with instance per lifetimescope

*I expect the result is that resolve IB will  give the same instance everytime within a lifetimescope, which it does, given we create the lifetimescope without a ContainerBuilder, but it fails, if we pass in a containerbuilder.
*It also works given a containerbuilder is passed, if the first compoent we resolve is IB and not IB. Testcode below, and a more detailed linqpad example here:
http://share.linqpad.net/3c7soe.linq

At best, a bad case of inconsistency...

I would like to help solve the issue, but I would need some pointers.
```
       public interface ISomeOtherInterface { }
        public interface IClassA { }
        public interface IClassB { }
        public class ClassB : IClassB, ISomeOtherInterface { }
        public class ClassA : IClassA, ISomeOtherInterface { }

        [Test]
        public void WhenTwoClassesShareAnInterfaceAndOneClassIsInstancePerLifetimeScopeInstancePerScopeShouldBeHonored()
        {
            var builder = new ContainerBuilder();
            //Related to https://github.com/autofac/Autofac/issues/475?
            builder.RegisterType<ClassA>().As<IClassA>().As<ISomeOtherInterface>();
            builder.RegisterType<ClassB>().As<IClassB>().As<ISomeOtherInterface>();
            builder.RegisterType<ClassB>().As<IClassB>().InstancePerLifetimeScope();
            using (var container = builder.Build())
            {
                //using BeginLifetimeScope() without parameters work
                using (var lifetimeScope = container.BeginLifetimeScope())
                {
                    lifetimeScope.Resolve<IClassA>();
                    var obj1 = lifetimeScope.Resolve<IClassB>();
                    var obj2 = lifetimeScope.Resolve<IClassB>();
                    Assert.AreEqual(obj1, obj2, "Excepted that the two objects are the same");
                }
                //using BeginLifetimeScope() without parameters work
                using (var lifetimeScope = container.BeginLifetimeScope(x => { }))
                {
                    lifetimeScope.Resolve<IClassA>();
                    var obj1 = lifetimeScope.Resolve<IClassB>();
                    var obj2 = lifetimeScope.Resolve<IClassB>();
                    Assert.AreEqual(obj1, obj2, "Excepted that the two objects are the same");
                }
            }
        }
```

**Comment by tillig** [comment] 2016-10-24 16:42
I added the failing unit test noted in the original issue and the test no longer fails. Apparently, at some point in the time since the issue was filed, changes were made to fix the cause of the issue.

I'm going to close this, but if a new failing unit test can be provided, we can re-open or open a new issue.

**Closed by tillig** 2016-10-24 16:42 UTC
Labels: bug
