### ISSUE TITLE
Autofac does not resolve generic interface when object is create by Activator

### ISSUE THREAD

**Issue by JannyM85** [autofac/Autofac#1260] opened 2021-03-04 12:21 UTC
Hello I have problem with resolving generic interface. I try build publis/subscireber solution with entity framework, for execute cusotm logic before SaveChages. When I create object with new everithing works perfect. When I create object by Activator, autofac cannot resolve this object.

```csharp
// this code works and autofac resolve type
 if (entity.GetType() == typeof(Voucher))
    await logicExecutor.ExecuteLogicAsync(new DbLogicUpdateEvent<Voucher, AppDbContext>((Voucher)changedEntity.Entity, this));

///This code create the same object. I compare GetType().FullName and are same. But autofac does not resovle object.
if (entity.GetType() == typeof(Voucher))
    {
        var genericBase = typeof(DbLogicUpdateEvent<,>);
        var combinedType = genericBase.MakeGenericType(entity.GetType(), this.GetType());
        var ev = Activator.CreateInstance(combinedType, (Voucher) changedEntity.Entity, this);
        await logicExecutor.ExecuteLogicAsync(ev);
    }

///resolve does not work for object created by activator
public class DbLogicExecutor : IDbLogicExecutor
    {
        private readonly ILifetimeScope _lifetimeScope;

        public DbLogicExecutor(ILifetimeScope lifetimeScope)
        {
            _lifetimeScope = lifetimeScope;
        }

        public virtual async Task ExecuteLogicAsync<TEvent>(TEvent @event)
        {
            var tasks = _lifetimeScope.Resolve<IEnumerable<IDbLogicTask<TEvent>>>();

            foreach (var task in tasks)
            {
                await task.ExecuteLogic(@event);
            }
        }
    }

///Regisration
builder.RegisterAssemblyTypes(typeof(ServiceAfModule).Assembly).AsClosedTypesOf(typeof(IDbLogicTask<>));

///Interface
public interface IDbLogicTask<in TEvent>
    {
        Task ExecuteLogic(TEvent @event);
    }

/// Event
public class DbLogicUpdateEvent<TEntity, TDbContext> : DbLogicEventBase<TEntity, TDbContext>
       // where TEntity : IEntityBase
        where TDbContext : AppDbContext
    {
        public DbLogicUpdateEvent(TEntity entity, TDbContext context) : base(entity, context)
        {
            Entity = entity;
            DbContext = context;
        }
    }
```

When i call this code Autofac resolve type correctly. I have to cast to the event.

` await logicExecutor.ExecuteLogicAsync((DbLogicUpdateEvent<Voucher, AppDbContext>)ev);`

**Comment by tillig** [comment] 2021-03-04 14:57
There are two things running against you here.

First, `System.Activator` does not go through dependency injection. It's the same as calling `new` - like, if you did this, it totally bypasses Autofac.

```csharp
var x = new DbLogicEvent<Foo, Bar>();
```

Using `Activator.CreateInstance` is the same as calling `new`, just with reflection. You're not using Autofac.

Second, I only see one thing (set of things?) getting actually registered with Autofac:

```csharp
builder.RegisterAssemblyTypes(typeof(ServiceAfModule).Assembly).AsClosedTypesOf(typeof(IDbLogicTask<>));
```

You didn't mention which version of Autofac you're using, but we only (just 20-ish days ago?) finished adding the ability to assembly scan for open generic types. If you're using any released version out there, this won't actually work. We haven't released assembly scanning for generics yet.

So...

- If you want Autofac to resolve it, you have to register it. Autofac won't be able to resolve (and populate constructor parameters) in anything that isn't registered with the container.
- If you want Autofac to populate parameters in the constructor, you need to resolve it from Autofac. You can't do `new()` or `Activator.CreateInstance` and get Autofac to magically provide parameters. You have to do `lifetimeScope.Resolve<T>()` to get Autofac to provide the parameters.

If you find that you still aren't getting parameters injected, be sure to try resolving them manually and see what happens. For example, let's say you classes like this:

```csharp
public class Car
{
  public readonly Driver _d;
  public Car(Driver d)
  {
    this._d = d;
  }
}

public class Driver { }
```

If you think Autofac should be able to resolve a `Car` and put the `Driver` in the constructor... try it.

```csharp
container.Resolve<Car>();
```

If it doesn't work, you'll get an exception explaining what the problem was. _Read the whole exception including the nested inner exceptions._ Don't stop reading at the top level. Especially if you have a deep resolution chain, sometimes the problem is a little deeper than the top level.

Fix whatever it is. Maybe you forgot to register something. Maybe you have two constructors that could both fulfill the request and Autofac doesn't know how to pick. It'll tell you.

But... if the question is why Autofac isn't populating stuff that comes through `Activator`... that isn't how DI works, so it's functioning as designed.

**Closed by tillig** 2021-03-04 14:57 UTC
