### ISSUE TITLE
How to unit test a method using Autofac ServiceLocator?

### ISSUE THREAD

**Issue by dinobu** [autofac/Autofac#957] opened 2019-01-27 21:13 UTC
I am trying to unit test a method in my `MyViewModel` which extends from `BaseViewModel`. The `BaseViewModel` has a method like this

```
public class BaseViewModel : INotifyPropertyChanged
{

   protected bool DoSomething()
   {
      if (something)
      {
         ServiceLocator.Current.GetInstance ...; //ERROR
         return true;
      }
      else
      {
         return false;
      }
   }

}
```

Then MyViewModel extends BaseViewModel and has a public Command that calls a method to set a property.  I want to unit test that method and confirm that the property is set:

```
public MyViewModel : BaseViewModel
{
      // I want to test this public Command which calls OnDoSomethig method below.
      // I want to unit test this method and confirm that SelectTask is set but because of the
      // DoSomething using ServiceLocator in BaseViewModel class above, I cannot test
      public Command DoSomethingCommand = new Command(OnDoSomething);

       private void OnDoSomething(TaskModel task)
        {
            if (DoSomething())
            {
                    SelectTask = task;
            }
        }
}
```

The app works as expected but I am trying to unit test (NUnit) a method from `MyViewModel` that calls `DoSomething` from `BaseViewModel`  as explained above.  The unit tests fail on call to `ServiceLocator`

The error I get is

**error CS0119: 'ServiceLocator' is a type, which is not valid in the given context
The ServiceLocator is coming from Autofac.CommonServiceLocator**

**Comment by tillig** [comment] 2019-01-27 21:30
Try qualifying it with the full namespace, like `CommonServiceLocator.ServiceLocator.Current`

**Comment by dinobu** [comment] 2019-01-27 21:48
> Try qualifying it with the full namespace, like `CommonServiceLocator.ServiceLocator.Current`

I am not missing namespace.  I am using CommonServicoLocator in my class.  But regardless, I tried to qualify it with the full namespace as you suggested, same outcome

**Comment by tillig** [comment] 2019-01-27 22:07
Well, that's usually the issue in places like this, but if not we'd need a full repro. The code provided isn't enough to see what's going on.

As noted in the issue template, "how do I..." or other usage questions will likely get a faster response on StackOverflow. We have limited ability to answer questions here and there's a much wider audience to help over there which already includes the project owners.

**Comment by tillig** [comment] 2019-03-07 21:26
Closing as unable to reproduce. I'll put the full unit test I tried below. If you're still having trouble, please open a question on StackOverflow; you're likely to get a larger set of eyes on it faster over there. If you believe you've found a bug, please include a complete/minimal repro (e.g., a unit test) that we can run to verify the behavior.

```c#
using System;
using Autofac;
using Autofac.Extras.CommonServiceLocator;
using CommonServiceLocator;
using Xunit;

namespace AutofacSandbox
{
    public class LocatorTest
    {
        [Fact]
        public void ServiceLocatorDemo()
        {
            var builder = new ContainerBuilder();
            builder.RegisterType<TargetObject>().As<ITargetObject>();
            var container = builder.Build();
            var locator = new AutofacServiceLocator(container);
            ServiceLocator.SetLocatorProvider(() => locator);
            var vm = new ViewModel();
            vm.DoSomething(); // Will resolve and assert.
        }
    }

    public interface ITargetObject { }

    public class TargetObject : ITargetObject { }

    public class ViewModel
    {
        public void DoSomething()
        {
            var obj = ServiceLocator.Current.GetInstance<ITargetObject>();
            Assert.NotNull(obj);
        }
    }
}
```

**Closed by tillig** 2019-03-07 21:26 UTC
